// frontend/src/faq/components/QuestionAndAnswer.tsx
import React from 'react';
import Twemoji from '../../website/components/Twemoji';
import type {SingleLanguageQuestionAndAnswer} from '../faqContent';

export default function QuestionAndAnswer({id, question, answer}: SingleLanguageQuestionAndAnswer) {
    return <div className="faqItem" id={id}>
        <Twemoji>
            <dt><strong>🅠: {question}</strong></dt>
            <dd>🅐: {answer}</dd>
        </Twemoji>
    </div>;
}

// frontend/src/faq/components/QuestionAndAnswer.svelte
<script lang="ts">
    import type { SingleLanguageQuestionAndAnswer } from '../faqContent'

    const { id, question, answer }: SingleLanguageQuestionAndAnswer = $props()
</script>

<div class="faqItem" {id}>
    <!-- eslint-disable svelte/no-at-html-tags -- trusted: renders our own FAQ question/answer content, not user input -->
    <dt><strong>🅠: {@html question}</strong></dt>
    <dd>🅐: {@html answer}</dd>
    <!-- eslint-enable svelte/no-at-html-tags -->
</div>
