// frontend/src/faq/components/QuestionsAndAnswersList.svelte
<script lang="ts">
    import QuestionAndAnswer from './QuestionAndAnswer.svelte';
    import type {SingleLanguageQuestionAndAnswer} from '../faqContent';

    let {questionsAndAnswers}: {questionsAndAnswers: SingleLanguageQuestionAndAnswer[]} = $props();
</script>

<dl class="faqList">
    {#each questionsAndAnswers as questionAndAnswer (questionAndAnswer.id)}
        <QuestionAndAnswer id={questionAndAnswer.id} question={questionAndAnswer.question} answer={questionAndAnswer.answer}/>
    {/each}
</dl>

// frontend/src/faq/components/QuestionsAndAnswersList.jsx
import React from 'react';
import QuestionAndAnswer from './QuestionAndAnswer.jsx';

/**
 * @param {{id: string, question: Component, answer: Component}[]} questionsAndAnswers
 * @returns {Component}
 * @constructor
 */
export default function QuestionsAndAnswersList({questionsAndAnswers}) {
    return <dl className="faqList">
        {questionsAndAnswers.map(questionAndAnswer =>
            <QuestionAndAnswer id={questionAndAnswer.id}
                               question={questionAndAnswer.question}
                               answer={questionAndAnswer.answer}
                               key={questionAndAnswer.id}/>)}
    </dl>;
}
