// frontend/src/materials/own-content/hu/week12-freestyle-and-review.tsx
import React from 'react';
import FullWidthLocalImage from '../../../challenges/components/FullWidthLocalImage';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'week12-freestyle-and-review',
        title: 'Szabad fotózás tippek, és egy kis visszatekintés',
        author: 'Photato',
        publishDate: new Date('2020-06-07'),
        publisherName: 'Photato',
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <FullWidthLocalImage fileName="cranes.jpg" altText="Darvak" />
        <h2>Visszatekintés</h2>
        <p>Nézzük meg röviden, mit csináltunk az elmúlt 12 héten:</p>
        <ol>
            <li><strong>Gasztrofotók</strong>kal kezdtünk, átnéztük, hogyan készül egy beállított kép és ejtettünk pár szót a mesterséges megvilágításról.</li>
            <li><strong>Épületfotók</strong>kal folytattuk, gyakoroltuk a kinti fotózást és a kompozíciót. Az érdeklődőbbek megismerkedtek a blende és a záridő fogalmával.</li>
            <li><strong>Makrók</strong>at fotóztunk, közben megnéztük, mi az a bokeh, az érdeklődők a linkelt cikkekből tanultak a fókusztávolságról és mélységélességről.</li>
            <li><strong>Utcai fotózás</strong> következett, ahol megtanultuk egy kicsit összeszedni a bátorságunkat és elkapni a pillanatot.</li>
            <li><strong>Sportfotózás</strong> közben megtanultuk a gyorsan mozgó dolgok fényképezését, a záridő, blende és ISO érték beállításait.</li>
            <li><strong>Élőlényeket</strong> fotóztunk, ahol akár gyorsan mozgó állatokat, lassan mozgó növényeket, vagy makrókat, vicces képeket lehetett lőni.</li>
            <li><strong>Hosszan exponált képek</strong>kel gyakoroltuk a gépünk manuális („M”) üzemmódját használni, és gyakoroltuk az előző héten tanult elméletet.</li>
            <li><strong>Csendélet</strong>fotózással folytattuk, és a fehéregyensúly beállításait tanultuk meg.</li>
            <li><strong>Portrék</strong>at fotóztunk, ahol megpróbáltuk mások személyiségét, hangulatát elkapni és megörökíteni.</li>
            <li><strong>Eseményfotózás</strong>t tanultunk, hogy a party- és családi fotóink is profitáljanak a tanfolyamból.</li>
            <li><strong>Önarckép</strong>et készítettünk a múlt héten, újabb bátorságpróbaként 😊</li>
            <li>A héten pedig <strong>szabadon fotózunk</strong>.</li>
        </ol>
        <p>...mert bizony elérkezett a tanfolyam utolsó hete! Reméljük, sokat tanultál, kipróbáltál új dolgokat, közben sikerült néha elhagyni a komfortzónád, és még élvezted is. Most adunk egy utolsó feladatot, és néhány továbblépési lehetőséget, hogy ha szeretnéd, folytathasd a tanulást.</p>

        <h2>A heti feladathoz</h2>
        <p>Most, hogy megtanultál mindent, amit csak a fényképezésről tudni lehet 😉, szabadjára engedünk, fotózz, amit csak szeretnél. A cél, hogy bemutathasd, mit tanultál, és mi jelenleg a kedvenc stílusod. Ha ez segít, gondolj rá úgy, mint egy diplomamunkára. Ha ez inkább frusztrál, akkor ne gondolj rá úgy. 😀 Talán mostanra kialakult benned egy érzés, hogy melyik téma állt legközelebb hozzád az elmúlt hetekben. Vagy valami, amit nem érintettünk, de jó lett volna?</p>
        <p>Pár tipp, hogyan találd meg a témád:</p>
        <ul>
            <li><strong>Mi érdekel most a legjobban? </strong>Van olyan, ami rögtön eszedbe jut erre a kérdésre? Vagy érzed valamivel kapcsolatban a bizsergést, hogy „De jó lenne lefotózni”? (Ha nem, semmi gond, van még néhány ötletünk a tarsolyban.)</li>
            <li><strong>Mi az üzeneted?</strong> Mit tartasz fontosnak? Mi áll hozzád közel? A pandák megmentése? Szegénység az utcákon? Fel akarod vidítani az embereket? (Ha most épp nem fedezel fel magadban különösebb mondanivalót, olvass tovább.)</li>
            <li><strong>Milyen esztétika mozgat meg?</strong> A mozgás, akció? Az emberi testek vagy arcok? Különböző életérzések? Sorsok? Épített geometria? A hétköznapi élet örömei? Apró teremtmények? Természet, természeti jelenségek? A divat?</li>
            <li><strong>Mit fotóznál rendszeresen? </strong>Milyen témában érzed azt, hogy érdekel annyira, hogy akár napi vagy heti szinten fotóznád és nem éreznéd megterhelőnek, inkább érdekesnek? Mit tudnál elképzelni, hogy a szokásoddá váljon?</li>
            <li><strong>Milyen reakciót szeretnél kiváltani az emberekből? </strong>Azt szeretnéd látni, hogy az emberek… gyönyörködnek? Elgondolkoznak? Megdöbbennek? Éhesek lesznek?</li>
            <li><strong>Melyik téma volt a kedvenced?</strong> Ezek voltak: gasztrofotó; épületek; makrók; utcai fotózás; sportfotók, gyors dolgok; hosszú exponálási idő; csendélet; állatok, növények; portré; eseményfotózás; önarckép. Akár végigmehetsz a galériákon, és ihletet meríthetsz mások beküldött képeiből. A fotózásban még a másolás sem ciki, hiszen, minden igyekezet ellenére, nincs két egyforma fénykép.</li>
            <li><strong>Fotózz krumplikat.</strong> Ha egyik fenti kérdés sem hozott ihletet, és egészen nincs ötleted, fotózz krumplikat. Krumplik mindenütt vannak, és mint a fotók esetében, a krumplik közül is mindegyik más. 😊 🥔🥔</li>
        </ul>
    </>;
}

// frontend/src/materials/own-content/hu/week12-freestyle-and-review.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'week12-freestyle-and-review',
            title: 'Szabad fotózás tippek, és egy kis visszatekintés',
            author: 'Photato',
            publishDate: new Date('2020-06-07'),
            publisherName: 'Photato',
        };
    }
</script>

<script lang="ts">
    import FullWidthLocalImage from '../../../challenges/components/FullWidthLocalImage.svelte';
</script>

<FullWidthLocalImage fileName="cranes.jpg" altText="Darvak" />
<h2>Visszatekintés</h2>
<p>Nézzük meg röviden, mit csináltunk az elmúlt 12 héten:</p>
<ol>
    <li><strong>Gasztrofotók</strong>kal kezdtünk, átnéztük, hogyan készül egy beállított kép és ejtettünk pár szót a mesterséges megvilágításról.</li>
    <li><strong>Épületfotók</strong>kal folytattuk, gyakoroltuk a kinti fotózást és a kompozíciót. Az érdeklődőbbek megismerkedtek a blende és a záridő fogalmával.</li>
    <li><strong>Makrók</strong>at fotóztunk, közben megnéztük, mi az a bokeh, az érdeklődők a linkelt cikkekből tanultak a fókusztávolságról és mélységélességről.</li>
    <li><strong>Utcai fotózás</strong> következett, ahol megtanultuk egy kicsit összeszedni a bátorságunkat és elkapni a pillanatot.</li>
    <li><strong>Sportfotózás</strong> közben megtanultuk a gyorsan mozgó dolgok fényképezését, a záridő, blende és ISO érték beállításait.</li>
    <li><strong>Élőlényeket</strong> fotóztunk, ahol akár gyorsan mozgó állatokat, lassan mozgó növényeket, vagy makrókat, vicces képeket lehetett lőni.</li>
    <li><strong>Hosszan exponált képek</strong>kel gyakoroltuk a gépünk manuális („M”) üzemmódját használni, és gyakoroltuk az előző héten tanult elméletet.</li>
    <li><strong>Csendélet</strong>fotózással folytattuk, és a fehéregyensúly beállításait tanultuk meg.</li>
    <li><strong>Portrék</strong>at fotóztunk, ahol megpróbáltuk mások személyiségét, hangulatát elkapni és megörökíteni.</li>
    <li><strong>Eseményfotózás</strong>t tanultunk, hogy a party- és családi fotóink is profitáljanak a tanfolyamból.</li>
    <li><strong>Önarckép</strong>et készítettünk a múlt héten, újabb bátorságpróbaként 😊</li>
    <li>A héten pedig <strong>szabadon fotózunk</strong>.</li>
</ol>
<p>...mert bizony elérkezett a tanfolyam utolsó hete! Reméljük, sokat tanultál, kipróbáltál új dolgokat, közben sikerült néha elhagyni a komfortzónád, és még élvezted is. Most adunk egy utolsó feladatot, és néhány továbblépési lehetőséget, hogy ha szeretnéd, folytathasd a tanulást.</p>

<h2>A heti feladathoz</h2>
<p>Most, hogy megtanultál mindent, amit csak a fényképezésről tudni lehet 😉, szabadjára engedünk, fotózz, amit csak szeretnél. A cél, hogy bemutathasd, mit tanultál, és mi jelenleg a kedvenc stílusod. Ha ez segít, gondolj rá úgy, mint egy diplomamunkára. Ha ez inkább frusztrál, akkor ne gondolj rá úgy. 😀 Talán mostanra kialakult benned egy érzés, hogy melyik téma állt legközelebb hozzád az elmúlt hetekben. Vagy valami, amit nem érintettünk, de jó lett volna?</p>
<p>Pár tipp, hogyan találd meg a témád:</p>
<ul>
    <li><strong>Mi érdekel most a legjobban? </strong>Van olyan, ami rögtön eszedbe jut erre a kérdésre? Vagy érzed valamivel kapcsolatban a bizsergést, hogy „De jó lenne lefotózni”? (Ha nem, semmi gond, van még néhány ötletünk a tarsolyban.)</li>
    <li><strong>Mi az üzeneted?</strong> Mit tartasz fontosnak? Mi áll hozzád közel? A pandák megmentése? Szegénység az utcákon? Fel akarod vidítani az embereket? (Ha most épp nem fedezel fel magadban különösebb mondanivalót, olvass tovább.)</li>
    <li><strong>Milyen esztétika mozgat meg?</strong> A mozgás, akció? Az emberi testek vagy arcok? Különböző életérzések? Sorsok? Épített geometria? A hétköznapi élet örömei? Apró teremtmények? Természet, természeti jelenségek? A divat?</li>
    <li><strong>Mit fotóznál rendszeresen? </strong>Milyen témában érzed azt, hogy érdekel annyira, hogy akár napi vagy heti szinten fotóznád és nem éreznéd megterhelőnek, inkább érdekesnek? Mit tudnál elképzelni, hogy a szokásoddá váljon?</li>
    <li><strong>Milyen reakciót szeretnél kiváltani az emberekből? </strong>Azt szeretnéd látni, hogy az emberek… gyönyörködnek? Elgondolkoznak? Megdöbbennek? Éhesek lesznek?</li>
    <li><strong>Melyik téma volt a kedvenced?</strong> Ezek voltak: gasztrofotó; épületek; makrók; utcai fotózás; sportfotók, gyors dolgok; hosszú exponálási idő; csendélet; állatok, növények; portré; eseményfotózás; önarckép. Akár végigmehetsz a galériákon, és ihletet meríthetsz mások beküldött képeiből. A fotózásban még a másolás sem ciki, hiszen, minden igyekezet ellenére, nincs két egyforma fénykép.</li>
    <li><strong>Fotózz krumplikat.</strong> Ha egyik fenti kérdés sem hozott ihletet, és egészen nincs ötleted, fotózz krumplikat. Krumplik mindenütt vannak, és mint a fotók esetében, a krumplik közül is mindegyik más. 😊 🥔🥔</li>
</ul>
