// frontend/src/upload/components/PhotoTitleInput.jsx
import React from 'react';
import {useI18n} from '../../i18n/components/I18nProvider.jsx';

/**
 *
 * @param {string} title
 * @param {boolean} isDisabled
 * @param {function(string): void} onChange
 * @returns {React.ReactElement}
 * @constructor
 */
export default function PhotoTitleInput({title, isDisabled, onChange}) {
    const {__} = useI18n();

    return <div className='title'>
        <input type='text'
               name='title'
               maxLength={150}
               placeholder={__('Give your photo a title (optional)')}
               disabled={isDisabled}
               value={title}
               onChange={event => onChange(event.target.value)}/>
    </div>;
}

// frontend/src/upload/components/PhotoTitleInput.svelte
<script lang="ts">
    import { __ } from '../../i18n/i18n.svelte'

    interface Props {
        title: string
        isDisabled: boolean
        onChange: (title: string) => void
    }

    const { title, isDisabled, onChange }: Props = $props()
</script>

<div class="title">
    <input
        type="text"
        name="title"
        maxlength="150"
        placeholder={__('Give your photo a title (optional)')}
        disabled={isDisabled}
        value={title}
        oninput={(event) => {
            onChange(event.currentTarget.value)
        }}
    />
</div>
