// frontend/src/admin/components/AdminPage.svelte
<script lang="ts">
    import {onMount} from 'svelte';
    import {__} from '../../i18n/i18n.svelte';
    import {config} from '../../config';
    import {getSessionToken} from '../../auth/auth.svelte';
    import {convertObjectToQueryString} from '../../website/httpHelper';
    import Link from '../../website/components/Link.svelte';

    let version = $state('Loading from server...');

    $effect(() => {document.title = 'Admin - Photato admin';});

    onMount(async () => {
        version = await getVersionFromServer();
    });

    async function getVersionFromServer(): Promise<string> {
        const url = config.backendApi.version.url;
        const accessToken = getSessionToken();
        try {
            const response = await fetch(url + '?' + convertObjectToQueryString({environment: config.backendApi.environment}), {
                method: 'GET',
                mode: 'cors',
                cache: 'no-cache',
                headers: {Authorization: 'Bearer ' + accessToken},
            });
            return (await response.text()) || 'Bad response from server.';
        } catch (error) {
            return `Unknown, could not reach back end. (URL: ${url})`;
        }
    }
</script>

<p><Link to="/admin/photos">{__('Photos')}</Link></p>
<p><Link to="/admin/messages">{__('Messages')}</Link></p>
<p><Link to="/admin/sitemap-generator">{__('Sitemap generator')}</Link></p>
<p>Back end version: {version}</p>

// frontend/src/admin/components/AdminPage.jsx
import React, {useEffect, useState} from 'react';
import {useI18n} from '../../i18n/components/I18nProvider.jsx';
import {NavLink} from 'react-router-dom';
import {config} from '../../config.jsx';
import {useAuth0} from '../../auth/components/Auth0Provider.jsx';
import {convertObjectToQueryString} from '../../website/httpHelper.jsx';

export default function AdminPage() {
    const {getTokenSilently} = useAuth0();
    const {__} = useI18n();
    const [version, setVersion] = useState('Loading from server...');

    useEffect(() => {
        document.title = 'Admin' + ' - Photato admin';
    }, []);

    useEffect(() => {
        async function getVersionFromServer() {
            setVersion(await _getVersionFromServer());
        }

        getVersionFromServer().then(() => {});
    }, []);

    return <>
        <p><NavLink to="/admin/photos">{__('Photos')}</NavLink></p>
        <p><NavLink to="/admin/messages">{__('Messages')}</NavLink></p>
        <p><NavLink to="/admin/sitemap-generator">{__('Sitemap generator')}</NavLink></p>
        <p>Back end version: {version}</p>
    </>;

    async function _getVersionFromServer() {
        const url = config.backendApi.version.url
        const accessToken = await getTokenSilently();
        try {
            const response = await fetch(url + '?' + convertObjectToQueryString({environment: config.backendApi.environment}), {
                method: 'GET', // *GET, POST, PUT, DELETE, etc.
                mode: 'cors', // no-cors, *cors, same-origin
                cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
                credentials: 'same-origin', // include, *same-origin, omit
                redirect: 'follow', // manual, *follow, error
                referrerPolicy: 'no-referrer', // no-referrer, *client
                headers: {
                    Authorization: 'Bearer ' + accessToken
                },
            });
            return (await response.text()) || 'Bad response from server.';
        } catch(error) {
            return `Unknown, could not reach back end. (URL: ${url})`;
        }
    }
}
