// frontend/src/materials/third-party-content/hu/bykyny-kozelfenykepezes-makrofotozas.jsx
import React from 'react';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'bykyny-kozelfenykepezes-makrofotozas',
        title: 'Közelfényképezés - makrofotózás',
        author: 'Bereczky Péter',
        publishDate: new Date('2016-10-01'),
        publisherName: 'bykyny.hu',
        originalUrl: 'http://www.bykyny.hu/fenykepezes-kozelfenykepezes.shtml',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
    </>;
}

// frontend/src/materials/third-party-content/hu/bykyny-kozelfenykepezes-makrofotozas.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'bykyny-kozelfenykepezes-makrofotozas',
            title: 'Közelfényképezés - makrofotózás',
            author: 'Bereczky Péter',
            publishDate: new Date('2016-10-01'),
            publisherName: 'bykyny.hu',
            originalUrl: 'http://www.bykyny.hu/fenykepezes-kozelfenykepezes.shtml',
            isOriginalUrlBroken: false,
        };
    }
</script>
