// frontend/src/materials/third-party-content/hu/canon-tippek-makrofotozashoz.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'canon-tippek-makrofotozashoz',
            title: 'Tippek makrofotózáshoz',
            author: 'Canon',
            publishDate: new Date('2019-05-31'),
            publisherName: 'Canon.hu',
            originalUrl: 'https://www.canon.hu/get-inspired/tips-and-techniques/macro-photography/',
            isOriginalUrlBroken: false,
        };
    }
</script>

<script lang="ts">
    import SimpleFigure from '../../components/SimpleFigure.svelte';
    import ExternalLink from '../../components/ExternalLink.svelte';
</script>

<p>A makrofotózás (közelképek készítése) új lehetőségeket nyit előtted és EOS fényképezőgéped előtt.</p>
<p>Az őszi és téli hónapok különösen kedveznek a makrofotózásnak, mivel ez a lakásban és a szabadban egyaránt remek szórakozás, amikor már rövidek a nappalok és kiszámíthatatlan az időjárás.</p>
<SimpleFigure fileName="Sample%20Pictures%20%28Macro%20Lite%20ON%29_normal%20macro_baby_IMG_0893_Both-Bright_1200x800_tcm128-1374039.jpg" altText="Illusztráció"/>
<h2>Az első lépések</h2>
<p>Kezdetben használhatod azt a zoom alapobjektívet, amely a legtöbb EOS fényképezőgép tartozéka, mielőtt beruházol egy kifejezetten makrofotózáshoz való objektívbe. A maximális nagyítás érdekében használd a teleobjektív állást, és állítsd az EOS gép módválasztó tárcsáját a Makró módra. Erre a gép elvégzi az expozíció és a képstílus beállítását. További információk ezekről a beállításokról. Észre fogod venni, hogy ahogy közelítesz a témához, felerősödik a fényképezőgép bemozdulásából adódó mozgás. Ezt a legegyszerűbben állvány használatával küszöbölheted ki. Már kezdheted is a fotózást</p>
<SimpleFigure fileName="PCA%20-%20Exercise%20Macros%20Photography%20-%20exercise-macro-focus-final-01_1200x800_tcm128-1374041.jpg" altText="Illusztráció"/>
<h2>Mélységélesség és fókuszálás</h2>
<p>Ha olyan témára fókuszálsz, amely közel van az objektívhez, sokkal kisebb a mélységélesség (a fókuszpont előtt és mögött fókuszban lévő terület). A rekeszbeállítástól függetlenül a háttér valószínűleg homályos lesz, habár kisebb (magasabb f szám) rekesz használata esetén a téma nagyobb része lesz fókuszban.</p>
<p>A lehető legjobb beállítás és pontosság érdekében állítsd az objektívet kézi vezérlésre. Látni fogod, hogy a téma nagyításával együtt az apró mozgások is felerősödnek. A fókuszgyűrű legfinomabb beállítása is óriási különbségeket eredményez a fókuszterületen. A legpontosabb fókuszvezérlés a felnagyított Élőkép használatával érhető el.</p>
<h2>Megvilágítás</h2>
<p>Makrofotózásnál különösen fontos a megfelelő fény. Ha beltérben dolgozol, kezdetben elég az ablakon át beszűrődő napfény. Kerüld a közvetlen napsütést (a felhőkön átszűrődőt fény jó), és egy fehér lap segítségével verd vissza a fényt a témára, hogy ne legyenek árnyékok. A lap használata és eltávolítása, illetve a szög megváltoztatása komoly különbségeket eredményez.</p>
<p>Ideális esetben a fényforrás a téma egészét megvilágítja, így az kellően részletes és színes. A Canon makró körvaku és makró ikervaku olyan kiegészítő világítórendszerek, amelyek minden makrofotózáshoz a legjobb fényt biztosítják.</p>
<SimpleFigure fileName="IMG_5302-5325.tif_1200x800_tcm128-1374042.jpg" altText="Illusztráció"/>
<h2>Kompozíció és háttér</h2>
<p>A makrofotózás a részletekről szól, így megéri jól beállítani a témát a háttér előtt. A háttér valószínűleg nem lesz éles, de a színek, a fények és a formák elvonhatják a figyelmet a témáról.</p>
<h2>A következő lépés</h2>
<p>
    <strong>A zoom alapobjektív kezdetben még elmegy a makrofotózáshoz, de vannak speciális objektívek és tartozékok, amelyeket kifejezetten közeli képek készítéséhez terveztek.</strong>
</p>
<h2>Makroobjektív</h2>
<p>Ezek az objektívek kifejezetten makrofotózáshoz készültek, és 1:1 nagyítást tesznek lehetővé (az 1:1 azt jelenti, hogy a téma életnagyságban jelenik meg a fényképezőgép képérzékelőjén). Természetesen nem csak makrók, hanem például portrék készítésére is alkalmasak. Az APS-C érzékelőkhöz első körben a Canon EF-S 60mm f2.8 Macro USM objektívet, a teljes képmezős érzékelőkhöz pedig a Canon EF 100mm f/2.8 Macro USM objektívet ajánljuk. Az EF 100mm f/2.8L Macro IS USM speciális Hibrid képstabilizátorral rendelkezik, melynek segítségével akár kézben tartott géppel is remek makrofotók készíthetők. Ezek a speciális objektívek garantálják, hogy a kép még a széleken is éles, kontrasztos és kiváló minőségű.</p>
<SimpleFigure fileName="CINC_Sample_Extra_IMG_5300_P_S_1200x800_tcm128-1374044.jpg" altText="Illusztráció"/>
<h2>Makró előtétlencsék</h2>
<p>Ezek a meglévő objektív elé szerelhető lencsék lehetővé teszik, hogy közelebbre fókuszálj. Nagyon kis helyet foglalnak, így utazáshoz is ideális kiegészítők. Kétféle Canon makró előtétlencse kapható: a 250D nagyobb, míg a 500D kisebb teljesítményű.</p>
<h2>Közgyűrűk</h2>
<p>A másik lehetőség a meglévő objektív mellé a közgyűrűk használata. Ezek az EOS váz és az objektív közé szerelhetők, lehetővé téve, hogy közelebbre fókuszálj. Kétféle Canon közgyűrű kapható: az EF12 II és az EF25 II. A szám a közgyűrű hosszára utal – a 25 mm-es közgyűrű nagyobb nagyítást tesz lehetővé, mint a 12 mm-es. A közgyűrűkben nincs üveg, így az objektív minősége nem változik, de a megfelelő expozícióhoz a témának több fényt kell kapnia.</p>
<SimpleFigure fileName="CANON_MACRO_TWIN_LITE_MT-26EX-RT%20Sample%20Canon%20Inc%204822%2005_1200x800_tcm128-1374045.jpg" altText="Illusztráció"/>
<h2>Az EOS fényképezőgépek speciális beállításai</h2>
<p>Most, hogy már beruháztál egy makrofotózáshoz való objektívbe vagy tartozékba, érdemes kipróbálni azokat a képkészítési módokat is, amelyek több lehetőséget adnak az expozíció beállítására. Ilyen például a Rekesz-előválasztás (Av) vagy a Kézi (M), amelyekkel igényeid szerint állíthatod be a mélységélességet.</p>
<p>Ha állványt használsz a fényképezéshez, néhány egyszerű trükkel még stabilabbá teheted a fényképezőgépet. Az exponálógomb elnyomása a fényképezőgép bemozdulását okozhatja. Ha nincs különösebb jelentősége annak, hogy melyik pillanatban készül el a kép, állítsd be az önkioldót 2 másodpercre, mert ez alatt az idő alatt megszűnik a mozgás. Ha fontos az időzítés, használj távkioldót. Így pontosan abban a pillanatban készítheted el a képet, amikor szeretnéd, mégsem kell hozzáérned a fényképezőgéphez.</p>
<SimpleFigure fileName="PCA-Macro%20in%20motion-tip-macro-in-motion-SanderMeertinsPhotography-shutterstock_1200x800_tcm128-1374047.jpg" altText="Illusztráció"/>
<h2>Végső simítások</h2>
<p>Most már nagyjából tudod, hogyan készíthetsz jó makrofotókat. Így már ajánlatos RAW formátumban fotózni, és a Canon Digital Photography Professional (<ExternalLink href="https://www.canon.hu/support/Camera_Software/">DPP</ExternalLink>) programjával elvégezni a finombeállításokat. Például az objektívkorrekció, a fehéregyensúly-beállítás és a vágás funkció használatával igazán lenyűgöző képeket készíthetsz.
</p>

// frontend/src/materials/third-party-content/hu/canon-tippek-makrofotozashoz.tsx
import React from 'react';
import SimpleFigure from '../../components/SimpleFigure';
import ExternalLink from '../../components/ExternalLink';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'canon-tippek-makrofotozashoz',
        title: 'Tippek makrofotózáshoz',
        author: 'Canon',
        publishDate: new Date('2019-05-31'),
        publisherName: 'Canon.hu',
        originalUrl: 'https://www.canon.hu/get-inspired/tips-and-techniques/macro-photography/',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <p>A makrofotózás (közelképek készítése) új lehetőségeket nyit előtted és EOS fényképezőgéped előtt.</p>
        <p>Az őszi és téli hónapok különösen kedveznek a makrofotózásnak, mivel ez a lakásban és a szabadban egyaránt remek szórakozás, amikor már rövidek a nappalok és kiszámíthatatlan az időjárás.</p>
        <SimpleFigure fileName="Sample%20Pictures%20%28Macro%20Lite%20ON%29_normal%20macro_baby_IMG_0893_Both-Bright_1200x800_tcm128-1374039.jpg" altText="Illusztráció"/>
        <h2>Az első lépések</h2>
        <p>Kezdetben használhatod azt a zoom alapobjektívet, amely a legtöbb EOS fényképezőgép tartozéka, mielőtt beruházol egy kifejezetten makrofotózáshoz való objektívbe. A maximális nagyítás érdekében használd a teleobjektív állást, és állítsd az EOS gép módválasztó tárcsáját a Makró módra. Erre a gép elvégzi az expozíció és a képstílus beállítását. További információk ezekről a beállításokról. Észre fogod venni, hogy ahogy közelítesz a témához, felerősödik a fényképezőgép bemozdulásából adódó mozgás. Ezt a legegyszerűbben állvány használatával küszöbölheted ki. Már kezdheted is a fotózást</p>
        <SimpleFigure fileName="PCA%20-%20Exercise%20Macros%20Photography%20-%20exercise-macro-focus-final-01_1200x800_tcm128-1374041.jpg" altText="Illusztráció"/>
        <h2>Mélységélesség és fókuszálás</h2>
        <p>Ha olyan témára fókuszálsz, amely közel van az objektívhez, sokkal kisebb a mélységélesség (a fókuszpont előtt és mögött fókuszban lévő terület). A rekeszbeállítástól függetlenül a háttér valószínűleg homályos lesz, habár kisebb (magasabb f szám) rekesz használata esetén a téma nagyobb része lesz fókuszban.</p>
        <p>A lehető legjobb beállítás és pontosság érdekében állítsd az objektívet kézi vezérlésre. Látni fogod, hogy a téma nagyításával együtt az apró mozgások is felerősödnek. A fókuszgyűrű legfinomabb beállítása is óriási különbségeket eredményez a fókuszterületen. A legpontosabb fókuszvezérlés a felnagyított Élőkép használatával érhető el.</p>
        <h2>Megvilágítás</h2>
        <p>Makrofotózásnál különösen fontos a megfelelő fény. Ha beltérben dolgozol, kezdetben elég az ablakon át beszűrődő napfény. Kerüld a közvetlen napsütést (a felhőkön átszűrődőt fény jó), és egy fehér lap segítségével verd vissza a fényt a témára, hogy ne legyenek árnyékok. A lap használata és eltávolítása, illetve a szög megváltoztatása komoly különbségeket eredményez.</p>
        <p>Ideális esetben a fényforrás a téma egészét megvilágítja, így az kellően részletes és színes. A Canon makró körvaku és makró ikervaku olyan kiegészítő világítórendszerek, amelyek minden makrofotózáshoz a legjobb fényt biztosítják.</p>
        <SimpleFigure fileName="IMG_5302-5325.tif_1200x800_tcm128-1374042.jpg" altText="Illusztráció"/>
        <h2>Kompozíció és háttér</h2>
        <p>A makrofotózás a részletekről szól, így megéri jól beállítani a témát a háttér előtt. A háttér valószínűleg nem lesz éles, de a színek, a fények és a formák elvonhatják a figyelmet a témáról.</p>
        <h2>A következő lépés</h2>
        <p>
            <strong>A zoom alapobjektív kezdetben még elmegy a makrofotózáshoz, de vannak speciális objektívek és tartozékok, amelyeket kifejezetten közeli képek készítéséhez terveztek.</strong>
        </p>
        <h2>Makroobjektív</h2>
        <p>Ezek az objektívek kifejezetten makrofotózáshoz készültek, és 1:1 nagyítást tesznek lehetővé (az 1:1 azt jelenti, hogy a téma életnagyságban jelenik meg a fényképezőgép képérzékelőjén). Természetesen nem csak makrók, hanem például portrék készítésére is alkalmasak. Az APS-C érzékelőkhöz első körben a Canon EF-S 60mm f2.8 Macro USM objektívet, a teljes képmezős érzékelőkhöz pedig a Canon EF 100mm f/2.8 Macro USM objektívet ajánljuk. Az EF 100mm f/2.8L Macro IS USM speciális Hibrid képstabilizátorral rendelkezik, melynek segítségével akár kézben tartott géppel is remek makrofotók készíthetők. Ezek a speciális objektívek garantálják, hogy a kép még a széleken is éles, kontrasztos és kiváló minőségű.</p>
        <SimpleFigure fileName="CINC_Sample_Extra_IMG_5300_P_S_1200x800_tcm128-1374044.jpg" altText="Illusztráció"/>
        <h2>Makró előtétlencsék</h2>
        <p>Ezek a meglévő objektív elé szerelhető lencsék lehetővé teszik, hogy közelebbre fókuszálj. Nagyon kis helyet foglalnak, így utazáshoz is ideális kiegészítők. Kétféle Canon makró előtétlencse kapható: a 250D nagyobb, míg a 500D kisebb teljesítményű.</p>
        <h2>Közgyűrűk</h2>
        <p>A másik lehetőség a meglévő objektív mellé a közgyűrűk használata. Ezek az EOS váz és az objektív közé szerelhetők, lehetővé téve, hogy közelebbre fókuszálj. Kétféle Canon közgyűrű kapható: az EF12 II és az EF25 II. A szám a közgyűrű hosszára utal – a 25 mm-es közgyűrű nagyobb nagyítást tesz lehetővé, mint a 12 mm-es. A közgyűrűkben nincs üveg, így az objektív minősége nem változik, de a megfelelő expozícióhoz a témának több fényt kell kapnia.</p>
        <SimpleFigure fileName="CANON_MACRO_TWIN_LITE_MT-26EX-RT%20Sample%20Canon%20Inc%204822%2005_1200x800_tcm128-1374045.jpg" altText="Illusztráció"/>
        <h2>Az EOS fényképezőgépek speciális beállításai</h2>
        <p>Most, hogy már beruháztál egy makrofotózáshoz való objektívbe vagy tartozékba, érdemes kipróbálni azokat a képkészítési módokat is, amelyek több lehetőséget adnak az expozíció beállítására. Ilyen például a Rekesz-előválasztás (Av) vagy a Kézi (M), amelyekkel igényeid szerint állíthatod be a mélységélességet.</p>
        <p>Ha állványt használsz a fényképezéshez, néhány egyszerű trükkel még stabilabbá teheted a fényképezőgépet. Az exponálógomb elnyomása a fényképezőgép bemozdulását okozhatja. Ha nincs különösebb jelentősége annak, hogy melyik pillanatban készül el a kép, állítsd be az önkioldót 2 másodpercre, mert ez alatt az idő alatt megszűnik a mozgás. Ha fontos az időzítés, használj távkioldót. Így pontosan abban a pillanatban készítheted el a képet, amikor szeretnéd, mégsem kell hozzáérned a fényképezőgéphez.</p>
        <SimpleFigure fileName="PCA-Macro%20in%20motion-tip-macro-in-motion-SanderMeertinsPhotography-shutterstock_1200x800_tcm128-1374047.jpg" altText="Illusztráció"/>
        <h2>Végső simítások</h2>
        <p>Most már nagyjából tudod, hogyan készíthetsz jó makrofotókat. Így már ajánlatos RAW formátumban fotózni, és a Canon Digital Photography Professional (<ExternalLink href="https://www.canon.hu/support/Camera_Software/">DPP</ExternalLink>) programjával elvégezni a finombeállításokat. Például az objektívkorrekció, a fehéregyensúly-beállítás és a vágás funkció használatával igazán lenyűgöző képeket készíthetsz.
        </p>
    </>;
}
