// frontend/src/materials/third-party-content/hu/canon-varosi-fotok-keszitese.tsx
import React from 'react';
import SimpleFigure from '../../components/SimpleFigure';
import ExternalLink from '../../components/ExternalLink';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'canon-varosi-fotok-keszitese',
        title: 'Városi fotók készítése',
        author: 'Canon',
        publishDate: new Date('2019-06-17'),
        publisherName: 'Canon.hu',
        originalUrl: 'https://www.canon.hu/get-inspired/tips-and-techniques/city-photography/',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <p>A városok természetüknél fogva zsúfolt és nyüzsgő helyek, de vannak olyan időszakok, különösen éjszaka és kora reggel, amikor lelassul a tempó. Ezekben a napszakokban azonban gyenge fényviszonyok mellett lehet csak fényképezni. Ehhez rövid záridőkre, magas ISO-értékekre és a fényképezőgép mozdulatlanul tartására van szükség.</p>
        <p>Amikor rossz fényviszonyok között fényképezel, először is ki kell kapcsolnod az automatikus vakuhasználatot. Ezt a Vaku kikapcsolva és/vagy a Kézi éjszakai üzemmód használatával érheted el.</p>
        <p>A kisméretű, például 10×15 cm-es vagy 13×18 cm-es képek ideális méretűek ahhoz, hogy azokat megoszd családoddal és barátaiddal. A <ExternalLink href="https://canon.hu/printers/pixma-photo-printers/">PIXMA</ExternalLink> nyomtatóval kinyomtatott képeket akár képeslapként is elküldheted. Az éles képek és élénk színek érdekében fényes papírt, például Photo Paper Plus Glossy vagy Photo Paper Pro papírt használj.
        </p>
        <p>
            <strong>Tipp:</strong> Vaku kikapcsolva üzemmód: fordítsd el a fényképezőgép üzemmódválasztó tárcsáját a Vaku kikapcsolva üzemmódra. Ennél az üzemmódnál a fényképezőgép más beállításokat fog használni a fényképek vaku nélkül történő elkészítéséhez. A gép magasabb fényérzékenység (ISO-értéket), alacsonyabb záridő és tágabb rekesz használatával biztosítja a megfelelő expozíciót.
        </p>
        <h2>A fényképezőgép bemozdulásából adódó elmosódás elkerülése</h2>
        <p>Nagyon rossz fényviszonyok mellett és éjszaka ügyelned kell arra, hogy a fényképezőgép ne mozduljon be a kép elkészítése közben. A fényképezőgép bemozdulása életlenséget eredményezhet és tönkreteheti a képet. Rossz fényviszonyok mellett próbáld meg mindig a földre, stabil asztalra vagy korlátra helyezni a gépet. Már az is sokat segíthet, ha a fényképezőgépet erősen egy falhoz tartod a kép elkészítése közben. A képstabilizátorral ellátott objektívek szintén sokat segíthetnek ilyen helyzetekben.</p>
        <p>
            <strong>Tipp:</strong> A Vaku kikapcsolva üzemmódot használd a múzeumokban és olyan helyeken is, ahol a vakuhasználat nem megengedett, vagy a vakuzás tönkretenné a hangulatot.
        </p>
        <h2>Kézi éjszakai üzemmód</h2>
        <p>Ez a hasznos üzemmód négy képből álló gyors sorozatot készít, majd a képeket egyetlen képpé egyesíti, a minimális bemozduláshoz optimalizálva. Mivel sok városban korlátozzák az állványok használatát, a Kézi éjszakai üzemmóddal biztosíthatod, hogy éjszaka is mindig éles képeket készíthess.</p>
        <h2>Használj gyors, nagy fényerejű fix objektívet</h2>
        <p>Mindig jó, ha van nálad egy nagy fényerejű fix objektív, például egy <ExternalLink href="https://canon.hu/lenses/ef-50mm-f-1-8-stm-lens/">Canon EF 50mm f/1,8 STM</ExternalLink>, mellyel alacsony fényviszonyok mellett is kiváló felvételeket készíthetsz. A kisméretű, könnyű, diszkrét objektív éles és kiváló minőségű képeket garantál. A fix objektívek széles tartományban állítható rekeszbeállításaival fantasztikusan szabályozható a mélységélesség. Annak érdekében, hogy a legtöbbet hozhasd ki ezekből az objektívekből, használd a rekesz-előválasztás (Av) üzemmódot a mélységélesség szabályozásához, vagy a záridő-előválasztást (Tv) a mozgás megörökítéséhez. Az ilyen típusú objektívek másik előnye, hogy a zoomolás helyett folyamatosan mozognod kell a megfelelő fókusztávolság eléréséhez, így nagyobb eséllyel találsz több érdekes nézőpontot a fényképek elkészítéséhez. Városfényképezéshez vagy általános fényképezéshez a <ExternalLink href="https://canon.hu/lenses/ef-24mm-f-2-8-is-usm-lens/">Canon EF 24mm f/2.8 IS USM</ExternalLink> vagy <ExternalLink href="https://canon.hu/lenses/ef-35mm-f-2-is-usm-lens/">Canon EF 35mm f/2 IS USM</ExternalLink> objektívet javasoljuk.
        </p>
        <h2>Legyél mindig felkészülve a fényképezésre</h2>
        <p>Gondoskodj arról, hogy a géped mindig készen álljon a fényképezésre. Ez azt jelenti, hogy a városban sétálva folyamatosan figyelj arra, hogy a fények hogyan változnak körülötted. Ha sötétebb lesz, számíts arra, hogy növelned kell az ISO-értéket, vagy nyitnod kell a rekeszen. Ha pedig több fény áll rendelkezésre, csökkentsd az ISO-értéket, vagy használj szűkebb rekeszt. Így a fényképezőgéped beállításai nagy valószínűséggel közel ideálisak lesznek, ha valamit hirtelen szeretnél lefényképezni.</p>
        <p className="tip">
            <strong>Tipp:</strong> Ha a városban sok a magas épület, figyeld meg, hogy a fény hogyan érkezik az épületek között, és gondold át, hogy az elérhető fényt hogyan használhatod fel a legjobban a fényképeken. Az is megoldás lehet, ha olyan időpontban térsz vissza az adott helyre, amikor a fények megfelelnek az elképzeléseidnek.
        </p>
        <SimpleFigure fileName="G9%20X%20Mark%20II_CINC_Sample_IMG_0515_Monochrome_01_A2_1200x800_tcm128-1374063.jpg" altText="Illusztráció"/>
        <h2>A monokróm mód és a szűrők használata</h2>
        <p>A monokróm képstílus használatával közvetlenül a fényképezőgéppel készíthetsz fekete-fehér felvételeket. Mivel a fekete-fehér képek az árnyékról és a fényekről szólnak, a monokróm mód segítségével megfigyelheted a kontraszt játékát. Az LCD kijelzőn fekete-fehérben fognak megjelenni a képek, de ha RAW formátumban fotózol, a számítógépen végzett utómunka során visszaállíthatod a színes képet.</p>
        <p>Erős napsütésnél a monokróm képstílus kontrasztbeállításának növelésével és sárga szűrő használatával gyakran még drámaibb kontraszt érhető el.</p>
        <p>
            <em><strong>Tudta?</strong> Az árnyékok hosszabbak a nap vége felé közeledve, mint a nap közepén, és verőfényes napokon a legélesebbek, amikor egy felhő sincs az égen.</em>
        </p>
        <h2>
            <ExternalLink href="https://canon.hu/get-inspired/tips-and-techniques/how-to-do-time-lapse-photography/">A time-lapse hatások maximális kihasználása</ExternalLink>
        </h2>
        <p>A time-lapse hatással akkor is nagyszerűen megörökítheted a város nyüzsgését, ha csak rövid időre látogatsz el az adott helyre. Néhány EOS fényképezőgép beépített intervalométerrel van ellátva, melynek használatával a gép néhány másodpercenként felvételt készít.</p>
        <p>Mindig használj stabil állványt a fényképezőgéphez. Megpróbálhatsz például egy magasan fekvő hotelszobából képeket készíteni egy nyüzsgő utcáról, mellyel napfelkeltétől napnyugtáig tartó érdekes felvételt kaphatsz a városról.</p>
        <p>Annak érdekében, hogy elegendő képed legyen a time-lapse felvételhez, ne feledd, hogy minél rövidebb az intervallum, annál hosszabb ideig tart a time-lapse. Ha csak néhány órányi állóképet rögzítesz, használj rövidebb intervallumot, hiszen a videót a szerkesztés során utólag bármikor felgyorsíthatod.</p>
        <h2>A fókusz módosítása</h2>
        <p>A nagyvárosokban, ahol nagy a tömeg, néha nehéz a távoli témákra fókuszálni. A fényképezőgép gyakran az útjába kerülő közeli témákra fókuszál. Nagyon nagy tömegben elképzelhető, hogy sokkal jobban rá kell közelíteni a témára.</p>
        <h2>A tökéletes kép a részletekben rejlik</h2>
        <p>A városfényképezés gyakran az adott városra jellemző egyedi, apró részletek megörökítéséről szól. Például jó ötlet lehet ellátogatni a város piacaira és lefényképezni az árukat (és az azokat áruló embereket).</p>
        <p>A megszokottól eltérő dolgok megörökítése mellett az adott város ikonikus áruiról, például sevillai narancsról, párizsi bagettről vagy berlini kolbászról is készíthetsz képeket.</p>
        <p>
            <strong>Tipp:</strong> Kis témák esetén válaszd ki a makró vagy közelkép módot a fókusz gombbal (a virággal vagy MF szimbólummal jelölt gomb), és menj olyan közel a témához, hogy kitöltse a képet.
        </p>
        <p>Smart Auto üzemmódban a fényképezőgép automatikusan átvált makró módra. Egyszerűen tartsd mozdulatlanul a fényképezőgépet körülbelül egy másodpercig, amíg a kijelző jobb felső részén lévő ikon átvált a virág ikonra.</p>
        <SimpleFigure fileName="EOS_5D_Mark_IV_CINC%20_sample-image20_1200x800_tcm128-1374064.jpg" altText="Illusztráció"/>
        <h2>Fényképezd le ugyanazt a témát több napszakban is</h2>
        <p>Ha időd engedi, készíts képeket különböző időpontokban ugyanarról a városrészről, és örökítsd meg a város ritmusát és változásait.</p>
        <p>Ha elég időd van, ugyanazokat a helyeket különböző napszakokban is meglátogathatod, és megörökítheted a fények és a járókelők változását. Már három-négy, különböző időpontban készített fényképpel is jól érzékelhető a város változása.</p>
        <h2>Mozgó témák fotózása</h2>
        <p>Mozgó témák, például a hídon vagy a téren sétáló emberek, fényképezésekor a legjobb megoldás mozdulatlanul tartani a fényképezőgépet és kikapcsolni a vakut – ennek köszönhetően a fényképezőgép hosszabb zársebességet választ a téma mozgásának kiemeléséhez. Ilyen képek készítésekor mindig olyan felületeket és helyeket kell keresni, ahol a fényképezőgép teljesen stabilan elhelyezhető. Próbálj a záridő-előválasztással (Tv) kísérletezni, ha a gépeden van ilyen üzemmód. Ezzel beállíthatod a záridőt, és kibontakoztathatod kreativitásodat.</p>
        <h2>Legyél felkészülve</h2>
        <p>Gondoskodj róla, hogy fényképezőgépeddel együtt mindig készen állj a fényképezésre, nappal és éjszaka egyaránt. A fényképezőgép típusától és modelljétől függetlenül mindig legyen teljesen feltöltve az akkumulátorod, és mindig legyen elég hely a memóriakártyán, hogy egy értékes pillanatról se maradj le.</p>
        <h2>Városi jelenetek megörökítése LEGRIA videokameráddal</h2>
        <p>Képzeld azt, hogy a videód a város reklámfilmje, vagy próbáld megörökíteni a város életének egy jellegzetes részletét. Ha világosan meghatározott célod és koncepciód van, nagyobb eséllyel tudsz az elképzeléseidnek megfelelő videót készíteni. Koncentrálj a divatra, az építészetre, a zenére vagy egy adott utcára, és készíts érdekes vizuális portrét a folyton változó városról.</p>
        <h2>Video-pillanatfelvételek</h2>
        <p>A video-pillanatfelvétel funkcióval olyan rövid videorészleteket rögzíthetsz, melyek valóban a város történetéről mesélnek. Ha az adott városrészben érdekes hangok vannak, érdemes hosszabb videorészletet rögzíteni, így az ebből nyert, folyamatos hangfelvétel több, külön felvett videoklipben is felhasználható. Az audió jelenetválasztó automatikusan beállítja a kamera hangrögzítési beállításait, hogy mindig kristálytisztán rögzíthesd a város környezetei hangjait.</p>
        <p>
            <strong>Tipp:</strong> Készíts felvételt a város mozgásáról. Az emberekről vagy a tömegközlekedésről készített felvételekkel remekül érzékeltethető a város dinamikája és folyamatos változása.
        </p>
        <SimpleFigure fileName="EOS_M50%20Lifestyle%20Mohamed%20Abdulle%2021_1200x800_tcm128-1374066.jpg" altText="Illusztráció"/>
        <h2>Figyelj a fényekre</h2>
        <p>A város mozgóképben történő megörökítésekor az egyik nagyon fontos tényező a fény. Azonban nem mindig lesz választási lehetőséged. A múzeumokba és az egyéb fedett helyekre gyakran csak kevés fény szűrődik be. Ezekben az esetekben próbáld meg elkerülni a sétálás közben készített felvételeket. Mindig stabil pozícióban készítsd el a videót, és a következő snitt felvételéig szüneteltesd a rögzítést.</p>
        <p>A szabadban a nappali fények a legalkalmasabbak a videózáshoz és a részletek megörökítéséhez, azonban a közvetlen napfény gyakran túl erős árnyékokat eredményez. Felhős időben gyakran sokkal jobb eredmények érhetők el.</p>
        <p>Az éjszakai felvételeknél egy kis kísérletezésre van szükség a kívánt eredmények eléréshez, mivel az elérhető fény nagyon korlátozott. Először próbálj meg alkonyatkor gyakorolni, keress jól kivilágított helyeket, és amikor csak lehetséges, használj állványt.</p>
        <h2>Mutasd be felvételeidet a legjobb formájukban</h2>
        <p>A városfotók kinyomtatva is remekül mutatnak, és otthon, a falra kitéve kiváló beszédtéma válhat belőlük. És ha már van egy képed, amire igazán büszke vagy, miért is ne büszkélkedhetnél vele – vagy miért ne küldenéd el a barátaidnak?</p>
        <p>A városfényképezésről hazatérve válogasd ki és nyomtasd ki a legjobb képeidet, és hozz létre lenyűgöző kollázsokat. Vagy nyomtasd ki a kedvenc képeidet, és kész is a saját útikalauzod a városról és a felfedezett dolgokról.</p>
        <SimpleFigure fileName="PCA%20-%20The%20Blue%20Hour_Tip-blue-hour-01_1200x800_tcm128-1374065.jpg" altText="Illusztráció"/>
    </>;
}

// frontend/src/materials/third-party-content/hu/canon-varosi-fotok-keszitese.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'canon-varosi-fotok-keszitese',
            title: 'Városi fotók készítése',
            author: 'Canon',
            publishDate: new Date('2019-06-17'),
            publisherName: 'Canon.hu',
            originalUrl: 'https://www.canon.hu/get-inspired/tips-and-techniques/city-photography/',
            isOriginalUrlBroken: false,
        };
    }
</script>

<script lang="ts">
    import SimpleFigure from '../../components/SimpleFigure.svelte';
    import ExternalLink from '../../components/ExternalLink.svelte';
</script>

<p>A városok természetüknél fogva zsúfolt és nyüzsgő helyek, de vannak olyan időszakok, különösen éjszaka és kora reggel, amikor lelassul a tempó. Ezekben a napszakokban azonban gyenge fényviszonyok mellett lehet csak fényképezni. Ehhez rövid záridőkre, magas ISO-értékekre és a fényképezőgép mozdulatlanul tartására van szükség.</p>
<p>Amikor rossz fényviszonyok között fényképezel, először is ki kell kapcsolnod az automatikus vakuhasználatot. Ezt a Vaku kikapcsolva és/vagy a Kézi éjszakai üzemmód használatával érheted el.</p>
<p>A kisméretű, például 10×15 cm-es vagy 13×18 cm-es képek ideális méretűek ahhoz, hogy azokat megoszd családoddal és barátaiddal. A <ExternalLink href="https://canon.hu/printers/pixma-photo-printers/">PIXMA</ExternalLink> nyomtatóval kinyomtatott képeket akár képeslapként is elküldheted. Az éles képek és élénk színek érdekében fényes papírt, például Photo Paper Plus Glossy vagy Photo Paper Pro papírt használj.
</p>
<p>
    <strong>Tipp:</strong> Vaku kikapcsolva üzemmód: fordítsd el a fényképezőgép üzemmódválasztó tárcsáját a Vaku kikapcsolva üzemmódra. Ennél az üzemmódnál a fényképezőgép más beállításokat fog használni a fényképek vaku nélkül történő elkészítéséhez. A gép magasabb fényérzékenység (ISO-értéket), alacsonyabb záridő és tágabb rekesz használatával biztosítja a megfelelő expozíciót.
</p>
<h2>A fényképezőgép bemozdulásából adódó elmosódás elkerülése</h2>
<p>Nagyon rossz fényviszonyok mellett és éjszaka ügyelned kell arra, hogy a fényképezőgép ne mozduljon be a kép elkészítése közben. A fényképezőgép bemozdulása életlenséget eredményezhet és tönkreteheti a képet. Rossz fényviszonyok mellett próbáld meg mindig a földre, stabil asztalra vagy korlátra helyezni a gépet. Már az is sokat segíthet, ha a fényképezőgépet erősen egy falhoz tartod a kép elkészítése közben. A képstabilizátorral ellátott objektívek szintén sokat segíthetnek ilyen helyzetekben.</p>
<p>
    <strong>Tipp:</strong> A Vaku kikapcsolva üzemmódot használd a múzeumokban és olyan helyeken is, ahol a vakuhasználat nem megengedett, vagy a vakuzás tönkretenné a hangulatot.
</p>
<h2>Kézi éjszakai üzemmód</h2>
<p>Ez a hasznos üzemmód négy képből álló gyors sorozatot készít, majd a képeket egyetlen képpé egyesíti, a minimális bemozduláshoz optimalizálva. Mivel sok városban korlátozzák az állványok használatát, a Kézi éjszakai üzemmóddal biztosíthatod, hogy éjszaka is mindig éles képeket készíthess.</p>
<h2>Használj gyors, nagy fényerejű fix objektívet</h2>
<p>Mindig jó, ha van nálad egy nagy fényerejű fix objektív, például egy <ExternalLink href="https://canon.hu/lenses/ef-50mm-f-1-8-stm-lens/">Canon EF 50mm f/1,8 STM</ExternalLink>, mellyel alacsony fényviszonyok mellett is kiváló felvételeket készíthetsz. A kisméretű, könnyű, diszkrét objektív éles és kiváló minőségű képeket garantál. A fix objektívek széles tartományban állítható rekeszbeállításaival fantasztikusan szabályozható a mélységélesség. Annak érdekében, hogy a legtöbbet hozhasd ki ezekből az objektívekből, használd a rekesz-előválasztás (Av) üzemmódot a mélységélesség szabályozásához, vagy a záridő-előválasztást (Tv) a mozgás megörökítéséhez. Az ilyen típusú objektívek másik előnye, hogy a zoomolás helyett folyamatosan mozognod kell a megfelelő fókusztávolság eléréséhez, így nagyobb eséllyel találsz több érdekes nézőpontot a fényképek elkészítéséhez. Városfényképezéshez vagy általános fényképezéshez a <ExternalLink href="https://canon.hu/lenses/ef-24mm-f-2-8-is-usm-lens/">Canon EF 24mm f/2.8 IS USM</ExternalLink> vagy <ExternalLink href="https://canon.hu/lenses/ef-35mm-f-2-is-usm-lens/">Canon EF 35mm f/2 IS USM</ExternalLink> objektívet javasoljuk.
</p>
<h2>Legyél mindig felkészülve a fényképezésre</h2>
<p>Gondoskodj arról, hogy a géped mindig készen álljon a fényképezésre. Ez azt jelenti, hogy a városban sétálva folyamatosan figyelj arra, hogy a fények hogyan változnak körülötted. Ha sötétebb lesz, számíts arra, hogy növelned kell az ISO-értéket, vagy nyitnod kell a rekeszen. Ha pedig több fény áll rendelkezésre, csökkentsd az ISO-értéket, vagy használj szűkebb rekeszt. Így a fényképezőgéped beállításai nagy valószínűséggel közel ideálisak lesznek, ha valamit hirtelen szeretnél lefényképezni.</p>
<p class="tip">
    <strong>Tipp:</strong> Ha a városban sok a magas épület, figyeld meg, hogy a fény hogyan érkezik az épületek között, és gondold át, hogy az elérhető fényt hogyan használhatod fel a legjobban a fényképeken. Az is megoldás lehet, ha olyan időpontban térsz vissza az adott helyre, amikor a fények megfelelnek az elképzeléseidnek.
</p>
<SimpleFigure fileName="G9%20X%20Mark%20II_CINC_Sample_IMG_0515_Monochrome_01_A2_1200x800_tcm128-1374063.jpg" altText="Illusztráció"/>
<h2>A monokróm mód és a szűrők használata</h2>
<p>A monokróm képstílus használatával közvetlenül a fényképezőgéppel készíthetsz fekete-fehér felvételeket. Mivel a fekete-fehér képek az árnyékról és a fényekről szólnak, a monokróm mód segítségével megfigyelheted a kontraszt játékát. Az LCD kijelzőn fekete-fehérben fognak megjelenni a képek, de ha RAW formátumban fotózol, a számítógépen végzett utómunka során visszaállíthatod a színes képet.</p>
<p>Erős napsütésnél a monokróm képstílus kontrasztbeállításának növelésével és sárga szűrő használatával gyakran még drámaibb kontraszt érhető el.</p>
<p>
    <em><strong>Tudta?</strong> Az árnyékok hosszabbak a nap vége felé közeledve, mint a nap közepén, és verőfényes napokon a legélesebbek, amikor egy felhő sincs az égen.</em>
</p>
<h2>
    <ExternalLink href="https://canon.hu/get-inspired/tips-and-techniques/how-to-do-time-lapse-photography/">A time-lapse hatások maximális kihasználása</ExternalLink>
</h2>
<p>A time-lapse hatással akkor is nagyszerűen megörökítheted a város nyüzsgését, ha csak rövid időre látogatsz el az adott helyre. Néhány EOS fényképezőgép beépített intervalométerrel van ellátva, melynek használatával a gép néhány másodpercenként felvételt készít.</p>
<p>Mindig használj stabil állványt a fényképezőgéphez. Megpróbálhatsz például egy magasan fekvő hotelszobából képeket készíteni egy nyüzsgő utcáról, mellyel napfelkeltétől napnyugtáig tartó érdekes felvételt kaphatsz a városról.</p>
<p>Annak érdekében, hogy elegendő képed legyen a time-lapse felvételhez, ne feledd, hogy minél rövidebb az intervallum, annál hosszabb ideig tart a time-lapse. Ha csak néhány órányi állóképet rögzítesz, használj rövidebb intervallumot, hiszen a videót a szerkesztés során utólag bármikor felgyorsíthatod.</p>
<h2>A fókusz módosítása</h2>
<p>A nagyvárosokban, ahol nagy a tömeg, néha nehéz a távoli témákra fókuszálni. A fényképezőgép gyakran az útjába kerülő közeli témákra fókuszál. Nagyon nagy tömegben elképzelhető, hogy sokkal jobban rá kell közelíteni a témára.</p>
<h2>A tökéletes kép a részletekben rejlik</h2>
<p>A városfényképezés gyakran az adott városra jellemző egyedi, apró részletek megörökítéséről szól. Például jó ötlet lehet ellátogatni a város piacaira és lefényképezni az árukat (és az azokat áruló embereket).</p>
<p>A megszokottól eltérő dolgok megörökítése mellett az adott város ikonikus áruiról, például sevillai narancsról, párizsi bagettről vagy berlini kolbászról is készíthetsz képeket.</p>
<p>
    <strong>Tipp:</strong> Kis témák esetén válaszd ki a makró vagy közelkép módot a fókusz gombbal (a virággal vagy MF szimbólummal jelölt gomb), és menj olyan közel a témához, hogy kitöltse a képet.
</p>
<p>Smart Auto üzemmódban a fényképezőgép automatikusan átvált makró módra. Egyszerűen tartsd mozdulatlanul a fényképezőgépet körülbelül egy másodpercig, amíg a kijelző jobb felső részén lévő ikon átvált a virág ikonra.</p>
<SimpleFigure fileName="EOS_5D_Mark_IV_CINC%20_sample-image20_1200x800_tcm128-1374064.jpg" altText="Illusztráció"/>
<h2>Fényképezd le ugyanazt a témát több napszakban is</h2>
<p>Ha időd engedi, készíts képeket különböző időpontokban ugyanarról a városrészről, és örökítsd meg a város ritmusát és változásait.</p>
<p>Ha elég időd van, ugyanazokat a helyeket különböző napszakokban is meglátogathatod, és megörökítheted a fények és a járókelők változását. Már három-négy, különböző időpontban készített fényképpel is jól érzékelhető a város változása.</p>
<h2>Mozgó témák fotózása</h2>
<p>Mozgó témák, például a hídon vagy a téren sétáló emberek, fényképezésekor a legjobb megoldás mozdulatlanul tartani a fényképezőgépet és kikapcsolni a vakut – ennek köszönhetően a fényképezőgép hosszabb zársebességet választ a téma mozgásának kiemeléséhez. Ilyen képek készítésekor mindig olyan felületeket és helyeket kell keresni, ahol a fényképezőgép teljesen stabilan elhelyezhető. Próbálj a záridő-előválasztással (Tv) kísérletezni, ha a gépeden van ilyen üzemmód. Ezzel beállíthatod a záridőt, és kibontakoztathatod kreativitásodat.</p>
<h2>Legyél felkészülve</h2>
<p>Gondoskodj róla, hogy fényképezőgépeddel együtt mindig készen állj a fényképezésre, nappal és éjszaka egyaránt. A fényképezőgép típusától és modelljétől függetlenül mindig legyen teljesen feltöltve az akkumulátorod, és mindig legyen elég hely a memóriakártyán, hogy egy értékes pillanatról se maradj le.</p>
<h2>Városi jelenetek megörökítése LEGRIA videokameráddal</h2>
<p>Képzeld azt, hogy a videód a város reklámfilmje, vagy próbáld megörökíteni a város életének egy jellegzetes részletét. Ha világosan meghatározott célod és koncepciód van, nagyobb eséllyel tudsz az elképzeléseidnek megfelelő videót készíteni. Koncentrálj a divatra, az építészetre, a zenére vagy egy adott utcára, és készíts érdekes vizuális portrét a folyton változó városról.</p>
<h2>Video-pillanatfelvételek</h2>
<p>A video-pillanatfelvétel funkcióval olyan rövid videorészleteket rögzíthetsz, melyek valóban a város történetéről mesélnek. Ha az adott városrészben érdekes hangok vannak, érdemes hosszabb videorészletet rögzíteni, így az ebből nyert, folyamatos hangfelvétel több, külön felvett videoklipben is felhasználható. Az audió jelenetválasztó automatikusan beállítja a kamera hangrögzítési beállításait, hogy mindig kristálytisztán rögzíthesd a város környezetei hangjait.</p>
<p>
    <strong>Tipp:</strong> Készíts felvételt a város mozgásáról. Az emberekről vagy a tömegközlekedésről készített felvételekkel remekül érzékeltethető a város dinamikája és folyamatos változása.
</p>
<SimpleFigure fileName="EOS_M50%20Lifestyle%20Mohamed%20Abdulle%2021_1200x800_tcm128-1374066.jpg" altText="Illusztráció"/>
<h2>Figyelj a fényekre</h2>
<p>A város mozgóképben történő megörökítésekor az egyik nagyon fontos tényező a fény. Azonban nem mindig lesz választási lehetőséged. A múzeumokba és az egyéb fedett helyekre gyakran csak kevés fény szűrődik be. Ezekben az esetekben próbáld meg elkerülni a sétálás közben készített felvételeket. Mindig stabil pozícióban készítsd el a videót, és a következő snitt felvételéig szüneteltesd a rögzítést.</p>
<p>A szabadban a nappali fények a legalkalmasabbak a videózáshoz és a részletek megörökítéséhez, azonban a közvetlen napfény gyakran túl erős árnyékokat eredményez. Felhős időben gyakran sokkal jobb eredmények érhetők el.</p>
<p>Az éjszakai felvételeknél egy kis kísérletezésre van szükség a kívánt eredmények eléréshez, mivel az elérhető fény nagyon korlátozott. Először próbálj meg alkonyatkor gyakorolni, keress jól kivilágított helyeket, és amikor csak lehetséges, használj állványt.</p>
<h2>Mutasd be felvételeidet a legjobb formájukban</h2>
<p>A városfotók kinyomtatva is remekül mutatnak, és otthon, a falra kitéve kiváló beszédtéma válhat belőlük. És ha már van egy képed, amire igazán büszke vagy, miért is ne büszkélkedhetnél vele – vagy miért ne küldenéd el a barátaidnak?</p>
<p>A városfényképezésről hazatérve válogasd ki és nyomtasd ki a legjobb képeidet, és hozz létre lenyűgöző kollázsokat. Vagy nyomtasd ki a kedvenc képeidet, és kész is a saját útikalauzod a városról és a felfedezett dolgokról.</p>
<SimpleFigure fileName="PCA%20-%20The%20Blue%20Hour_Tip-blue-hour-01_1200x800_tcm128-1374065.jpg" altText="Illusztráció"/>
