// frontend/src/materials/third-party-content/hu/elkapottpillanatok-fotozas-szuletesnapi-zsuron.tsx
import React from 'react';
import ExternalLink from '../../components/ExternalLink';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'elkapottpillanatok-fotozas-szuletesnapi-zsuron',
        title: 'Fotózás születésnapi zsúron',
        author: 'Tungler Andrea',
        publishDate: new Date('2014-01-01'),
        publisherName: 'Elkapott Pillanatok Fotóstúdió',
        originalUrl: 'http://www.elkapottpillanatok.hu/tippek/fotozas-szuletesnapi-zsuron',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <p>Sokszor fotóztam már gyerekek születésnapi ünnepségén, és mindegyik mókás élmény volt. Gyerekeket fényképezni nem könnyű, és a születésnapi összejövetelek fotózása további sajátos kihívások elé állítja a fotóst. A születésnapi bulikon rengeteg az érzelem, a kapcsolat, a szín és az energia – az élet pozitív oldalai mutatkoznak meg, néha egy-két rossz pillanattal. Ami igazi kihívást jelent, az a szinte elmaradhatatlan káosz. Mindegyik fotótéma folyamatosan mozog, hatalmas zűrzavar és igen kevés az idő egy beállítás összerendezésére és lefényképezésére.</p>
        <p>Hogy mindezt mégis hogyan oldom meg? Íme az én tippjeim és módszereim a születésnapi fotózáshoz:</p>

        <h2>1. Profi, külsős fotós</h2>
        <p>Nincs rosszabb, mint amikor egy családi összejövetel végén ráeszmélünk, hogy a fényképező végig a polcon pihent, mert senki sem ért rá fényképezni. Legyen egy külső fotós, akinek csak a fényképezés a feladata, <strong>nincs egyéb teendője</strong>. Így biztosan lesznek képek, és biztosan jó képek lesznek, melyekkel öröm lesz felidézni az eseményt. Így a család és a meghívottak együtt lehetnek, ráérnek élvezni a születésnapot, és biztosak lehetnek abban is, hogy az elkészült képek nem kerülnek illetéktelen kezekbe.
        </p>

        <h2>2. Perspektíva</h2>
        <p>A gyerekfotózás alapja, melyet ilyenkor sem szabad elfelejteni, hogy a képeket a <strong>gyerekek szemmagasságábó</strong>l kell készíteni. A legtöbb szülő ezt elfelejti, és állva, saját szemmagasságból, mintegy felülnézetből fotózza a gyerekeket. Én is elkattintok így néhány képet, de a fotók többségét a gyermekek közé térdelve, guggolva, vagy ülve készítem.
        </p>

        <h2>3. Változatos képek</h2>
        <p>Hogy mitől lesznek az én képeim izgalmasak és egyediek? Gyakran fotózok <strong>szokatlan helyekről</strong>, irányokból, változtatom a fényképezés látószögét. Felállok egy székre – ez kiváló megoldás nagy csoportképekhez, vagy lehasalok a padlóra – ez a gyermekarcok megörökítésére tökéletes. Nagy látószöggel megörökítem az egész termet, majd a kis részletekre fókuszálva egy-egy gyermek, egy-egy apróság is lencsevégre kerül. Ezeket a technikákat keverve alakul ki végül a teljes születésnapi fotóalbum.
        </p>

        <h2>4. Részletek</h2>
        <p>A hagyományos <ExternalLink href="http://www.elkapottpillanatok.hu/baba-mama-fotozas/szuletesnapi-fotozas">születésnapi fotózás</ExternalLink> általában csoportképekből áll. Természetesen én is elkészítem ezeket a képeket, de szeretek kicsit foglalkozni az <strong>apró részletekkel</strong> is, hiszen a kész albumot ezek teszik majd izgalmassá. Az ilyen jellegű fényképeket még a vendégek érkezése előtt szoktam elkészíteni: lufik, a <strong>dekoráció egyes részletei</strong>, a becsomagolt ajándékok, a szépen megterített asztal. Szeretem ezeket egészen közelről fotózni, valami apró dologgal kitölteni a teljes képet, ez gyakran egészen absztrakt kompozíciókat eredményez. Ezek a fotók a dobják fel igazán a kész albumot – némi változatosság a sok arckép között.
        </p>

        <h2>5. Programterv</h2>
        <p>Hogy ne maradjak le semmiről, előre tudnom kell, várhatóan mikor <strong>mi és hol történik</strong>. Mikor érkeznek a vendégek, mikor ülnek le enni, mikor és honnan érkezik a torta, jön-e bohóc, mikor kapja az ünnepelt az ajándékokat, hol fogja kibontani - ezek olyan részletek, melyeket nem lehet kihagyni a fotózásból. Az egyeztetés során mondjátok el alaposan a programtervet, így a jelentősebb pillanatokra előre fel tudok készülni, és időben elfoglalom a fotózáshoz szükséges legjobb helyet. A vendégek érkezése előtt szeretem megismerni a helyszínt, ilyenkor van lehetőség a további egyeztetésre is.
        </p>

        <h2>6. Háttérből, „lesből” fotózás</h2>
        <p>Sok képet készítek „lesből” – ilyenkor a fotózott személy talán nem is veszi észre, hogy kép készül róla. Ezeken a képeken a buli különböző résztvevői <strong>természetesen viselkednek</strong>, egymáshoz fűződő kapcsolatuk látható. Általában nyugodtan játszó, egymással beszélgető, éppen tortát majszoló gyerekeket örökítek meg, klasszikus „elkapott porték születnek”. Ilyenkor a terem szélére húzódok, a fényképezéshez teleobjektívet használok.
        </p>
        <p>A másik technikámat akkor alkalmazom, ha a buli már javában „pörög” – a terem széléről a tömeg közepére húzódok, és nagylátószögű objektívvel a közepéről fotózok. Ezek a képek mozgalmasabbak, izgalmasabbak lesznek. Ezeken a képeken az aktív, mozgásban, vagy valamilyen játékban elmerülő gyerekek lesznek láthatóak.</p>

        <h2>7. Kapcsolatépítés</h2>
        <p>A buli közepén ülve fotózni mókás dolog, de van, akikkel ez nem működik. Az igazán jó képekhez az is kell, hogy a gyermekek elfogadják a környezetet és vele együtt a fotóst is. Én ezért különösen figyelek a kapcsolatépítésre. Érkezéskor a vendéglátókkal együtt fogadom az érkező gyerekeket, igyekszem közvetlenül, de nem tolakodóan viselkedni. Ilyenkor a fényképezőgépemet is elteszem egy időre. Fotózáskor tiszteletben tartom a gyerekek saját személyes terét, egy-egy közeli kép készítésére a kísérő szülőktől is engedélyt kérek (sajnos olyan időket élünk, amikor a gyerekek fotózása sokakban rossz érzéseket kelt). Ha úgy tapasztalom, hogy valakit zavar a fotózás, akkor ezt <strong>tiszteletben tartom</strong>.
        </p>

        <h2>8. „Kötelező” képek</h2>
        <p>A háttérből ellőtt képek mellett kell előre meghatározott, „kötelező” kép is. Érdemes ezeket időben átgondolni –csak a szülők tudják, hogy melyek az elhagyhatatlan összeállítások. Kihagyhatatlanok bizonyos csoportképek (szülőkkel, legjobb baráttal, testvérekkel, közeli rokonokkal), legyen kép külön a tortáról, a gyertyafújásról, ajándéknyitásról, bizonyos játékról stb.</p>

        <h2>9. Előtte-utána képek</h2>
        <p>Bámulatos mennyit változik egy szoba képe egy-két óra alatt – különösen, ha egy sereg gyerek játszik ott. Szeretem megörökíteni a helyszínt a buli előtt és után is, akár a teljes termet, akár apró részleteket. Ezeket a képeket Ti is szeretni fogjátok. Maga az <strong>ünnepelt is drámai változáson megy át</strong> az ünneplés során: ezért készítek róla is képet a vendégek érkezése előtt. Lássuk mi lesz a szépen felöltözött, megfésült gyermekből a buli végére...
        </p>

        <h2>10. Sorozatfotózás</h2>
        <p>Ha a zsúr beindul, akkor a gépet gyakran állítom sorozatfotózásra – ilyen eseményeken ez a leghatékonyabb módszer. Ezt csinálom a pár másodpercig tartó <strong>gyertyafújásnál </strong>is, így biztosan lesz róla használható kép!
        </p>

        <h2>11. Felnőttek a képeken</h2>
        <p>A gyerekek születésnapján a lényeg a gyerekeken van – de azért néhányszor a felnőtteket is lefotózom. A kicsiket figyelő szülőkről, különösen az ünnepelt szüleiről igazán megható képeket lehet készíteni. A <strong>figyelő és boldog arcok</strong> kedves téma minden portréhoz.
        </p>
    </>;
}

// frontend/src/materials/third-party-content/hu/elkapottpillanatok-fotozas-szuletesnapi-zsuron.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'elkapottpillanatok-fotozas-szuletesnapi-zsuron',
            title: 'Fotózás születésnapi zsúron',
            author: 'Tungler Andrea',
            publishDate: new Date('2014-01-01'),
            publisherName: 'Elkapott Pillanatok Fotóstúdió',
            originalUrl: 'http://www.elkapottpillanatok.hu/tippek/fotozas-szuletesnapi-zsuron',
            isOriginalUrlBroken: false,
        }
    }
</script>

<script lang="ts">
    import ExternalLink from '../../components/ExternalLink.svelte'
</script>

<p>
    Sokszor fotóztam már gyerekek születésnapi ünnepségén, és mindegyik mókás élmény volt. Gyerekeket fényképezni nem
    könnyű, és a születésnapi összejövetelek fotózása további sajátos kihívások elé állítja a fotóst. A születésnapi
    bulikon rengeteg az érzelem, a kapcsolat, a szín és az energia – az élet pozitív oldalai mutatkoznak meg, néha
    egy-két rossz pillanattal. Ami igazi kihívást jelent, az a szinte elmaradhatatlan káosz. Mindegyik fotótéma
    folyamatosan mozog, hatalmas zűrzavar és igen kevés az idő egy beállítás összerendezésére és lefényképezésére.
</p>
<p>Hogy mindezt mégis hogyan oldom meg? Íme az én tippjeim és módszereim a születésnapi fotózáshoz:</p>

<h2>1. Profi, külsős fotós</h2>
<p>
    Nincs rosszabb, mint amikor egy családi összejövetel végén ráeszmélünk, hogy a fényképező végig a polcon pihent,
    mert senki sem ért rá fényképezni. Legyen egy külső fotós, akinek csak a fényképezés a feladata, <strong
        >nincs egyéb teendője</strong
    >. Így biztosan lesznek képek, és biztosan jó képek lesznek, melyekkel öröm lesz felidézni az eseményt. Így a család
    és a meghívottak együtt lehetnek, ráérnek élvezni a születésnapot, és biztosak lehetnek abban is, hogy az elkészült
    képek nem kerülnek illetéktelen kezekbe.
</p>

<h2>2. Perspektíva</h2>
<p>
    A gyerekfotózás alapja, melyet ilyenkor sem szabad elfelejteni, hogy a képeket a <strong
        >gyerekek szemmagasságábó</strong
    >l kell készíteni. A legtöbb szülő ezt elfelejti, és állva, saját szemmagasságból, mintegy felülnézetből fotózza a
    gyerekeket. Én is elkattintok így néhány képet, de a fotók többségét a gyermekek közé térdelve, guggolva, vagy ülve
    készítem.
</p>

<h2>3. Változatos képek</h2>
<p>
    Hogy mitől lesznek az én képeim izgalmasak és egyediek? Gyakran fotózok <strong>szokatlan helyekről</strong>,
    irányokból, változtatom a fényképezés látószögét. Felállok egy székre – ez kiváló megoldás nagy csoportképekhez,
    vagy lehasalok a padlóra – ez a gyermekarcok megörökítésére tökéletes. Nagy látószöggel megörökítem az egész termet,
    majd a kis részletekre fókuszálva egy-egy gyermek, egy-egy apróság is lencsevégre kerül. Ezeket a technikákat
    keverve alakul ki végül a teljes születésnapi fotóalbum.
</p>

<h2>4. Részletek</h2>
<p>
    A hagyományos <ExternalLink href="http://www.elkapottpillanatok.hu/baba-mama-fotozas/szuletesnapi-fotozas"
        >születésnapi fotózás</ExternalLink
    > általában csoportképekből áll. Természetesen én is elkészítem ezeket a képeket, de szeretek kicsit foglalkozni az
    <strong>apró részletekkel</strong>
    is, hiszen a kész albumot ezek teszik majd izgalmassá. Az ilyen jellegű fényképeket még a vendégek érkezése előtt szoktam
    elkészíteni: lufik, a <strong>dekoráció egyes részletei</strong>, a becsomagolt ajándékok, a szépen megterített
    asztal. Szeretem ezeket egészen közelről fotózni, valami apró dologgal kitölteni a teljes képet, ez gyakran egészen
    absztrakt kompozíciókat eredményez. Ezek a fotók a dobják fel igazán a kész albumot – némi változatosság a sok
    arckép között.
</p>

<h2>5. Programterv</h2>
<p>
    Hogy ne maradjak le semmiről, előre tudnom kell, várhatóan mikor <strong>mi és hol történik</strong>. Mikor érkeznek
    a vendégek, mikor ülnek le enni, mikor és honnan érkezik a torta, jön-e bohóc, mikor kapja az ünnepelt az
    ajándékokat, hol fogja kibontani - ezek olyan részletek, melyeket nem lehet kihagyni a fotózásból. Az egyeztetés
    során mondjátok el alaposan a programtervet, így a jelentősebb pillanatokra előre fel tudok készülni, és időben
    elfoglalom a fotózáshoz szükséges legjobb helyet. A vendégek érkezése előtt szeretem megismerni a helyszínt,
    ilyenkor van lehetőség a további egyeztetésre is.
</p>

<h2>6. Háttérből, „lesből” fotózás</h2>
<p>
    Sok képet készítek „lesből” – ilyenkor a fotózott személy talán nem is veszi észre, hogy kép készül róla. Ezeken a
    képeken a buli különböző résztvevői <strong>természetesen viselkednek</strong>, egymáshoz fűződő kapcsolatuk
    látható. Általában nyugodtan játszó, egymással beszélgető, éppen tortát majszoló gyerekeket örökítek meg, klasszikus
    „elkapott porték születnek”. Ilyenkor a terem szélére húzódok, a fényképezéshez teleobjektívet használok.
</p>
<p>
    A másik technikámat akkor alkalmazom, ha a buli már javában „pörög” – a terem széléről a tömeg közepére húzódok, és
    nagylátószögű objektívvel a közepéről fotózok. Ezek a képek mozgalmasabbak, izgalmasabbak lesznek. Ezeken a képeken
    az aktív, mozgásban, vagy valamilyen játékban elmerülő gyerekek lesznek láthatóak.
</p>

<h2>7. Kapcsolatépítés</h2>
<p>
    A buli közepén ülve fotózni mókás dolog, de van, akikkel ez nem működik. Az igazán jó képekhez az is kell, hogy a
    gyermekek elfogadják a környezetet és vele együtt a fotóst is. Én ezért különösen figyelek a kapcsolatépítésre.
    Érkezéskor a vendéglátókkal együtt fogadom az érkező gyerekeket, igyekszem közvetlenül, de nem tolakodóan
    viselkedni. Ilyenkor a fényképezőgépemet is elteszem egy időre. Fotózáskor tiszteletben tartom a gyerekek saját
    személyes terét, egy-egy közeli kép készítésére a kísérő szülőktől is engedélyt kérek (sajnos olyan időket élünk,
    amikor a gyerekek fotózása sokakban rossz érzéseket kelt). Ha úgy tapasztalom, hogy valakit zavar a fotózás, akkor
    ezt <strong>tiszteletben tartom</strong>.
</p>

<h2>8. „Kötelező” képek</h2>
<p>
    A háttérből ellőtt képek mellett kell előre meghatározott, „kötelező” kép is. Érdemes ezeket időben átgondolni –csak
    a szülők tudják, hogy melyek az elhagyhatatlan összeállítások. Kihagyhatatlanok bizonyos csoportképek (szülőkkel,
    legjobb baráttal, testvérekkel, közeli rokonokkal), legyen kép külön a tortáról, a gyertyafújásról,
    ajándéknyitásról, bizonyos játékról stb.
</p>

<h2>9. Előtte-utána képek</h2>
<p>
    Bámulatos mennyit változik egy szoba képe egy-két óra alatt – különösen, ha egy sereg gyerek játszik ott. Szeretem
    megörökíteni a helyszínt a buli előtt és után is, akár a teljes termet, akár apró részleteket. Ezeket a képeket Ti
    is szeretni fogjátok. Maga az <strong>ünnepelt is drámai változáson megy át</strong> az ünneplés során: ezért készítek
    róla is képet a vendégek érkezése előtt. Lássuk mi lesz a szépen felöltözött, megfésült gyermekből a buli végére...
</p>

<h2>10. Sorozatfotózás</h2>
<p>
    Ha a zsúr beindul, akkor a gépet gyakran állítom sorozatfotózásra – ilyen eseményeken ez a leghatékonyabb módszer.
    Ezt csinálom a pár másodpercig tartó <strong>gyertyafújásnál </strong>is, így biztosan lesz róla használható kép!
</p>

<h2>11. Felnőttek a képeken</h2>
<p>
    A gyerekek születésnapján a lényeg a gyerekeken van – de azért néhányszor a felnőtteket is lefotózom. A kicsiket
    figyelő szülőkről, különösen az ünnepelt szüleiről igazán megható képeket lehet készíteni. A <strong
        >figyelő és boldog arcok</strong
    > kedves téma minden portréhoz.
</p>
