// frontend/src/materials/third-party-content/hu/fotozasblog-iso-erzekenyseg-fenymeres-beepitett-vaku.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'fotozasblog-iso-erzekenyseg-fenymeres-beepitett-vaku',
            title: 'Fotózás alapok',
            author: 'Illés Dániel',
            publishDate: new Date('2014-02-09'),
            publisherName: 'fotozasblog.hu',
            originalUrl: 'http://fotozasblog.hu/fotozas-alapjai-iso-fenymeres/',
            isOriginalUrlBroken: true,
        }
    }
</script>

<script lang="ts">
    import FullWidthLocalImage from '../../../challenges/components/FullWidthLocalImage.svelte'
</script>

<FullWidthLocalImage fileName="fotozasblog-iso-erzekenyseg-fenymeres-beepitett-vaku.png" altText="" />

// frontend/src/materials/third-party-content/hu/fotozasblog-iso-erzekenyseg-fenymeres-beepitett-vaku.tsx
import React from 'react';
import FullWidthLocalImage from '../../../challenges/components/FullWidthLocalImage';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'fotozasblog-iso-erzekenyseg-fenymeres-beepitett-vaku',
        title: 'Fotózás alapok',
        author: 'Illés Dániel',
        publishDate: new Date('2014-02-09'),
        publisherName: 'fotozasblog.hu',
        originalUrl: 'http://fotozasblog.hu/fotozas-alapjai-iso-fenymeres/',
        isOriginalUrlBroken: true,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <FullWidthLocalImage fileName="fotozasblog-iso-erzekenyseg-fenymeres-beepitett-vaku.png" altText="" />
    </>;
}
