// frontend/src/materials/third-party-content/hu/fotosarok-101-portrefoto-tipp.jsx
import React from 'react';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'fotosarok-101-portrefoto-tipp',
        title: '101 Portréfotó tipp',
        author: 'Korecz Márk',
        publishDate: new Date('2012-06-03'),
        publisherName: 'FotóSarok Blog',
        originalUrl: 'http://blog.fotosarok.hu/tag/101-portrefoto-tipp/page/2/',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
    </>;
}

// frontend/src/materials/third-party-content/hu/fotosarok-101-portrefoto-tipp.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'fotosarok-101-portrefoto-tipp',
            title: '101 Portréfotó tipp',
            author: 'Korecz Márk',
            publishDate: new Date('2012-06-03'),
            publisherName: 'FotóSarok Blog',
            originalUrl: 'http://blog.fotosarok.hu/tag/101-portrefoto-tipp/page/2/',
            isOriginalUrlBroken: false,
        }
    }
</script>
