// frontend/src/materials/third-party-content/hu/fotosuli-unja-a-telet-keszuljon-fel-a-tavaszra-1.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'fotosuli-unja-a-telet-keszuljon-fel-a-tavaszra-1',
            title: 'Unja a telet? Készüljön fel a tavaszra! - I. rész',
            author: 'Feggaris',
            publishDate: new Date('2017-01-25'),
            publisherName: 'Fotósuli',
            originalUrl: 'https://fotosuli.blog.hu/2017/01/25/unja_a_telet_keszuljon_fel_a_tavaszra_i_resz',
            isOriginalUrlBroken: false,
        };
    }
</script>

<script lang="ts">
    import SimpleFigure from '../../components/SimpleFigure.svelte';
</script>

<p>Beszéljünk most egy kicsit a növények, ezen belül is a virágok fényképezéséről. Noha mozdulatlanok, tehát gondolhatjuk, hogy egyszerű őket lefotózni, mégsem annyira, mint gondolnánk. Legalább is abból a szempontból egyáltalán nem mindegy a technika, hogy milyen minőségű, élességű fotót kívánunk a magunkénak tudni.</p>
<SimpleFigure fileName="68205580_l.jpg" altText="Illusztráció"/>
<p>Jöjjön tehát néhány jó tanács, ebben a témában, reméljük, mindenkinek a hasznára válik, azzal együtt, hogy sokaknak személyes tapasztalatukból néhány elv már ismert.</p>
<p>Talán az egyik legfontosabb, hogy a tájképekkel ellentétben a virágokat a legjobb nem kifejezett verőfényben fényképezni, sokkal alkalmasabb a növény fotózására a borús idő. Ha felhős időben fotózunk, akkor azzal elérhetjük, hogy a virágoknak többszörösen erőteljesebb színük legyen.</p>
<p>Fokozhatjuk a makulátlan és igazán különleges hatást, ha közvetlenül eső után fényképezünk, mert így a virágon maradt vízcseppek csodaszépen megjelennek majd a képeken. Olyat is hallottunk már – és remek ötletnek tartjuk – hogy eső hiányában valaki folyadékszóró flakonból fújt a növényekre, ezzel produkálva vízcseppeket azokra. Tehát, nem kell feltétlenül kivárni az esős időt ahhoz, hogy tökéletes fotót készítsünk. Egyébként a kora reggeli pára is tökéletesen megfelel az elvárásoknak, hiszen a harmat is vízcsepp, így érdemes kicsit hamarabb kelni a fotózás napján!</p>
<p>Szeles időben nem éppen szerencsés a fotózás, gondolom, mindenki tudja, hogy miért. Elvész a pillanat, hiszen egy másodperc alatt is más lesz a virág „beállítása” ha fúj a szél, ajánlott tehát csendes időben fényképezni a szabadtéri helyszínen.</p>
<p>A másik fontos szabály, ha igazán szép csendéletet szeretnél egy-egy kiszemelt növényről, hogy mindig picit alulról, illetve oldalról kattints! Ez néha azzal jár, ha földközeli virágokat fényképezel, hogy le kell ereszkedned a talajszintre, magyarul hajolni, vagy guggolni kell. Egy fotósnál persze ez egyáltalán nem probléma, mindent a tökéletes képekért! Ezzel a módszerrel azt érjük el, hogy maga a virág fogja betölteni a kép mezejét teljesen, ami valójában itt a cél!</p>
<p>Folytatjuk…</p>

// frontend/src/materials/third-party-content/hu/fotosuli-unja-a-telet-keszuljon-fel-a-tavaszra-1.tsx
import React from 'react';
import SimpleFigure from '../../components/SimpleFigure';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'fotosuli-unja-a-telet-keszuljon-fel-a-tavaszra-1',
        title: 'Unja a telet? Készüljön fel a tavaszra! - I. rész',
        author: 'Feggaris',
        publishDate: new Date('2017-01-25'),
        publisherName: 'Fotósuli',
        originalUrl: 'https://fotosuli.blog.hu/2017/01/25/unja_a_telet_keszuljon_fel_a_tavaszra_i_resz',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <p>Beszéljünk most egy kicsit a növények, ezen belül is a virágok fényképezéséről. Noha mozdulatlanok, tehát gondolhatjuk, hogy egyszerű őket lefotózni, mégsem annyira, mint gondolnánk. Legalább is abból a szempontból egyáltalán nem mindegy a technika, hogy milyen minőségű, élességű fotót kívánunk a magunkénak tudni.</p>
        <SimpleFigure fileName="68205580_l.jpg" altText="Illusztráció"/>
        <p>Jöjjön tehát néhány jó tanács, ebben a témában, reméljük, mindenkinek a hasznára válik, azzal együtt, hogy sokaknak személyes tapasztalatukból néhány elv már ismert.</p>
        <p>Talán az egyik legfontosabb, hogy a tájképekkel ellentétben a virágokat a legjobb nem kifejezett verőfényben fényképezni, sokkal alkalmasabb a növény fotózására a borús idő. Ha felhős időben fotózunk, akkor azzal elérhetjük, hogy a virágoknak többszörösen erőteljesebb színük legyen.</p>
        <p>Fokozhatjuk a makulátlan és igazán különleges hatást, ha közvetlenül eső után fényképezünk, mert így a virágon maradt vízcseppek csodaszépen megjelennek majd a képeken. Olyat is hallottunk már – és remek ötletnek tartjuk – hogy eső hiányában valaki folyadékszóró flakonból fújt a növényekre, ezzel produkálva vízcseppeket azokra. Tehát, nem kell feltétlenül kivárni az esős időt ahhoz, hogy tökéletes fotót készítsünk. Egyébként a kora reggeli pára is tökéletesen megfelel az elvárásoknak, hiszen a harmat is vízcsepp, így érdemes kicsit hamarabb kelni a fotózás napján!</p>
        <p>Szeles időben nem éppen szerencsés a fotózás, gondolom, mindenki tudja, hogy miért. Elvész a pillanat, hiszen egy másodperc alatt is más lesz a virág „beállítása” ha fúj a szél, ajánlott tehát csendes időben fényképezni a szabadtéri helyszínen.</p>
        <p>A másik fontos szabály, ha igazán szép csendéletet szeretnél egy-egy kiszemelt növényről, hogy mindig picit alulról, illetve oldalról kattints! Ez néha azzal jár, ha földközeli virágokat fényképezel, hogy le kell ereszkedned a talajszintre, magyarul hajolni, vagy guggolni kell. Egy fotósnál persze ez egyáltalán nem probléma, mindent a tökéletes képekért! Ezzel a módszerrel azt érjük el, hogy maga a virág fogja betölteni a kép mezejét teljesen, ami valójában itt a cél!</p>
        <p>Folytatjuk…</p>
    </>;
}
