// frontend/src/materials/third-party-content/hu/haziallat-allatok-fotozasa-trukkok.jsx
import React from 'react';
import SimpleFigure from '../../components/SimpleFigure.jsx';
import ExternalLink from '../../components/ExternalLink.jsx';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'haziallat-allatok-fotozasa-trukkok',
        title: '9 egyszerű trükk házikedvencek fotózásához',
        author: 'Duncsák Ágnes',
        publishDate: new Date('2010-03-09'),
        publisherName: 'háziállat.hu',
        originalUrl: 'https://www.haziallat.hu/allati-trendi/technika/allatok-fotozasa-trukkok/1897/',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <p>Kedvencünk - legyen az kutya, macska, degu, papagáj vagy bármi egyéb háziállat - hamar belopja magukat a szívünkbe, és fel sem tűnik, hogy már több száz fotót készítettünk róla. De vajon hogyan készíthetünk tökéletes képeket? Olvasd el és alkalmazd tippjeinket, és neked is szuper fotóid lesznek háziállatodról!</p>
        <h2>Hogyan fotózzuk kedvenceinket?</h2>
        <p>A <ExternalLink href="http://www.haziallat.hu/kutya/kutyafajtak/">kutyák</ExternalLink>, <ExternalLink href="http://www.haziallat.hu/macska/macskafajtak/">macskák</ExternalLink> és egyéb házikedvencek fotózása nem mindig könnyű feladat: ők nem értik, mi történik ilyenkor és nem várhatjuk, hogy pózoljanak kameránk előtt! Szerencsére léteznek egyszerű praktikák, melyeket bárki alkalmazhat. Összegyűjtöttük a 9 legegyszerűbb trükköt:
        </p>

        <h2>1. Használj természetes fényt!</h2>
        <p>Amikor csak lehet, természetes fénynél fotózz! A vaku használata nem tanácsos: nem csak a vörös szem-effektus miatt, hanem azért sem, mert megijesztheti az állatot.<strong> </strong>A szabadban késő délután a legszebbek a fények, a déli tűző napsütés nem ideális a fotózáshoz.
        </p>

        <h2>2. A szemek élesen látszódjanak!</h2>
        <p>A szem a lélek tükre - tartja a mondás. Minden portré fontos eleme, hogy a fotózott alany szeme élesen látszódjon. Az állatok szeme nagyon kifejező tud lenni, ezért <strong>fókuszálj kedvenced szemére és állítsd be megfelelően az élességet</strong> (automata beállítások esetén: ha az exponáló gombot félig lenyomod, a gép automatikusan beállítja az élességet, s csak ezután kell exponálni).
        </p>
        <SimpleFigure fileName="1_original.jpg" altText="Kutya szeme" caption="A szem a lélek tükre"/>

        <h2>3. Menj oda hozzá!</h2>
        <p>Fontos, hogy háziállatod kényelmesen érezze magát, és természetesen viselkedjen, ezért ne kényszerítsd, hogy a fotó kedvéért odajöjjön hozzád, inkább te közelíts felé!<strong> </strong>Ereszkedj le hozzá: guggolva, ülve, sőt akár fekve fotózz. Sokkal jobb képelet kapsz így, mint ha fölé magasodva állnál, s felülről fényképeznéd.
        </p>
        <SimpleFigure fileName="2_original.jpg" altText="Német dog alulról fotózva" caption="Ne felülről fotózd!"/>

        <h2>4. Használd ki, hogy te ismered őt a legjobban!</h2>
        <p>Nálad jobban senki sem ismeri kedvencedet. A jól sikerült képeken mindig "átjön" a fotóalany személyisége. Ha lusta cicád van, fotózd őt ásítás közben, ha örökmozgó kutyád van, akkor futkározás közben kapd őt lencsevégre, stb.</p>
        <SimpleFigure fileName="3_original.jpg" altText="Vizslaorr" caption="Nem kell, hogy az egész kutya szerepeljen a képen"/>

        <h2>5. Fotózz makró témákat</h2>
        <p>Fotózd kedvencedet egészen közelről: akár úgy, hogy arcának csak egy részlete látszódjon a képen. Ehhez - többek között - makróobjektívre és szélcsendre lesz szükséged.</p>

        <h2>6. Lepd meg kedvencedet!</h2>
        <p>Az egyik legnehezebb dolog az állatok fotózásában: rávenni őket, hogy nyugton maradjanak.Íme, a trükk: hagyd, hogy játsszon, vagy csinálja azt, amivel épp amúgy is el van foglalva, és ha minden készen áll a fotózáshoz, kérj meg valakit, hogy fütyüljön neki, vagy hívja magához. Ez kizökkenti az állatot, felkapja a fejét, így lesz alkalmad lefotózni egy olyan pillanatban, amikor épp megáll, s feszülten figyel valamire.</p>
        <SimpleFigure fileName="4_original.jpg" altText="Németjuhász vacsorát kap" caption="Egy-egy jó időzítés mókás képeket eredményezhet"/>

        <h2>7. Fontos a jó időzítés</h2>
        <p>Hagyományos portrét álmos állatkáról a legkönnyebb készíteni. Ezért lefekvés előtt, vagy ébredés után fényképezd! Ha dinamikus mozgássorozatot ábrázoló képekre vágysz, akkor futás vagy játék közben kapd őt lencsevégre. Ha kedvenced beteg, akkor ne gyötörd, inkább halaszd későbbre a fotózást.</p>

        <h2>8. Csak nyugisan!</h2>
        <p>Az állatok fotózása sok türelmet igényel. Bármilyen izgatott is háziállatod, ha látja, hogy te türelmes vagy, előbb-utóbb ő is lenyugszik, és alkalmad lesz normális képeket készíteni.</p>
        <SimpleFigure fileName="5_original.jpg" altText="Illusztráció" caption="Ha a cica feszülten figyel valamire, (nem feltétlenül ránk), akkor remek képet készíthetünk"/>

        <h2>9. Kísérletezz!</h2>
        <p>Próbálgasd ugyanazt a témát különböző beállításokból fotózni, minden alkalommal másképpen komponáld meg a képet. Fotózd le ugyanazt színesben, fekete-fehérben, sőt szépia (barnás) színbeállítással is. Ha digitális géped van, akkor bátran fotózz egyszerre rengeteget, később majd átnézheted, és a nem jól sikerült képeket kitörölheted.</p>
    </>;
}

// frontend/src/materials/third-party-content/hu/haziallat-allatok-fotozasa-trukkok.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'haziallat-allatok-fotozasa-trukkok',
            title: '9 egyszerű trükk házikedvencek fotózásához',
            author: 'Duncsák Ágnes',
            publishDate: new Date('2010-03-09'),
            publisherName: 'háziállat.hu',
            originalUrl: 'https://www.haziallat.hu/allati-trendi/technika/allatok-fotozasa-trukkok/1897/',
            isOriginalUrlBroken: false,
        }
    }
</script>

<script lang="ts">
    import SimpleFigure from '../../components/SimpleFigure.svelte'
    import ExternalLink from '../../components/ExternalLink.svelte'
</script>

<p>
    Kedvencünk - legyen az kutya, macska, degu, papagáj vagy bármi egyéb háziállat - hamar belopja magukat a szívünkbe,
    és fel sem tűnik, hogy már több száz fotót készítettünk róla. De vajon hogyan készíthetünk tökéletes képeket? Olvasd
    el és alkalmazd tippjeinket, és neked is szuper fotóid lesznek háziállatodról!
</p>
<h2>Hogyan fotózzuk kedvenceinket?</h2>
<p>
    A <ExternalLink href="http://www.haziallat.hu/kutya/kutyafajtak/">kutyák</ExternalLink>, <ExternalLink
        href="http://www.haziallat.hu/macska/macskafajtak/">macskák</ExternalLink
    > és egyéb házikedvencek fotózása nem mindig könnyű feladat: ők nem értik, mi történik ilyenkor és nem várhatjuk, hogy
    pózoljanak kameránk előtt! Szerencsére léteznek egyszerű praktikák, melyeket bárki alkalmazhat. Összegyűjtöttük a 9 legegyszerűbb
    trükköt:
</p>

<h2>1. Használj természetes fényt!</h2>
<p>
    Amikor csak lehet, természetes fénynél fotózz! A vaku használata nem tanácsos: nem csak a vörös szem-effektus miatt,
    hanem azért sem, mert megijesztheti az állatot.<strong> </strong>A szabadban késő délután a legszebbek a fények, a
    déli tűző napsütés nem ideális a fotózáshoz.
</p>

<h2>2. A szemek élesen látszódjanak!</h2>
<p>
    A szem a lélek tükre - tartja a mondás. Minden portré fontos eleme, hogy a fotózott alany szeme élesen látszódjon.
    Az állatok szeme nagyon kifejező tud lenni, ezért <strong
        >fókuszálj kedvenced szemére és állítsd be megfelelően az élességet</strong
    > (automata beállítások esetén: ha az exponáló gombot félig lenyomod, a gép automatikusan beállítja az élességet, s csak
    ezután kell exponálni).
</p>
<SimpleFigure fileName="1_original.jpg" altText="Kutya szeme" caption="A szem a lélek tükre" />

<h2>3. Menj oda hozzá!</h2>
<p>
    Fontos, hogy háziállatod kényelmesen érezze magát, és természetesen viselkedjen, ezért ne kényszerítsd, hogy a fotó
    kedvéért odajöjjön hozzád, inkább te közelíts felé!<strong> </strong>Ereszkedj le hozzá: guggolva, ülve, sőt akár
    fekve fotózz. Sokkal jobb képelet kapsz így, mint ha fölé magasodva állnál, s felülről fényképeznéd.
</p>
<SimpleFigure fileName="2_original.jpg" altText="Német dog alulról fotózva" caption="Ne felülről fotózd!" />

<h2>4. Használd ki, hogy te ismered őt a legjobban!</h2>
<p>
    Nálad jobban senki sem ismeri kedvencedet. A jól sikerült képeken mindig "átjön" a fotóalany személyisége. Ha lusta
    cicád van, fotózd őt ásítás közben, ha örökmozgó kutyád van, akkor futkározás közben kapd őt lencsevégre, stb.
</p>
<SimpleFigure
    fileName="3_original.jpg"
    altText="Vizslaorr"
    caption="Nem kell, hogy az egész kutya szerepeljen a képen"
/>

<h2>5. Fotózz makró témákat</h2>
<p>
    Fotózd kedvencedet egészen közelről: akár úgy, hogy arcának csak egy részlete látszódjon a képen. Ehhez - többek
    között - makróobjektívre és szélcsendre lesz szükséged.
</p>

<h2>6. Lepd meg kedvencedet!</h2>
<p>
    Az egyik legnehezebb dolog az állatok fotózásában: rávenni őket, hogy nyugton maradjanak.Íme, a trükk: hagyd, hogy
    játsszon, vagy csinálja azt, amivel épp amúgy is el van foglalva, és ha minden készen áll a fotózáshoz, kérj meg
    valakit, hogy fütyüljön neki, vagy hívja magához. Ez kizökkenti az állatot, felkapja a fejét, így lesz alkalmad
    lefotózni egy olyan pillanatban, amikor épp megáll, s feszülten figyel valamire.
</p>
<SimpleFigure
    fileName="4_original.jpg"
    altText="Németjuhász vacsorát kap"
    caption="Egy-egy jó időzítés mókás képeket eredményezhet"
/>

<h2>7. Fontos a jó időzítés</h2>
<p>
    Hagyományos portrét álmos állatkáról a legkönnyebb készíteni. Ezért lefekvés előtt, vagy ébredés után fényképezd! Ha
    dinamikus mozgássorozatot ábrázoló képekre vágysz, akkor futás vagy játék közben kapd őt lencsevégre. Ha kedvenced
    beteg, akkor ne gyötörd, inkább halaszd későbbre a fotózást.
</p>

<h2>8. Csak nyugisan!</h2>
<p>
    Az állatok fotózása sok türelmet igényel. Bármilyen izgatott is háziállatod, ha látja, hogy te türelmes vagy,
    előbb-utóbb ő is lenyugszik, és alkalmad lesz normális képeket készíteni.
</p>
<SimpleFigure
    fileName="5_original.jpg"
    altText="Illusztráció"
    caption="Ha a cica feszülten figyel valamire, (nem feltétlenül ránk), akkor remek képet készíthetünk"
/>

<h2>9. Kísérletezz!</h2>
<p>
    Próbálgasd ugyanazt a témát különböző beállításokból fotózni, minden alkalommal másképpen komponáld meg a képet.
    Fotózd le ugyanazt színesben, fekete-fehérben, sőt szépia (barnás) színbeállítással is. Ha digitális géped van,
    akkor bátran fotózz egyszerre rengeteget, később majd átnézheted, és a nem jól sikerült képeket kitörölheted.
</p>
