// frontend/src/materials/third-party-content/hu/hvg-tippek-a-karacsonyi-fotozashoz.tsx
import React from 'react';
import SimpleFigure from '../../components/SimpleFigure';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'hvg-tippek-a-karacsonyi-fotozashoz',
        title: 'Tippek a karácsonyi fotózáshoz',
        author: 'techline.hu',
        publishDate: new Date('2007-12-25'),
        publisherName: 'HVG',
        originalUrl: 'https://hvg.hu/tudomany/20071221_karacsonyifoto',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <h2>1. Készüljünk fel a nagy pillanatokra!</h2>
        <p>Bizonyára sokakkal előfordult már a fotózás során, hogy lemaradt a legjobb pillanatokról, mert elfelejtette feltölteni az akkumulátort, vagy letörölni a betelt memóriakártyát. Ezért a karácsonyi események előtt célszerű ellenőrizni néhány apróságot – megéri.</p>
        <p>Keressük meg a digitális gépünket. :) Töltsük fel az akkumulátorokat, s lehetőleg gondoskodjunk tartalékról is.</p>
        <p>Ellenőrizzük a memóriakártyát. Ha tele van, mentsük le a tartalmát. Legyen megfelelő a kártya kapacitása. A gépekhez adott memóriakártya <em>16 vagy 32 megabájtja</em> nem sok képre elegendő. Még időben szerezzünk be egy <em>minimum 512 MB-os </em>kártyát. S az sem árt, ha egy kicsit gyorsabb tud lenni, hiszen egy sorozatfelvételnél a kártyára való írás is lassíthatja a felvételt.
        </p>
        <p>Ha lehetőségünk van rá, tartsunk terepszemlét a családi fotózás helyszínén, lehetőleg még nyugodt körülmények között. Képzeljük el milyen lesz a leendő háttér, mérjük fel, hogy vannak-e zavaró részletek, amelyeket érdemes elkerülni. Ellenőrizzük a megvilágítást, s gondoljuk át, vajon elegendő fény lesz-e számunkra, kell-e majd vakut használni. Az sem mindegy, hogy izzólámpával, esetleg neonnal lesz-e dolgunk. Határozzuk meg, honnan lesznek a legjobbak a képeink, s érdemes olykor elpakolni néhány belógó kacatot, amelyeket később csak kitartó retusálással lehet eltüntetni. Készítsünk néhány próbafelvételt, hogy még időben észrevehessük a lehetséges hibákat.</p>
        <SimpleFigure fileName="image (1).jpg" altText="Karácsonyi fotózás 1" caption="Egy betelt memóriakártya kellemetlen meglepetést okozhat"/>

        <h2>2. Készítsünk fotósarkot!</h2>
        <p>A karácsonykor általában sok portréfotót készítünk, de még családunkban is akadnak olyanok, akik nem szeretik, ha fotózzák őket (de legalábbis kellő hangulatban kell lenniük ehhez.) Éppen ezért lehet jó ötlet, ha kijelölünk egy fotósarkot karácsonykor, ahol mindig ideális körülményeket biztosítunk, például egy karosszéket a karácsonyfa mellett, sok zavaró, figyelmet elterelő részlet nélkül. Ha a fényképezőgépet állványra helyezzük, és bekapcsoljuk az időzítőjét (ez az a kis gomb, amelyet aktiválva 15-20 másodperc múlva exponál csak a gépünk), akkor ott sem kell lennünk a fotó elkészülésekor. A modelljeink saját maguk kezelhetik a gépet, kényelmesen elhelyezkedhetnek, nem zavarja őket semmi. Figyeljük meg, hogy modelljeink a karácsony folyamán többször is be fognak ülni rögtönzött fotósarkunkba egy-két újabb fotó erejéig.</p>

        <h2>3. Az előkészület pillanatai</h2>
        <p>Természetesen a karácsonyi ajándékozás, az ünnepi vacsora pillanatai a legemlékezetesebbek, de sokszor az előkészületek alatt már nagyon jó képeket készíthetünk. A finomságok készítése, az asztal megterítése, a dekorációk felrakása, az ajándékok csomagolása közben mindig találunk egy-egy pillanatot, amely fotóalbumunk büszkeségére válhat.</p>
        <SimpleFigure fileName="image (3).jpg" altText="Karácsonyi fotózás 2" caption="Készül a mézeskalács karácsonyra"/>

        <h2>4. Buli előtt és után</h2>
        <p>Sokszor készítünk olyan felvételeket, amelyeknél megjegyezzük: az lett volna az igazi, ha meg tudjuk mutatni, milyen volt korábban az adott téma. Jó példa erre a gyerekek szépen elrendezett ajándéka a fa alatt, majd az eufórikus bontogatás folyamata, s végül a papírfoszlányok mindenfelé. Készüljünk rá! Jó megoldás, ha még a karácsonyi parti előtt készítünk pár jellegzetes felvételt, lehetőleg olyan helyzetből, amelyből a későbbiekben is fotózni fogunk.</p>
        <SimpleFigure fileName="image.jpg" altText="Karácsonyi fotózás 3" caption="Az egyik karácsonyi csomag akció előtt"/>

        <h2>5. Karácsonyi gyorsított felvétel</h2>
        <p>Látványos felvételsorozatot készíthetünk a karácsonyi eseményekről webkameránk segítségével . Irányítsuk a kamerát a karácsonyfára, s állítsuk be, hogy 5 percenként készítsen egy felvételt. A nap végén a legnagyobb élmény lesz visszanézni ezeket a gyorsított felvételszerű képeket. Sajnos ehhez a számítógépet is az események közelébe kell vonszolni, de szerencsére már van néhány olyan videokamera, amely képes fotókat készíteni és az időzítést is megoldani. Természetesen ne felejtsük el állványra helyezni a kamerát.</p>

        <h2>6. A karácsonyi fehéregyensúly</h2>
        <p>A karácsony megörökítendő eseményeink a legtöbb helyen belső térben zajlanak, mesterséges megvilágításnál (kivéve ha a tengerparton, pálmafák alatt élvezzük a karácsonyt), ahol a megvilágító fény színe fogja befolyásolni az elkészített felvétel színezetét, vagyis színegyensúlyát. Ezt fehéregyensúlynak nevezik, ami az angol White Balance elnevezés közvetlen fordításából származik.</p>
        <p>A színhelyes kép megalkotásához digitális fényképezőgépünk elektronikáját a megvilágításhoz tudjuk hangolni. A legtöbb digitális fényképezőgépnél ez a beállítás a menüből érhető el, amely alapértelmezésben automatikusan állítja a színegyensúlyt. Ezért az izzólámpa, a gyertya vagy a tűz fénye mellett készült felvételek az automatikus beállításoknál vörösesek lesznek. A neonfény hatására a kép színezete inkább a zöldes árnyalatba fordul át.</p>
        <p>Szerencsére a legtöbb digitális fényképezőgép felajánl más beállítási lehetőségeket is az automatikus üzemmódon kívül. Beáll&amp;iaciacute;tásokat találhatunk nappali fényhez, felhős időhöz, szürkülethez, izzólámpás környezethez, valamint különböző neoncsöves megvilágításokhoz. Komolyabb digitális gépeken manuálisan is beállíthatjuk a fehéregyensúlyt, amelynek a segítségével pontosan a megvilágítási körülményekhez állíthatjuk a színek hangolását. Ilyenkor egy fehér lapról vagy más fehér felületről visszaverődő fényt kell megméretni a digitális géppel, amely kielemzi a <em>CCD-érzékelőre</em> érkező fény színösszetételét, és ennek megfelelően módosítja a színegyensúlyt. Így a fehér lapról érkező fény a későbbiekben meghatározza a kép fehér és semleges tónusainak színhelyességét. Professzionális digitális fényképezőgépeknél lehetőség van a színhőmérséklet számszerű megadására is. Ilyenkor a kívánt <em>Kelvin</em>
            <em>érték</em> egyszerűen léptetéssel beállítható.
        </p>
        <p>Egy-egy felvétel színegyensúlyának beállításához nem léteznek egyértelmű szabályok, hiszen minden a téma természetétől és megvalósítandó céljainktól függ. Azonban megfigyelve a rendelkezésünkre álló fényviszonyokat, igazán hatásos képeket alkothatunk. Ha a gép fehéregyensúlyát nappali vagy automata beállításon hagyjuk, akkor egy kicsit sárgásabb, vörösesebb, azaz melegebb megvilágítást kapunk, amely talán jobban illik a karácsony hangulatához. Ez természetesen megítélés kérdése.</p>
        <p>Ha olyan gépünk van, amelyik <em>RAW</em>
            <em>formátumban</em> is képes rögzíteni a felvételt, akkor utólag is állíthatunk a fehéregyensúlyon.
        </p>
        <SimpleFigure fileName="image (4).jpg" altText="Karácsonyi fotózás 4" caption="A különböző fehéregyensúly-beállítások hatása izzólámpás megvilágítás mellett"/>

        <h2>7. A karácsonyi fények megörökítése</h2>
        <p>Karácsonykor minden fényárban úszik, legyen az egy nappali szoba vagy a feldíszített Andrássy út. Ki ne szeretné megörökíteni? A legelső lépés, hogy kapcsoljuk ki a gépünk beépített vakuját. Helyezzük állványra a gépünket, mert a hosszú expozíciós idő miatt szükség lesz rá. Ha az utcán járunk, és nincs nálunk állvány, keressünk valami olyan fix pontot, amelyhez odaszoríthatjuk gépünket. Egy villanyoszlop, egy korlát vagy egy pad jó szolgálatot tehet.</p>
        <p>A legjobb képeket a szabadban a teljes sötétedés előtt készíthetjük, hiszen ilyenkor az égbolt sötétkék színe sokkal jobban mutat képünkön. Felhős égbolt esetén még érdekes rajzolatokat is kaphatunk. Ha később készül a felvétel, már teljesen fekete lesz a hátterünk. A fehéregyensúlyt érdemes az izzólámpás beállításhoz állítani, hiszen a legtöbb köztéri világítás ebben a tartományban üzemel.</p>
        <p>A szobában készült gyertyafényes képekre is hasonló beállítások vonatkoznak. A bemozdulások csökkentése érdekében az állványról készített felvételnél is használjuk az időzítő funkciót.</p>
        <SimpleFigure fileName="image (5).jpg" altText="Karácsonyi fotózás 5" caption="Vaku nélkül, hosszú expozíciós idővel fotózott karácsonyfa"/>

        <h2>8. Csökkentsük a zavaró részleteket</h2>
        <p>A legtöbb jó felvételen a fókuszpontba helyezett téma vonja magára a figyelmet. Karácsonykor azonban a túl sok téma okozhat problémát, s a képeinken zavarba ejtően sok érdekes részlet, ember, szín, dekoráció jelenhet meg. Ezért a kaotikus hatás ellensúlyozására próbáljuk meg csökkenteni, kiiktatni a túl sok zavaró részletet. Távolítsuk el a téma körül a túl sok dekorációt, esetleg váltsunk nézőpontot, az egyszerűbb fotó többet mond elvét követve.</p>

        <h2>9. Karácsonyi csoportkép</h2>
        <p>Nem igazán telhet el a karácsony csoportkép készítése nélkül. Ez általában macerás feladat, mert valaki mindig lemarad, vagy a háttér nem megfelelő, vagy nincs megfelelő hely az elkészítéséhez. Ha mégis összejön a dolog, nem árt odafigyelni néhány apróságra. Legyen lehetőleg egyenletes fény az egész csoport körül, és a háttér is viszonylag semleges maradjon (természetesen karácsonykor azért a fának is illik a képre kerülni). Ilyenkor a vaku használat szinte automatikus, amely sajnos az erős árnyékhatással rontja a képünk összhatását. Ha lehetőségünk van, akkor ne villantsunk közvetlenül a témára, hanem inkább a mennyezetre vagy egy derítőlapra. Próbáljuk kiiktatni a háttérből a nagyon csillogó felületeket is, mert a vaku fénye könyörtelenül megjelenik rajta.</p>
        <p>Használjuk ki, ha a modelljeink pózolnak, bohóckodnak. Ne csak egyetlen képet készítsünk, hanem próbáljunk sorozatot készíteni. Általában az első képen mereven beálló családtagok a harmadik, negyedik képen már sokkal lazábbnak tűnnek.</p>
        <p>Készíthetünk vaku nélkül is csoportképet. Nagyon szép képek születhetnek, ha csak a gyertyák világítanak körülöttünk. Ilyenkor rakjuk állványra gépünket, és használjuk az időzítő funkciót. Természetesen meg kell kérni a csoport valamennyi tagját, hogy pár másodpercig legyenek mozdulatlanok.</p>

        <h2>10. Kapjuk el a pillanatot!</h2>
        <p>A fotósok számára mindig hálás téma lehet a karácsonyi ajándékbontás pillanata. A mozdulatok, az érzelmek, az arcok, a mosolyok megörökítése azonban nem a legegyszerűbb feladat. Gyorsan kell cselekedni, és persze némi szerencse sem árt. A gépünket kapcsoljuk a sorozatfelvétel üzemmódba, s reménykedjünk, hogy a képek között lesz az adott pillanat. A legtöbb digitális gépen ezt az üzemmódot menüből lehet csak elérni, de pár modellen külső kezelőgombot is található. A fotózás során ilyenkor addig tartjuk nyomva az exponáló gombot, amíg szeretnénk rögzíteni a fotósorozatot. A gépeken általában megadják a másodpercenként rögzíthető képek számát, amely a gép belső memóriájának függvénye.</p>
        <p>A legnagyobb sikerre a tükörreflexes gépeknél számíthatunk, hiszen ezek tudják a leggyorsabban rögzíteni a pillanatot. Az automata gépeknél nagyobb késleltetéssel kell számolnunk, ezért próbáljuk meg ezt kalkulálni, s ha tudjuk „előzzük meg” a pillanatot. A gyorsabb memóriakártyákkal is tudunk nyerni egy-két plusz képkockát.</p>
        <SimpleFigure fileName="image (7).jpg" altText="Karácsonyi fotózás 6" caption="Egy sorozatfelvétel pillanatai"/>

        <h2>11. Használjuk a zoomot, de inkább lépjünk közelebb!</h2>
        <p>A karácsonyi képeken is gyakori probléma, hogy a téma csak a kép egy részén jelenik meg, körülötte csupa felesleges részlettel. Ezt természetesen utólag bármilyen képfeldolgozó programmal levághatjuk, de jobb előre gondolkozni. Komponáljuk meg a képünket, és használjuk a zoomot, vagy akár lépjünk közelebb a témához. :)</p>

        <h2>12. Karácsonyi villanások - óvatosan a vakuval!</h2>
        <p>A karácsonyi fotózáskor az egyik legnagyobb problémát a vaku okozza. Egyrészt zavaró árnyékot rajzol a téma köré, másrészt túlexponálhatja a képet, durva és természetellenes megvilágításba helyezve azt. Az automata gépeken nem sok lehetőség van korrigálni. A közeli felvételeknél jobban tesszük, ha távolabb megyünk inkább, és zoomolunk egy kicsit. Lágyíthatjuk a vaku fényét a vakura szerelt diffúzorral is. (<em>Jobb híján ragaszthatunk a beépített vakura egy pauszpapír darabkát is.)</em> Ezt csak közeli fotózásnál használhatjuk igazán, hiszen a vakunk fényereje is csökken az elé helyezett „fényszóró” elem hatására.
        </p>
        <p>A legfontosabb szempont a karácsonyi portrékészítésnél, hogy lehetőleg kerüljük a direktbe vakuzást. Erre segítség a külső vaku használata, amely dönthető vagy forgatható fejű. Így a vakut nem a modell arcára, hanem valamelyik falra vagy a mennyezetre irányítjuk, s az onnan visszaverődő fénnyel világítjuk meg. Így eltüntethető lesz az indirekt vakuzás okozta zavaró árnyék, kellemesebb, lágyabb megvilágításba helyezve az áldozatunkat. Sokan szeretik a plafonra villantani a vakut, pedig számítani lehet rá, hogy a felülről érkező fény árnyékolni fogja a szemgödröt és árnyékot ragaszthat az orr alá. Érdemes odafigyelni a visszatükröző falfelület színére is, hiszen ha az nem fehér, akkor könnyen megjelennek az arcon oda nem illő színek.</p>
        <p>Ha nincs lehetőség visszaverődő fénnyel deríteni a témát, akkor jó szolgálatot tehetnek az úgynevezett derítőlapok, amelyek a vaku fényét terelik megfelelő irányba, s lágyítják a kialakuló árnyékokat. A legegyszerűbb derítőlap egy világos színű, merev papírlap, amelyet a vaku köré erősítünk valahogy, vagy megkérünk valakit, hogy tartsa meg nekünk a fotózás erejéig. No persze is igaz, hogy a karácsonyi partin elég idétlenül néz ki és fölöttébb zavaró, ha valamelyik családtagnak állandóan a kezébe adunk egy ilyen nagyméretű fehér lapot.</p>
        <p>A vakuhasználat során gyakori probléma, hogy modellünknek vörös lesz a szeme, mert kitágul a pupillája, s a vakuból a szemébe érkező fény visszatükröződik a retinájáról. A legtöbb gépen található vörösszem-effektus csökkentő funkció, amely a vaku villanása előtt egy fényt bocsát ki, amely elméletileg összehúzza a pupillát, s így csökkenti a vörös szem megjelenését a majdani fotón. Ez sokszor segítséget jelent, de nem szabad elfelejteni, hogy ez csupán a vörösszem effektus csökkentését, nem pedig a kiküszöbölését jelenti.</p>
        <p>Ha nincs lehetőség külső vaku használatára, akkor kérjük meg a modellünket, hogy ne közvetlenül a gépbe nézzen, hanem kicsit oldalra, esetleg kapcsoljunk fel több lámpát a helyiségben. Ha a képen mégis rajta marad a vörös szem, akkor nem marad más hátra, mint a szoftveres eltávolítás, amelyre szinte mindegyik képfeldolgozó program ajánl megoldásokat.</p>
        <h2>13. Karácsonyi részletek</h2>
        <p>A legtöbb digitális fényképezőgéppel már<em> 2-3 centiméterről</em> tudunk felvételeket készíteni anélkül, hogy bármilyen kiegészítő makrólencsét alkalmaznánk. A legtöbb gép teljesen automatikus beállításokat engedélyez csak, de általában a programozott beállításain keresztül elérhető a makró funkció. Ezt a funkciót egységesen egy kis virág ikon szimbolizálja a kijelzőn.
        </p>
        <p>A karácsonyfán, az ünnepi asztalon lévő apró dekorációk ideális témákat nyújtanak közelképek készítésére. A makrófotózás jellegzetessége, hogy a mélységélesség jelentősen csökken, ezért fontos a pontos fókuszálás. A kompakt gépeknél elég nehezen oldható meg, mert az autófókusz gyakran beleszól az élességbe, s esetleg nem oda fókuszál, ahová mi gondoltuk. Ezért ha lehetőség van rá, kapcsoljuk ki ilyenkor az autófókuszt, és használjuk a manuális beállítást. A makrófotókat célszerű állványról készíteni, s az időzítőt használni, hogy minimálisra csökkentsük a gép beremegéseit.</p>
        <SimpleFigure fileName="image (6).jpg" altText="Karácsonyi fotózás 7" caption="A mélységélesség szinte csak centiméterekben mérhető"/>

        <h2>14. Milyen expozíciós üzemmódot használjunk karácsonykor?</h2>
        <p>A legtöbb digitális fényképezőgépen a teljesen automata beállításon kívül több, témára szabott üzemmóddal is találhatunk. Ezek az adott témához (<em>tájkép, portré, sport, éjszakai felvétel</em>) legjobban illeszkedő <em>rekesz-idő</em> párosítást állítják be a gépen.
        </p>
        <p>A tájkép üzemmódban nagy kiterjedésű témákat lehet fotózni. Ilyenkor a gép a lehető legkisebb rekesznyílást alkalmazza a minél nagyobb mélységélesség érdekében. A legtöbb esetben az élesség automatikusan végtelenre állítódik. A karácsonyi csoportképeinkhez ez megfelelő beállítás.</p>
        <p>A portréprogramot akkor alkalmazzuk, ha azt szeretnénk, hogy a háttérben lévő részletek elmosódottak legyenek. Ez a program tipikusan arcok és tárgyak fotózására alkalmas, hiszen a téma így kiemelkedik a háttérből. Ebben az üzemmódban nagyobb rekesznyílást állít be a gép, amely a mélységélesség csökkenését eredményezi. A háttér pedig annál elmosódottabb lesz, minél nagyobb gyújtótávolságot használunk.</p>
        <SimpleFigure fileName="image (2).jpg" altText="Karácsonyi fotózás 8" caption="Egy morcos mikulás mindig jó fotótéma"/>
        <p>A sportprogramban a lehető legrövidebb expozíciós időt használja digitális fényképezőgépünk, amelyet gyorsan mozgó témák megörökítésénél célszerű használni. A játszó gyerekek megörökítéséhez ideális ez a beállítás.</p>
        <p>Az éjszakai felvétel üzemmódot akkor érdemes használni, ha embereket szeretnénk lefotózni esti égbolt előtt vagy nagyon rossz megvilágítású helyen. Ebben az üzemmódban a vaku világítja meg az embereket, a háttér helyes expozíciójához pedig hosszú megvilágítási időt használ a digitális gépünk. Ilyenkor a hosszú záridő miatt célszerű megkérni a fényképezni kívánt személyeket, hogy a vaku villanása után néhány másodpercig még ne mozogjanak.</p>
        <p>Természetesen, ha nem vagyunk elégedettek az automata beállításokkal, akkor átválthatunk egy nagyobb alkotói szabadságot engedélyező üzemmódba.</p>
        <p>A <em>rekesz-prioritás</em> (A), vagy más néven időautomata üzemmódban a rekesznyílás értékét mi választhatjuk ki, a digitális fényképezőgépünk pedig automatikusan beállítja az expozíciós időt a téma világosságának megfelelően. Ennek az üzemmódnak több előnye is van. Mivel a mélységélesség a rekesznyílástól függ, ezért ezt pontosan beállíthatjuk, s a fényviszonyok megváltozása sem fogja érinteni. Másik használati előnye, hogy az expozíciós időknek meglehetősen széles tartománya áll a rendelkezésünkre, ezért extrém fényviszonyok között is nagy valószínűséggel talál az automatika a beállított rekesznyíláshoz megfelelő értéket. Hosszú expozíciós időknél természetesen figyelni kell a bemozdulás veszélyre.
        </p>
        <p>A karácsonyi dekorációk fotózásakor nagy rekesznyílást válasszunk, s ilyenkor a háttér elmosódva fog megjelenni. Viszont ha azt akarjuk, hogy a karácsonyi asztalunk egész hosszában éles legyen, akkor a kis rekesznyílásra voksoljunk.</p>
        <p>Az <em>idő-prioritás</em> (T), vagy más néven rekeszautomata üzemmódban az expozíciós időt választhatjuk szabadon, a fényképezőgép pedig automatikusan beállítja a rekeszértéket a téma világosságának megfelelően. Ebben az üzemmódban rövid expozíciós idővel meg lehet „fagyasztani” a mozgást, amely a fény csökkenésével egyidejűleg is fenntartható.
        </p>
    </>;
}

// frontend/src/materials/third-party-content/hu/hvg-tippek-a-karacsonyi-fotozashoz.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'hvg-tippek-a-karacsonyi-fotozashoz',
            title: 'Tippek a karácsonyi fotózáshoz',
            author: 'techline.hu',
            publishDate: new Date('2007-12-25'),
            publisherName: 'HVG',
            originalUrl: 'https://hvg.hu/tudomany/20071221_karacsonyifoto',
            isOriginalUrlBroken: false,
        }
    }
</script>

<script lang="ts">
    import SimpleFigure from '../../components/SimpleFigure.svelte'
</script>

<h2>1. Készüljünk fel a nagy pillanatokra!</h2>
<p>
    Bizonyára sokakkal előfordult már a fotózás során, hogy lemaradt a legjobb pillanatokról, mert elfelejtette
    feltölteni az akkumulátort, vagy letörölni a betelt memóriakártyát. Ezért a karácsonyi események előtt célszerű
    ellenőrizni néhány apróságot – megéri.
</p>
<p>Keressük meg a digitális gépünket. :) Töltsük fel az akkumulátorokat, s lehetőleg gondoskodjunk tartalékról is.</p>
<p>
    Ellenőrizzük a memóriakártyát. Ha tele van, mentsük le a tartalmát. Legyen megfelelő a kártya kapacitása. A gépekhez
    adott memóriakártya <em>16 vagy 32 megabájtja</em> nem sok képre elegendő. Még időben szerezzünk be egy
    <em>minimum 512 MB-os </em>kártyát. S az sem árt, ha egy kicsit gyorsabb tud lenni, hiszen egy sorozatfelvételnél a
    kártyára való írás is lassíthatja a felvételt.
</p>
<p>
    Ha lehetőségünk van rá, tartsunk terepszemlét a családi fotózás helyszínén, lehetőleg még nyugodt körülmények
    között. Képzeljük el milyen lesz a leendő háttér, mérjük fel, hogy vannak-e zavaró részletek, amelyeket érdemes
    elkerülni. Ellenőrizzük a megvilágítást, s gondoljuk át, vajon elegendő fény lesz-e számunkra, kell-e majd vakut
    használni. Az sem mindegy, hogy izzólámpával, esetleg neonnal lesz-e dolgunk. Határozzuk meg, honnan lesznek a
    legjobbak a képeink, s érdemes olykor elpakolni néhány belógó kacatot, amelyeket később csak kitartó retusálással
    lehet eltüntetni. Készítsünk néhány próbafelvételt, hogy még időben észrevehessük a lehetséges hibákat.
</p>
<SimpleFigure
    fileName="image (1).jpg"
    altText="Karácsonyi fotózás 1"
    caption="Egy betelt memóriakártya kellemetlen meglepetést okozhat"
/>

<h2>2. Készítsünk fotósarkot!</h2>
<p>
    A karácsonykor általában sok portréfotót készítünk, de még családunkban is akadnak olyanok, akik nem szeretik, ha
    fotózzák őket (de legalábbis kellő hangulatban kell lenniük ehhez.) Éppen ezért lehet jó ötlet, ha kijelölünk egy
    fotósarkot karácsonykor, ahol mindig ideális körülményeket biztosítunk, például egy karosszéket a karácsonyfa
    mellett, sok zavaró, figyelmet elterelő részlet nélkül. Ha a fényképezőgépet állványra helyezzük, és bekapcsoljuk az
    időzítőjét (ez az a kis gomb, amelyet aktiválva 15-20 másodperc múlva exponál csak a gépünk), akkor ott sem kell
    lennünk a fotó elkészülésekor. A modelljeink saját maguk kezelhetik a gépet, kényelmesen elhelyezkedhetnek, nem
    zavarja őket semmi. Figyeljük meg, hogy modelljeink a karácsony folyamán többször is be fognak ülni rögtönzött
    fotósarkunkba egy-két újabb fotó erejéig.
</p>

<h2>3. Az előkészület pillanatai</h2>
<p>
    Természetesen a karácsonyi ajándékozás, az ünnepi vacsora pillanatai a legemlékezetesebbek, de sokszor az
    előkészületek alatt már nagyon jó képeket készíthetünk. A finomságok készítése, az asztal megterítése, a dekorációk
    felrakása, az ajándékok csomagolása közben mindig találunk egy-egy pillanatot, amely fotóalbumunk büszkeségére
    válhat.
</p>
<SimpleFigure fileName="image (3).jpg" altText="Karácsonyi fotózás 2" caption="Készül a mézeskalács karácsonyra" />

<h2>4. Buli előtt és után</h2>
<p>
    Sokszor készítünk olyan felvételeket, amelyeknél megjegyezzük: az lett volna az igazi, ha meg tudjuk mutatni, milyen
    volt korábban az adott téma. Jó példa erre a gyerekek szépen elrendezett ajándéka a fa alatt, majd az eufórikus
    bontogatás folyamata, s végül a papírfoszlányok mindenfelé. Készüljünk rá! Jó megoldás, ha még a karácsonyi parti
    előtt készítünk pár jellegzetes felvételt, lehetőleg olyan helyzetből, amelyből a későbbiekben is fotózni fogunk.
</p>
<SimpleFigure fileName="image.jpg" altText="Karácsonyi fotózás 3" caption="Az egyik karácsonyi csomag akció előtt" />

<h2>5. Karácsonyi gyorsított felvétel</h2>
<p>
    Látványos felvételsorozatot készíthetünk a karácsonyi eseményekről webkameránk segítségével . Irányítsuk a kamerát a
    karácsonyfára, s állítsuk be, hogy 5 percenként készítsen egy felvételt. A nap végén a legnagyobb élmény lesz
    visszanézni ezeket a gyorsított felvételszerű képeket. Sajnos ehhez a számítógépet is az események közelébe kell
    vonszolni, de szerencsére már van néhány olyan videokamera, amely képes fotókat készíteni és az időzítést is
    megoldani. Természetesen ne felejtsük el állványra helyezni a kamerát.
</p>

<h2>6. A karácsonyi fehéregyensúly</h2>
<p>
    A karácsony megörökítendő eseményeink a legtöbb helyen belső térben zajlanak, mesterséges megvilágításnál (kivéve ha
    a tengerparton, pálmafák alatt élvezzük a karácsonyt), ahol a megvilágító fény színe fogja befolyásolni az
    elkészített felvétel színezetét, vagyis színegyensúlyát. Ezt fehéregyensúlynak nevezik, ami az angol White Balance
    elnevezés közvetlen fordításából származik.
</p>
<p>
    A színhelyes kép megalkotásához digitális fényképezőgépünk elektronikáját a megvilágításhoz tudjuk hangolni. A
    legtöbb digitális fényképezőgépnél ez a beállítás a menüből érhető el, amely alapértelmezésben automatikusan állítja
    a színegyensúlyt. Ezért az izzólámpa, a gyertya vagy a tűz fénye mellett készült felvételek az automatikus
    beállításoknál vörösesek lesznek. A neonfény hatására a kép színezete inkább a zöldes árnyalatba fordul át.
</p>
<p>
    Szerencsére a legtöbb digitális fényképezőgép felajánl más beállítási lehetőségeket is az automatikus üzemmódon
    kívül. Beáll&amp;iaciacute;tásokat találhatunk nappali fényhez, felhős időhöz, szürkülethez, izzólámpás
    környezethez, valamint különböző neoncsöves megvilágításokhoz. Komolyabb digitális gépeken manuálisan is
    beállíthatjuk a fehéregyensúlyt, amelynek a segítségével pontosan a megvilágítási körülményekhez állíthatjuk a
    színek hangolását. Ilyenkor egy fehér lapról vagy más fehér felületről visszaverődő fényt kell megméretni a
    digitális géppel, amely kielemzi a <em>CCD-érzékelőre</em> érkező fény színösszetételét, és ennek megfelelően
    módosítja a színegyensúlyt. Így a fehér lapról érkező fény a későbbiekben meghatározza a kép fehér és semleges
    tónusainak színhelyességét. Professzionális digitális fényképezőgépeknél lehetőség van a színhőmérséklet számszerű
    megadására is. Ilyenkor a kívánt <em>Kelvin</em>
    <em>érték</em> egyszerűen léptetéssel beállítható.
</p>
<p>
    Egy-egy felvétel színegyensúlyának beállításához nem léteznek egyértelmű szabályok, hiszen minden a téma
    természetétől és megvalósítandó céljainktól függ. Azonban megfigyelve a rendelkezésünkre álló fényviszonyokat,
    igazán hatásos képeket alkothatunk. Ha a gép fehéregyensúlyát nappali vagy automata beállításon hagyjuk, akkor egy
    kicsit sárgásabb, vörösesebb, azaz melegebb megvilágítást kapunk, amely talán jobban illik a karácsony hangulatához.
    Ez természetesen megítélés kérdése.
</p>
<p>
    Ha olyan gépünk van, amelyik <em>RAW</em>
    <em>formátumban</em> is képes rögzíteni a felvételt, akkor utólag is állíthatunk a fehéregyensúlyon.
</p>
<SimpleFigure
    fileName="image (4).jpg"
    altText="Karácsonyi fotózás 4"
    caption="A különböző fehéregyensúly-beállítások hatása izzólámpás megvilágítás mellett"
/>

<h2>7. A karácsonyi fények megörökítése</h2>
<p>
    Karácsonykor minden fényárban úszik, legyen az egy nappali szoba vagy a feldíszített Andrássy út. Ki ne szeretné
    megörökíteni? A legelső lépés, hogy kapcsoljuk ki a gépünk beépített vakuját. Helyezzük állványra a gépünket, mert a
    hosszú expozíciós idő miatt szükség lesz rá. Ha az utcán járunk, és nincs nálunk állvány, keressünk valami olyan fix
    pontot, amelyhez odaszoríthatjuk gépünket. Egy villanyoszlop, egy korlát vagy egy pad jó szolgálatot tehet.
</p>
<p>
    A legjobb képeket a szabadban a teljes sötétedés előtt készíthetjük, hiszen ilyenkor az égbolt sötétkék színe sokkal
    jobban mutat képünkön. Felhős égbolt esetén még érdekes rajzolatokat is kaphatunk. Ha később készül a felvétel, már
    teljesen fekete lesz a hátterünk. A fehéregyensúlyt érdemes az izzólámpás beállításhoz állítani, hiszen a legtöbb
    köztéri világítás ebben a tartományban üzemel.
</p>
<p>
    A szobában készült gyertyafényes képekre is hasonló beállítások vonatkoznak. A bemozdulások csökkentése érdekében az
    állványról készített felvételnél is használjuk az időzítő funkciót.
</p>
<SimpleFigure
    fileName="image (5).jpg"
    altText="Karácsonyi fotózás 5"
    caption="Vaku nélkül, hosszú expozíciós idővel fotózott karácsonyfa"
/>

<h2>8. Csökkentsük a zavaró részleteket</h2>
<p>
    A legtöbb jó felvételen a fókuszpontba helyezett téma vonja magára a figyelmet. Karácsonykor azonban a túl sok téma
    okozhat problémát, s a képeinken zavarba ejtően sok érdekes részlet, ember, szín, dekoráció jelenhet meg. Ezért a
    kaotikus hatás ellensúlyozására próbáljuk meg csökkenteni, kiiktatni a túl sok zavaró részletet. Távolítsuk el a
    téma körül a túl sok dekorációt, esetleg váltsunk nézőpontot, az egyszerűbb fotó többet mond elvét követve.
</p>

<h2>9. Karácsonyi csoportkép</h2>
<p>
    Nem igazán telhet el a karácsony csoportkép készítése nélkül. Ez általában macerás feladat, mert valaki mindig
    lemarad, vagy a háttér nem megfelelő, vagy nincs megfelelő hely az elkészítéséhez. Ha mégis összejön a dolog, nem
    árt odafigyelni néhány apróságra. Legyen lehetőleg egyenletes fény az egész csoport körül, és a háttér is viszonylag
    semleges maradjon (természetesen karácsonykor azért a fának is illik a képre kerülni). Ilyenkor a vaku használat
    szinte automatikus, amely sajnos az erős árnyékhatással rontja a képünk összhatását. Ha lehetőségünk van, akkor ne
    villantsunk közvetlenül a témára, hanem inkább a mennyezetre vagy egy derítőlapra. Próbáljuk kiiktatni a háttérből a
    nagyon csillogó felületeket is, mert a vaku fénye könyörtelenül megjelenik rajta.
</p>
<p>
    Használjuk ki, ha a modelljeink pózolnak, bohóckodnak. Ne csak egyetlen képet készítsünk, hanem próbáljunk sorozatot
    készíteni. Általában az első képen mereven beálló családtagok a harmadik, negyedik képen már sokkal lazábbnak
    tűnnek.
</p>
<p>
    Készíthetünk vaku nélkül is csoportképet. Nagyon szép képek születhetnek, ha csak a gyertyák világítanak
    körülöttünk. Ilyenkor rakjuk állványra gépünket, és használjuk az időzítő funkciót. Természetesen meg kell kérni a
    csoport valamennyi tagját, hogy pár másodpercig legyenek mozdulatlanok.
</p>

<h2>10. Kapjuk el a pillanatot!</h2>
<p>
    A fotósok számára mindig hálás téma lehet a karácsonyi ajándékbontás pillanata. A mozdulatok, az érzelmek, az arcok,
    a mosolyok megörökítése azonban nem a legegyszerűbb feladat. Gyorsan kell cselekedni, és persze némi szerencse sem
    árt. A gépünket kapcsoljuk a sorozatfelvétel üzemmódba, s reménykedjünk, hogy a képek között lesz az adott pillanat.
    A legtöbb digitális gépen ezt az üzemmódot menüből lehet csak elérni, de pár modellen külső kezelőgombot is
    található. A fotózás során ilyenkor addig tartjuk nyomva az exponáló gombot, amíg szeretnénk rögzíteni a
    fotósorozatot. A gépeken általában megadják a másodpercenként rögzíthető képek számát, amely a gép belső
    memóriájának függvénye.
</p>
<p>
    A legnagyobb sikerre a tükörreflexes gépeknél számíthatunk, hiszen ezek tudják a leggyorsabban rögzíteni a
    pillanatot. Az automata gépeknél nagyobb késleltetéssel kell számolnunk, ezért próbáljuk meg ezt kalkulálni, s ha
    tudjuk „előzzük meg” a pillanatot. A gyorsabb memóriakártyákkal is tudunk nyerni egy-két plusz képkockát.
</p>
<SimpleFigure fileName="image (7).jpg" altText="Karácsonyi fotózás 6" caption="Egy sorozatfelvétel pillanatai" />

<h2>11. Használjuk a zoomot, de inkább lépjünk közelebb!</h2>
<p>
    A karácsonyi képeken is gyakori probléma, hogy a téma csak a kép egy részén jelenik meg, körülötte csupa felesleges
    részlettel. Ezt természetesen utólag bármilyen képfeldolgozó programmal levághatjuk, de jobb előre gondolkozni.
    Komponáljuk meg a képünket, és használjuk a zoomot, vagy akár lépjünk közelebb a témához. :)
</p>

<h2>12. Karácsonyi villanások - óvatosan a vakuval!</h2>
<p>
    A karácsonyi fotózáskor az egyik legnagyobb problémát a vaku okozza. Egyrészt zavaró árnyékot rajzol a téma köré,
    másrészt túlexponálhatja a képet, durva és természetellenes megvilágításba helyezve azt. Az automata gépeken nem sok
    lehetőség van korrigálni. A közeli felvételeknél jobban tesszük, ha távolabb megyünk inkább, és zoomolunk egy
    kicsit. Lágyíthatjuk a vaku fényét a vakura szerelt diffúzorral is. (<em
        >Jobb híján ragaszthatunk a beépített vakura egy pauszpapír darabkát is.)</em
    > Ezt csak közeli fotózásnál használhatjuk igazán, hiszen a vakunk fényereje is csökken az elé helyezett „fényszóró” elem
    hatására.
</p>
<p>
    A legfontosabb szempont a karácsonyi portrékészítésnél, hogy lehetőleg kerüljük a direktbe vakuzást. Erre segítség a
    külső vaku használata, amely dönthető vagy forgatható fejű. Így a vakut nem a modell arcára, hanem valamelyik falra
    vagy a mennyezetre irányítjuk, s az onnan visszaverődő fénnyel világítjuk meg. Így eltüntethető lesz az indirekt
    vakuzás okozta zavaró árnyék, kellemesebb, lágyabb megvilágításba helyezve az áldozatunkat. Sokan szeretik a
    plafonra villantani a vakut, pedig számítani lehet rá, hogy a felülről érkező fény árnyékolni fogja a szemgödröt és
    árnyékot ragaszthat az orr alá. Érdemes odafigyelni a visszatükröző falfelület színére is, hiszen ha az nem fehér,
    akkor könnyen megjelennek az arcon oda nem illő színek.
</p>
<p>
    Ha nincs lehetőség visszaverődő fénnyel deríteni a témát, akkor jó szolgálatot tehetnek az úgynevezett derítőlapok,
    amelyek a vaku fényét terelik megfelelő irányba, s lágyítják a kialakuló árnyékokat. A legegyszerűbb derítőlap egy
    világos színű, merev papírlap, amelyet a vaku köré erősítünk valahogy, vagy megkérünk valakit, hogy tartsa meg
    nekünk a fotózás erejéig. No persze is igaz, hogy a karácsonyi partin elég idétlenül néz ki és fölöttébb zavaró, ha
    valamelyik családtagnak állandóan a kezébe adunk egy ilyen nagyméretű fehér lapot.
</p>
<p>
    A vakuhasználat során gyakori probléma, hogy modellünknek vörös lesz a szeme, mert kitágul a pupillája, s a vakuból
    a szemébe érkező fény visszatükröződik a retinájáról. A legtöbb gépen található vörösszem-effektus csökkentő
    funkció, amely a vaku villanása előtt egy fényt bocsát ki, amely elméletileg összehúzza a pupillát, s így csökkenti
    a vörös szem megjelenését a majdani fotón. Ez sokszor segítséget jelent, de nem szabad elfelejteni, hogy ez csupán a
    vörösszem effektus csökkentését, nem pedig a kiküszöbölését jelenti.
</p>
<p>
    Ha nincs lehetőség külső vaku használatára, akkor kérjük meg a modellünket, hogy ne közvetlenül a gépbe nézzen,
    hanem kicsit oldalra, esetleg kapcsoljunk fel több lámpát a helyiségben. Ha a képen mégis rajta marad a vörös szem,
    akkor nem marad más hátra, mint a szoftveres eltávolítás, amelyre szinte mindegyik képfeldolgozó program ajánl
    megoldásokat.
</p>
<h2>13. Karácsonyi részletek</h2>
<p>
    A legtöbb digitális fényképezőgéppel már<em> 2-3 centiméterről</em> tudunk felvételeket készíteni anélkül, hogy bármilyen
    kiegészítő makrólencsét alkalmaznánk. A legtöbb gép teljesen automatikus beállításokat engedélyez csak, de általában a
    programozott beállításain keresztül elérhető a makró funkció. Ezt a funkciót egységesen egy kis virág ikon szimbolizálja
    a kijelzőn.
</p>
<p>
    A karácsonyfán, az ünnepi asztalon lévő apró dekorációk ideális témákat nyújtanak közelképek készítésére. A
    makrófotózás jellegzetessége, hogy a mélységélesség jelentősen csökken, ezért fontos a pontos fókuszálás. A kompakt
    gépeknél elég nehezen oldható meg, mert az autófókusz gyakran beleszól az élességbe, s esetleg nem oda fókuszál,
    ahová mi gondoltuk. Ezért ha lehetőség van rá, kapcsoljuk ki ilyenkor az autófókuszt, és használjuk a manuális
    beállítást. A makrófotókat célszerű állványról készíteni, s az időzítőt használni, hogy minimálisra csökkentsük a
    gép beremegéseit.
</p>
<SimpleFigure
    fileName="image (6).jpg"
    altText="Karácsonyi fotózás 7"
    caption="A mélységélesség szinte csak centiméterekben mérhető"
/>

<h2>14. Milyen expozíciós üzemmódot használjunk karácsonykor?</h2>
<p>
    A legtöbb digitális fényképezőgépen a teljesen automata beállításon kívül több, témára szabott üzemmóddal is
    találhatunk. Ezek az adott témához (<em>tájkép, portré, sport, éjszakai felvétel</em>) legjobban illeszkedő
    <em>rekesz-idő</em> párosítást állítják be a gépen.
</p>
<p>
    A tájkép üzemmódban nagy kiterjedésű témákat lehet fotózni. Ilyenkor a gép a lehető legkisebb rekesznyílást
    alkalmazza a minél nagyobb mélységélesség érdekében. A legtöbb esetben az élesség automatikusan végtelenre
    állítódik. A karácsonyi csoportképeinkhez ez megfelelő beállítás.
</p>
<p>
    A portréprogramot akkor alkalmazzuk, ha azt szeretnénk, hogy a háttérben lévő részletek elmosódottak legyenek. Ez a
    program tipikusan arcok és tárgyak fotózására alkalmas, hiszen a téma így kiemelkedik a háttérből. Ebben az
    üzemmódban nagyobb rekesznyílást állít be a gép, amely a mélységélesség csökkenését eredményezi. A háttér pedig
    annál elmosódottabb lesz, minél nagyobb gyújtótávolságot használunk.
</p>
<SimpleFigure fileName="image (2).jpg" altText="Karácsonyi fotózás 8" caption="Egy morcos mikulás mindig jó fotótéma" />
<p>
    A sportprogramban a lehető legrövidebb expozíciós időt használja digitális fényképezőgépünk, amelyet gyorsan mozgó
    témák megörökítésénél célszerű használni. A játszó gyerekek megörökítéséhez ideális ez a beállítás.
</p>
<p>
    Az éjszakai felvétel üzemmódot akkor érdemes használni, ha embereket szeretnénk lefotózni esti égbolt előtt vagy
    nagyon rossz megvilágítású helyen. Ebben az üzemmódban a vaku világítja meg az embereket, a háttér helyes
    expozíciójához pedig hosszú megvilágítási időt használ a digitális gépünk. Ilyenkor a hosszú záridő miatt célszerű
    megkérni a fényképezni kívánt személyeket, hogy a vaku villanása után néhány másodpercig még ne mozogjanak.
</p>
<p>
    Természetesen, ha nem vagyunk elégedettek az automata beállításokkal, akkor átválthatunk egy nagyobb alkotói
    szabadságot engedélyező üzemmódba.
</p>
<p>
    A <em>rekesz-prioritás</em> (A), vagy más néven időautomata üzemmódban a rekesznyílás értékét mi választhatjuk ki, a digitális
    fényképezőgépünk pedig automatikusan beállítja az expozíciós időt a téma világosságának megfelelően. Ennek az üzemmódnak
    több előnye is van. Mivel a mélységélesség a rekesznyílástól függ, ezért ezt pontosan beállíthatjuk, s a fényviszonyok
    megváltozása sem fogja érinteni. Másik használati előnye, hogy az expozíciós időknek meglehetősen széles tartománya áll
    a rendelkezésünkre, ezért extrém fényviszonyok között is nagy valószínűséggel talál az automatika a beállított rekesznyíláshoz
    megfelelő értéket. Hosszú expozíciós időknél természetesen figyelni kell a bemozdulás veszélyre.
</p>
<p>
    A karácsonyi dekorációk fotózásakor nagy rekesznyílást válasszunk, s ilyenkor a háttér elmosódva fog megjelenni.
    Viszont ha azt akarjuk, hogy a karácsonyi asztalunk egész hosszában éles legyen, akkor a kis rekesznyílásra
    voksoljunk.
</p>
<p>
    Az <em>idő-prioritás</em> (T), vagy más néven rekeszautomata üzemmódban az expozíciós időt választhatjuk szabadon, a fényképezőgép
    pedig automatikusan beállítja a rekeszértéket a téma világosságának megfelelően. Ebben az üzemmódban rövid expozíciós
    idővel meg lehet „fagyasztani” a mozgást, amely a fény csökkenésével egyidejűleg is fenntartható.
</p>
