// frontend/src/materials/third-party-content/hu/indafoto-fenycsikok-hosszu-zaridovel.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'indafoto-fenycsikok-hosszu-zaridovel',
            title: 'Fénycsíkok hosszú záridővel',
            author: 'Réka',
            publishDate: new Date('2011-05-19'),
            publisherName: 'Indafotó',
            originalUrl: 'https://www.onlinefototanfolyam.hu/aktualis-cikkek/mi-a-gyujtotavolsag-szorzo-/47545/',
            isOriginalUrlBroken: false,
        }
    }
</script>

<script lang="ts">
    import SimpleFigure from '../../components/SimpleFigure.svelte'
</script>

<p>
    Az éjszakai fotókat, amennyiben nem teljesen érintetlen tájról szeretnénk fotót készíteni, általában feldobja a
    járművekről vagy egyéb mozgó tárgyak mozgása során rögzített fénycsík. Ebben a posztban róluk fogok szólni.
</p>
<SimpleFigure fileName="6745191_6a062f3e73c9311d6b4adfe0f95d61be_m.jpg" altText="Réka: Winter Wonderland" />
<p>
    A hosszú záridős fénycsíkok úgy keletkeznek, hogy a több másodperces exponálás során a mozgó tárgyak (emberek)
    elmosódva jelennek meg a képen. Minél hosszabb a záridő, annál elmosottabb lesz a tárgy, végül teljesen eltűnik a
    képről, és csak lámpáinak fénye marad a fotón, hosszú csíkot húzva.
</p>
<p>
    Ezeket a fotókat több okból is célszerű este készíteni: nappal nem látszanak olyan tisztán az autók fénycsíkjai, és
    az elmosódáshoz szükséges hosszú záridőt is nehezebb elérni nappal (csak erős szürkeszűrők segítségével sikerül).
    Azonban a legsötétebb éjszaka sem ideális a műfajhoz, hiszen a fekete, részlettelen égbolt, víztükör stb, nem túl
    szép látvány. Legszebb képeket, mint általában az éjszakai fotózásban, a kék órában kapunk, amikor az ég még nem
    fekete, de a város fényei már kigyúltak. A kék óra azért is hasznos, mert a sötétben lehetetlen helyesen kiexponálni
    a sötét részeket és a nagyon világos fénycsíkokat - a lágy fényű kék órában jobb eséllyel lesz kiégés- és
    bebukásmentes a fotó. Ennél a képnél a zúzmarás fák alkonyati kékes derengése szolgáltatja a hátteret a féklámpa
    csíkjának.
</p>
<p>
    Persze ez nem törvényszerű, az alábbi képnél kimondottan a rideg sötétségre törekedtem, amelyet melegen roncsol szét
    az elhaladó taxi meleg fénye. A hepehupás úttest megugrasztotta a kocsit, ezáltal girbegurba lett a fénycsík is.
</p>
<SimpleFigure fileName="6745047_7ee9d0aa4007a32c7ff7879366a87cd7_m.jpg" altText="Réka: Hazafelé" />
<p>
    Alap esetben azt szeretném, hogy a járművek lámpái elmosódjanak, a környezet azonban maradjon éles - ehhez állványra
    lesz szükség, hiszen a záridő 5-30 másodperc körül fog alakulni. Fénycsíkos kép minden olyan géppel készíthető -
    kompakttal is-, amely állványra rögzíthető (a csatlakozó ipari szabvány) és legalább 5-8 másodperces záridőre képes.
</p>
<p>
    Ha találtam egy alkalmas helyet, pl. egy utcát, amely S-kanyarban fekszik, egy mozgalmas teret vagy más, szimpatikus
    helyszínt, akkor rögzítem az állványt, rajta a géppel és megkomponálom a fotót. Lehetőleg úgy kell helyezkednem,
    hogy az autók ne oldalról suhanjanak el mellettem, hanem kissé srégen, mögülem kerüljenek a képbe. Ha ugyanis
    oldalról fotózok mondjuk egy utcát, akkor csak a kocsik oldalsó indexfényét fogom rögzíteni és nagyon halvány
    fénycsíkot fogok kapni. Ezért jó hely mondjuk egy S-kanyar vagy egy tér közepe, mert akkor szemből-hátról jönnek a
    kocsik és így látványos fotó lesz a fényszórókból, hátsó fényekből. Akár felülnézetből is lehet fotózni, ezt a képet
    a buszpályaudvar felett állva készítettem a ki-beálló autóbuszokról.
</p>
<SimpleFigure fileName="6808081_770fcbb59c379015aa41ea935f34ea04_l.jpg" altText="Réka: Slussen" />
<p>
    Miután sikeresen beálltam (mármint a megfelelő helyre!), elkezdhetek gondolkodni a záridőn. Célszerű a záridőt úgy
    igazítani, hogy az elhaladó autó kb az expo kezdetekor haladjon be a képkockába, és az expo végén haladjon ki
    belőle. Ha az exponálás túl rövid a kocsi sebességéhez képest, akkor csak a kép közepén lesz egy rövid fénycsík - ha
    viszont túl hosszú ideig exponálok, akkor a kocsi fénye csak egy halovány csíkként fog megjelenni. Ha a kocsi
    mondjuk 5 másodperc alatt halad át a keresőnkön, akkor 5-6 másodperces záridő az ideális - ha viszont cammog, és
    csak 30 másodperc alatt mászik át a képkockán, akkor 30 másodperc körüli záridő lesz a jó ahhoz, hogy jó
    látványosan, a képkockát kitöltve jelenjen meg a fényszóró vagy a helyzetjelző fénye.
</p>
<p>
    A tükrös gépesek, távkioldóval rendelkezők ehhez használhatják a B záridőt is, ez a legegyszerűbb - amint a kocsi
    belesuhan a képkockába, akkor exponálás kezd, ha meg kihaladt belőle, akkor exponálás megszakít. Nyilván ehhez kell
    majd igazítani a rekeszt és az ISOt is, hogy korrekt expo értékeket kapjunk.
</p>
<p>
    De kompakttal is be lehet lőni, hogy mekkora záridőre lehet szükség, egyszerűen meg kell figyelni néhány kocsit és
    lőni pár próbafelvételt, no meg remélni, hogy a következő autó betartja a sebességkorlátot és nem mondjuk 30 helyett
    120-al húz el a gép előtt, mert akkor semmi nem fog látszani belőle. Téli estéken ez a tesztelgetés csak kesztyűben
    megoldható, előre szólok! :) azonban a tél azért is alkalmas erre a műfajra, mert mivel korán sötétedik, nem kell
    későig kint lenni a fotós cuccal, hanem vacsorára már otthon lehetünk a zsákmánnyal, munka után is megoldható
    egy-egy gyors fotózás.
</p>
<p>
    Bár az állvány szinte elengedhetetlen kelléke a fénycsíkfotózásnak, néha nem árt levenni a gépet és csak úgy
    meglengetni a levegőben exponálás közben, ki tudja, mi sül ki belőle. Egy számomra kedves képem Budapestről pont így
    készült, akár egy átmulatott éjszaka után való hazatérést is ábrázolhatna.
</p>
<SimpleFigure fileName="7421551_2a255fb98ef159febc352d8514d8453c_m.jpg" altText="Réka: Vision of Love" />
<p>További tippek: ki lehet próbálni a fekete-fehér változatot is, elegáns hangulatot kölcsönöz a fotónak.</p>
<p>
    Vagy hosszú záridő helyett épp egy szokásosnál kicsivel hosszabbat, hogy épp mozduljon be a téma: mozgalmas,
    dinamikus végeredményt kapunk.
</p>
<p>
    Az alábbi fotó pedig kompakttal készült, zuhogó esőben tartottam hazafelé és megláttam a vizesen fénylő, tükröződő
    aszfaltban rejlő lehetőségeket. A gépet egy trafódobozra raktam, a kabátról lecsatolt csuklyámat tartottam felé és
    imádkoztam, hogy jöjjön egy autó, mielőtt az egész várost elnyeli az özönvíz.
</p>
<SimpleFigure fileName="jhov.jpg" altText="Illusztráció" />

// frontend/src/materials/third-party-content/hu/indafoto-fenycsikok-hosszu-zaridovel.jsx
import React from 'react';
import SimpleFigure from '../../components/SimpleFigure.jsx';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'indafoto-fenycsikok-hosszu-zaridovel',
        title: 'Fénycsíkok hosszú záridővel',
        author: 'Réka',
        publishDate: new Date('2011-05-19'),
        publisherName: 'Indafotó',
        originalUrl: 'https://www.onlinefototanfolyam.hu/aktualis-cikkek/mi-a-gyujtotavolsag-szorzo-/47545/',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <p>Az éjszakai fotókat, amennyiben nem teljesen érintetlen tájról szeretnénk fotót készíteni, általában feldobja a járművekről vagy egyéb mozgó tárgyak mozgása során rögzített fénycsík. Ebben a posztban róluk fogok szólni.</p>
        <SimpleFigure fileName="6745191_6a062f3e73c9311d6b4adfe0f95d61be_m.jpg" altText="Réka: Winter Wonderland"/>
        <p> A hosszú záridős fénycsíkok úgy keletkeznek, hogy a több másodperces exponálás során a mozgó tárgyak (emberek) elmosódva jelennek meg a képen. Minél hosszabb a záridő, annál elmosottabb lesz a tárgy, végül teljesen eltűnik a képről, és csak lámpáinak fénye marad a fotón, hosszú csíkot húzva.</p>
        <p>Ezeket a fotókat több okból is célszerű este készíteni: nappal nem látszanak olyan tisztán az autók fénycsíkjai, és az elmosódáshoz szükséges hosszú záridőt is nehezebb elérni nappal (csak erős szürkeszűrők segítségével sikerül). Azonban a legsötétebb éjszaka sem ideális a műfajhoz, hiszen a fekete, részlettelen égbolt, víztükör stb, nem túl szép látvány. Legszebb képeket, mint általában az éjszakai fotózásban, a kék órában kapunk, amikor az ég még nem fekete, de a város fényei már kigyúltak. A kék óra azért is hasznos, mert a sötétben lehetetlen helyesen kiexponálni a sötét részeket és a nagyon világos fénycsíkokat - a lágy fényű kék órában jobb eséllyel lesz kiégés- és bebukásmentes a fotó. Ennél a képnél a zúzmarás fák alkonyati kékes derengése szolgáltatja a hátteret a féklámpa csíkjának.</p>
        <p>Persze ez nem törvényszerű, az alábbi képnél kimondottan a rideg sötétségre törekedtem, amelyet melegen roncsol szét az elhaladó taxi meleg fénye. A hepehupás úttest megugrasztotta a kocsit, ezáltal girbegurba lett a fénycsík is.</p>
        <SimpleFigure fileName="6745047_7ee9d0aa4007a32c7ff7879366a87cd7_m.jpg" altText="Réka: Hazafelé"/>
        <p>Alap esetben azt szeretném, hogy a járművek lámpái elmosódjanak, a környezet azonban maradjon éles - ehhez állványra lesz szükség, hiszen a záridő 5-30 másodperc körül fog alakulni. Fénycsíkos kép minden olyan géppel készíthető - kompakttal is-, amely állványra rögzíthető (a csatlakozó ipari szabvány) és legalább 5-8 másodperces záridőre képes.</p>
        <p>Ha találtam egy alkalmas helyet, pl. egy utcát, amely S-kanyarban fekszik, egy mozgalmas teret vagy más, szimpatikus helyszínt, akkor rögzítem az állványt, rajta a géppel és megkomponálom a fotót. Lehetőleg úgy kell helyezkednem, hogy az autók ne oldalról suhanjanak el mellettem, hanem kissé srégen, mögülem kerüljenek a képbe. Ha ugyanis oldalról fotózok mondjuk egy utcát, akkor csak a kocsik oldalsó indexfényét fogom rögzíteni és nagyon halvány fénycsíkot fogok kapni. Ezért jó hely mondjuk egy S-kanyar vagy egy tér közepe, mert akkor szemből-hátról jönnek a kocsik és így látványos fotó lesz a fényszórókból, hátsó fényekből. Akár felülnézetből is lehet fotózni, ezt a képet a buszpályaudvar felett állva készítettem a ki-beálló autóbuszokról.</p>
        <SimpleFigure fileName="6808081_770fcbb59c379015aa41ea935f34ea04_l.jpg" altText="Réka: Slussen"/>
        <p>Miután sikeresen beálltam (mármint a megfelelő helyre!), elkezdhetek gondolkodni a záridőn. Célszerű a záridőt úgy igazítani, hogy az elhaladó autó kb az expo kezdetekor haladjon be a képkockába, és az expo végén haladjon ki belőle. Ha az exponálás túl rövid a kocsi sebességéhez képest, akkor csak a kép közepén lesz egy rövid fénycsík - ha viszont túl hosszú ideig exponálok, akkor a kocsi fénye csak egy halovány csíkként fog megjelenni. Ha a kocsi mondjuk 5 másodperc alatt halad át a keresőnkön, akkor 5-6 másodperces záridő az ideális - ha viszont cammog, és csak 30 másodperc alatt mászik át a képkockán, akkor 30 másodperc körüli záridő lesz a jó ahhoz, hogy jó látványosan, a képkockát kitöltve jelenjen meg a fényszóró vagy a helyzetjelző fénye.</p>
        <p>A tükrös gépesek, távkioldóval rendelkezők ehhez használhatják a B záridőt is, ez a legegyszerűbb - amint a kocsi belesuhan a képkockába, akkor exponálás kezd, ha meg kihaladt belőle, akkor exponálás megszakít. Nyilván ehhez kell majd igazítani a rekeszt és az ISOt is, hogy korrekt expo értékeket kapjunk.</p>
        <p>De kompakttal is be lehet lőni, hogy mekkora záridőre lehet szükség, egyszerűen meg kell figyelni néhány kocsit és lőni pár próbafelvételt, no meg remélni, hogy a következő autó betartja a sebességkorlátot és nem mondjuk 30 helyett 120-al húz el a gép előtt, mert akkor semmi nem fog látszani belőle. Téli estéken ez a tesztelgetés csak kesztyűben megoldható, előre szólok! :) azonban a tél azért is alkalmas erre a műfajra, mert mivel korán sötétedik, nem kell későig kint lenni a fotós cuccal, hanem vacsorára már otthon lehetünk a zsákmánnyal, munka után is megoldható egy-egy gyors fotózás.</p>
        <p>Bár az állvány szinte elengedhetetlen kelléke a fénycsíkfotózásnak, néha nem árt levenni a gépet és csak úgy meglengetni a levegőben exponálás közben, ki tudja, mi sül ki belőle. Egy számomra kedves képem Budapestről pont így készült, akár egy átmulatott éjszaka után való hazatérést is ábrázolhatna.</p>
        <SimpleFigure fileName="7421551_2a255fb98ef159febc352d8514d8453c_m.jpg" altText="Réka: Vision of Love"/>
        <p>További tippek: ki lehet próbálni a fekete-fehér változatot is, elegáns hangulatot kölcsönöz a fotónak.</p>
        <p>Vagy hosszú záridő helyett épp egy szokásosnál kicsivel hosszabbat, hogy épp mozduljon be a téma: mozgalmas, dinamikus végeredményt kapunk.</p>
        <p>Az alábbi fotó pedig kompakttal készült, zuhogó esőben tartottam hazafelé és megláttam a vizesen fénylő, tükröződő aszfaltban rejlő lehetőségeket. A gépet egy trafódobozra raktam, a kabátról lecsatolt csuklyámat tartottam felé és imádkoztam, hogy jöjjön egy autó, mielőtt az egész várost elnyeli az özönvíz.</p>
        <SimpleFigure fileName="jhov.jpg" altText="Illusztráció"/>
    </>;
}
