// frontend/src/materials/third-party-content/hu/sg-makrofotozas-1.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'sg-makrofotozas-1',
            title: 'Makrofotózás I.',
            author: 'Gábor Zoltán',
            publishDate: new Date('2006-05-08'),
            publisherName: 'Sg.hu',
            originalUrl: 'https://sg.hu/cikkek/it-tech/44392/hogyan-fotozzunk-makrofotozas-i',
            isOriginalUrlBroken: false,
        }
    }
</script>

<script lang="ts">
    import TwoEnlargeableFigures from '../../components/TwoEnlargeableFigures.svelte'
</script>

<p>A makrofotózással olyan világot tudunk bemutatni, amit pusztán a szemünkkel nem láthatunk ennyire részletesen.</p>
<p>
    A makrofotózás a természetfotózás egyik legkedveltebb válfaja. Sokakat vonz ez a világ, hiszen a fényképezőgéppel és
    egy erre alkalmas objektívvel olyan világot tudunk bemutatni, amit pusztán a szemünkkel nem láthatunk ennyire
    részletesen. A digitális kompakt fényképezőgépek az idők során egyre komolyabb közelfényképezésre adtak lehetőséget,
    relatíve olcsó áron, így a hétköznapi fotós is kipróbálhatja magát ezen a téren, de nem árt, ha tisztában vagyunk a
    lehetőségeinkkel és a buktatókkal.
</p>
<h2>Makrózás kompakt géppel</h2>
<p>
    Ha makrofényképezésre adjuk a fejünket, legyünk tisztában gépünk lehetőségeivel ezen a fronton. Egyik lényeges
    tényező az objektívünk legközelebbi fókuszpontja. Ez az érték jelöli, hogy gépünk érzékelőjétől (tehát nem az
    objektív frontlencséjétől!) milyen messze lévő tárgyra képes gépünk ráfókuszálni, azaz a helyes élességet
    beállítani. Ez az érték mostanság egyre kisebb (általában 2-10 cm), azaz a gyártók olyan objektívekkel szerelik a
    gépeket, amikkel akár közvetlenül az objektívünk frontlencséjénél lévő tárgyról is éles felvételt készíthetünk.
</p>
<p>
    Nemcsak a kompakt masinák, de már a belépőszintű DSLR gépek is rendelkeznek makro üzemmóddal, amit rendre egy kis
    virággal jelölnek a módtárcsákon vagy a menüben. A kompakt gépeknél gyakorlati haszna is van ennek a módnak, a DSLR
    masinákon különösebben nem vesszük hasznát. A kompakt gépek objektívjei csak ebben az állásban képesek a közeli
    témákra fókuszálni, azaz a fókusztávolság ebben az állásban rövidül le a makrózáshoz használható mértékűre.
</p>
<TwoEnlargeableFigures
    thumbnailFileName1="0504_makro1_200.jpg"
    fileName1="0504_makro1.jpg"
    altText1="Makró 1"
    caption1="Kompakt géppel és makró előtétlencsével készült felvétel"
    thumbnailFileName2="0504_makro2_200.jpg"
    fileName2="0504_makro2.jpg"
    altText2="Makró 2"
    caption2="Kompakt géppel és makró előtétlencsével készült felvétel"
/>
<p>
    A kompaktok jelentős része nem csupán egyféle makró üzemmódot ismer, előfordul kétféle makro állás is a gépeken. Az
    egyik üzemmód a sima mezei makró mód, ilyenkor az objektív teljes zoomtartományát használhatjuk. A másik üzemmód az
    úgynevezett szuper makró mód. Ilyenkor az objektívet csak nagy látószögű állásban használhatjuk (tehát nem
    zoomolhatunk), és általában jóval közelebbi témákra élesíthetünk rá (ilyenkor lehetséges pl. egyes gépeknél az 1
    cm-es fókusztáv használata). Ilyenkor tehát elég komoly nagyítást érhetünk el, ráadásul fényerőnk is van elég, azaz
    akár rekeszelhetünk is. A dolog hátulütője, hogy nagylátó állásban az objektívek torzítanak, tehát nem a valós képet
    vetítik az érzékelőre (ez természetesen nem minden esetben jelent hátrányt, sokszor nagyon érdekes hatást érhetünk
    el). Továbbá ebben az állásban a hátterünk kevésbé lesz elmosva mintha tele állásában fotóznák, azaz a témánk
    kevésbé fog kiemelkedni az életlen háttérből.
</p>
<p>
    Egyes ultrazoom gépek érzékelik, ha makró módban a zoomtartomány végén fotózunk (telemakro mód), és ehhez
    kalibrálják a beállításokat. Sajnos sok gépnél előfordul, hogy a makró módban nem szólhatunk be a képrögzítés egyéb
    tulajdonságaiba, tehát nem állíthatunk sem az ISO érzékenységen, sem a fehéregyensúlyon vagy egyéb értékeken. Az
    objektív viszont csak makró állásban képes a közeli fókusztartományt használni, így mindenképpen makró módban kell
    fotóznunk, manuális módban nem vagyunk kinn a vízből.
</p>
<h2>Beállítások</h2>
<p>
    Ha tehetjük, fotózzunk tele állásban. Ez sajnos fényerővesztéssel jár és gépünk nehezebben fog fókuszálni, viszont
    témáink nem lesznek torzítottak és a háttér is remekül el lesz mosva. Amennyiben módunkban áll egyéb beállításokat
    is végezni a gépen, mindenképpen tegyük ezt meg. Az érzékenységet állítsuk a legalacsonyabb értékre, vagy esetleg
    egy értékkel emeljük meg (ISO100-ISO200). A fénymérést állítsuk középre súlyozottra vagy spotmérésre. Mivel témáink
    elég aprók, így lényeges, hogy leginkább a rájuk eső fényt mérje a gép, és ne egy átlagolt értéket számítson (de ez
    erősen témafüggő).
</p>
<p>
    Amennyiben elég fényünk van és a természetben vagyunk, kapcsoljuk ki a beépített vakut. Nem túl szép, ha a
    természetes megvilágítást hideg, mesterséges fénnyel nyomjuk el. Természetesen egy árnyékos rész derítésére
    használhatjuk a vakut, de csak módjával, és ha lehet, ne direktben (bár erre a legtöbb kompakt gépnél nincs
    lehetőség, csak direkt vakuzásra). Használjunk inkább egy nagyobb fehér lapot a témáink derítéséhez.
</p>
<TwoEnlargeableFigures
    thumbnailFileName1="0504_makro3_200.jpg"
    fileName1="0504_makro3.jpg"
    altText1="Makró 3"
    caption1="Kompakt géppel és makró előtétlencsével készült felvétel"
    thumbnailFileName2="0504_makro4_200.jpg"
    fileName2="0504_makro4.jpg"
    altText2="Makró 4"
    caption2="Kompakt géppel és makró előtétlencsével készült felvétel"
/>
<p>
    Nagyon fontos dolog a fókusz helyes használata! A kompakt masinák autófókusza elég lassúcska és pontatlan ilyen
    helyzetekben. Természetesen próbálkozhatunk autofókusszal, de hamar rá fogunk jönni, hogy nem ez az üdvözült
    megoldás. Amennyiben gépünkön van lehetőség manuális fókuszállásra, használjuk inkább azt! A legcélszerűbb megoldás,
    ha egyből a legközelebbi fókuszponthoz tekerjük (állítjuk) a fókuszt. Ezután nem a gépünkkel fókuszálunk, hanem a
    saját testünk előre-hátra mozgásával állíthatjuk be a helyes élességet. Ha lehetőségünk van és a téma is megkívánja,
    addig közelítsünk, amíg az éles nem lesz, így készíthetjük a legnagyobb nagyítású fotót a témánkról. Amennyiben túl
    közel vagyunk, témánk kilóg a keresőből, akkor távolodva álljunk meg a megfelelő távolságnál, és a fókuszt állítsuk
    hozzá a beállításhoz.
</p>
<p>
    Természetesen a makrofotózásnál is lényeges a helyes záridő használata, ami a témák többségénél minél rövidebb,
    annál jobb. Ha elég fény áll rendelkezésünkre, ha elég rövid záridőt tudunk használni, akkor lehetőségünk van az
    objektív lerekeszelésére. Ez a kompakt gépek esetében nem olyan lényeges, hiszen az apró képérzékelő miatt a kompakt
    masinák objektívjei jóval nagyobb mélységélességgel bírnak a cserélhető objektívekkel szemben. Extrém nagyításoknál
    a kompakt gépekkel is előfordulhat azonban, hogy lerekeszeléssel elérhető plusz mélységélességre lesz szükségünk.
    Ráadásul az minden objektívre igaz, hogy közepes rekesznél rajzolják a legrészletesebb képet, így, ha tehetjük,
    érdemes közepes rekeszértéket használni a makrofotózásnál is.
</p>
<TwoEnlargeableFigures
    thumbnailFileName1="0504_makro5_200.jpg"
    fileName1="0504_makro5.jpg"
    altText1="Makró 5"
    caption1="Kompakt géppel készült felvétel"
    thumbnailFileName2="0504_makro6_200.jpg"
    fileName2="0504_makro6.jpg"
    altText2="Makró 6"
    caption2="Kompakt géppel készült felvétel"
/>
<p>
    A kompakt gépek makroképességét előtétlencsékkel komolyan megnövelhetjük. Ez azonban - mint minden más -
    kompromisszumokkal jár: az előtétlencsék sajnos rontják a képminőséget. Az olcsóbb márkák jelentősen, a márkásabbak
    kevésbé, de mindenképpen rontanak kicsit, ráadásul kis mértékben még az objektívünk fényerejét is csökkentik.
    Segítségükkel azonban igazán látványos makrofotókat készíthetünk, főleg akkor, ha gépünk alaphelyzetben remek
    makroképességekkel rendelkezik.
</p>
<p>
    Fontos megjegyeznem még, hogy minden, a képminőségre valamit is adó fotós (még ha kezdő is) jobban jár, ha állványt
    vásárol a makrofényképezéshez. Vannak direkt ilyen célra készített apró makroállványok is, melyekkel a földközeli
    témák megörökítése lehetséges, de egy hétköznapi fotóállvánnyal is dolgozhatunk. Az eredmény meghálálja a
    befektetett pénzt és fáradtságot. Aki komolyabban szeretne a makrofényképezésben elmerülni, de nem tud vagy nem akar
    DSLR gépet vásárolni, annak ajánlom a kihajtható, forgatható LCD kijelzővel felszerelt kompakt gépeket, hiszen ezek
    jelentősen megkönnyítik a makrofényképezést.
</p>

// frontend/src/materials/third-party-content/hu/sg-makrofotozas-1.jsx
import React from 'react';
import TwoEnlargeableFigures from '../../components/TwoEnlargeableFigures.jsx';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'sg-makrofotozas-1',
        title: 'Makrofotózás I.',
        author: 'Gábor Zoltán',
        publishDate: new Date('2006-05-08'),
        publisherName: 'Sg.hu',
        originalUrl: 'https://sg.hu/cikkek/it-tech/44392/hogyan-fotozzunk-makrofotozas-i',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <p>A makrofotózással olyan világot tudunk bemutatni, amit pusztán a szemünkkel nem láthatunk ennyire részletesen.</p>
        <p>A makrofotózás a természetfotózás egyik legkedveltebb válfaja. Sokakat vonz ez a világ, hiszen a fényképezőgéppel és egy erre alkalmas objektívvel olyan világot tudunk bemutatni, amit pusztán a szemünkkel nem láthatunk ennyire részletesen. A digitális kompakt fényképezőgépek az idők során egyre komolyabb közelfényképezésre adtak lehetőséget, relatíve olcsó áron, így a hétköznapi fotós is kipróbálhatja magát ezen a téren, de nem árt, ha tisztában vagyunk a lehetőségeinkkel és a buktatókkal.</p>
        <h2>Makrózás kompakt géppel</h2>
        <p>Ha makrofényképezésre adjuk a fejünket, legyünk tisztában gépünk lehetőségeivel ezen a fronton. Egyik lényeges tényező az objektívünk legközelebbi fókuszpontja. Ez az érték jelöli, hogy gépünk érzékelőjétől (tehát nem az objektív frontlencséjétől!) milyen messze lévő tárgyra képes gépünk ráfókuszálni, azaz a helyes élességet beállítani. Ez az érték mostanság egyre kisebb (általában 2-10 cm), azaz a gyártók olyan objektívekkel szerelik a gépeket, amikkel akár közvetlenül az objektívünk frontlencséjénél lévő tárgyról is éles felvételt készíthetünk.</p>
        <p>Nemcsak a kompakt masinák, de már a belépőszintű DSLR gépek is rendelkeznek makro üzemmóddal, amit rendre egy kis virággal jelölnek a módtárcsákon vagy a menüben. A kompakt gépeknél gyakorlati haszna is van ennek a módnak, a DSLR masinákon különösebben nem vesszük hasznát. A kompakt gépek objektívjei csak ebben az állásban képesek a közeli témákra fókuszálni, azaz a fókusztávolság ebben az állásban rövidül le a makrózáshoz használható mértékűre.</p>
        <TwoEnlargeableFigures thumbnailFileName1="0504_makro1_200.jpg" fileName1="0504_makro1.jpg" altText1="Makró 1" caption1="Kompakt géppel és makró előtétlencsével készült felvétel" thumbnailFileName2="0504_makro2_200.jpg" fileName2="0504_makro2.jpg" altText2="Makró 2" caption2="Kompakt géppel és makró előtétlencsével készült felvétel"/>
        <p>A kompaktok jelentős része nem csupán egyféle makró üzemmódot ismer, előfordul kétféle makro állás is a gépeken. Az egyik üzemmód a sima mezei makró mód, ilyenkor az objektív teljes zoomtartományát használhatjuk. A másik üzemmód az úgynevezett szuper makró mód. Ilyenkor az objektívet csak nagy látószögű állásban használhatjuk (tehát nem zoomolhatunk), és általában jóval közelebbi témákra élesíthetünk rá (ilyenkor lehetséges pl. egyes gépeknél az 1 cm-es fókusztáv használata). Ilyenkor tehát elég komoly nagyítást érhetünk el, ráadásul fényerőnk is van elég, azaz akár rekeszelhetünk is. A dolog hátulütője, hogy nagylátó állásban az objektívek torzítanak, tehát nem a valós képet vetítik az érzékelőre (ez természetesen nem minden esetben jelent hátrányt, sokszor nagyon érdekes hatást érhetünk el). Továbbá ebben az állásban a hátterünk kevésbé lesz elmosva mintha tele állásában fotóznák, azaz a témánk kevésbé fog kiemelkedni az életlen háttérből.</p>
        <p>Egyes ultrazoom gépek érzékelik, ha makró módban a zoomtartomány végén fotózunk (telemakro mód), és ehhez kalibrálják a beállításokat. Sajnos sok gépnél előfordul, hogy a makró módban nem szólhatunk be a képrögzítés egyéb tulajdonságaiba, tehát nem állíthatunk sem az ISO érzékenységen, sem a fehéregyensúlyon vagy egyéb értékeken. Az objektív viszont csak makró állásban képes a közeli fókusztartományt használni, így mindenképpen makró módban kell fotóznunk, manuális módban nem vagyunk kinn a vízből.</p>
        <h2>Beállítások</h2>
        <p>Ha tehetjük, fotózzunk tele állásban. Ez sajnos fényerővesztéssel jár és gépünk nehezebben fog fókuszálni, viszont témáink nem lesznek torzítottak és a háttér is remekül el lesz mosva. Amennyiben módunkban áll egyéb beállításokat is végezni a gépen, mindenképpen tegyük ezt meg. Az érzékenységet állítsuk a legalacsonyabb értékre, vagy esetleg egy értékkel emeljük meg (ISO100-ISO200). A fénymérést állítsuk középre súlyozottra vagy spotmérésre. Mivel témáink elég aprók, így lényeges, hogy leginkább a rájuk eső fényt mérje a gép, és ne egy átlagolt értéket számítson (de ez erősen témafüggő).</p>
        <p>Amennyiben elég fényünk van és a természetben vagyunk, kapcsoljuk ki a beépített vakut. Nem túl szép, ha a természetes megvilágítást hideg, mesterséges fénnyel nyomjuk el. Természetesen egy árnyékos rész derítésére használhatjuk a vakut, de csak módjával, és ha lehet, ne direktben (bár erre a legtöbb kompakt gépnél nincs lehetőség, csak direkt vakuzásra). Használjunk inkább egy nagyobb fehér lapot a témáink derítéséhez.</p>
        <TwoEnlargeableFigures thumbnailFileName1="0504_makro3_200.jpg" fileName1="0504_makro3.jpg" altText1="Makró 3" caption1="Kompakt géppel és makró előtétlencsével készült felvétel" thumbnailFileName2="0504_makro4_200.jpg" fileName2="0504_makro4.jpg" altText2="Makró 4" caption2="Kompakt géppel és makró előtétlencsével készült felvétel"/>
        <p>Nagyon fontos dolog a fókusz helyes használata! A kompakt masinák autófókusza elég lassúcska és pontatlan ilyen helyzetekben. Természetesen próbálkozhatunk autofókusszal, de hamar rá fogunk jönni, hogy nem ez az üdvözült megoldás. Amennyiben gépünkön van lehetőség manuális fókuszállásra, használjuk inkább azt! A legcélszerűbb megoldás, ha egyből a legközelebbi fókuszponthoz tekerjük (állítjuk) a fókuszt. Ezután nem a gépünkkel fókuszálunk, hanem a saját testünk előre-hátra mozgásával állíthatjuk be a helyes élességet. Ha lehetőségünk van és a téma is megkívánja, addig közelítsünk, amíg az éles nem lesz, így készíthetjük a legnagyobb nagyítású fotót a témánkról. Amennyiben túl közel vagyunk, témánk kilóg a keresőből, akkor távolodva álljunk meg a megfelelő távolságnál, és a fókuszt állítsuk hozzá a beállításhoz.</p>
        <p>Természetesen a makrofotózásnál is lényeges a helyes záridő használata, ami a témák többségénél minél rövidebb, annál jobb. Ha elég fény áll rendelkezésünkre, ha elég rövid záridőt tudunk használni, akkor lehetőségünk van az objektív lerekeszelésére. Ez a kompakt gépek esetében nem olyan lényeges, hiszen az apró képérzékelő miatt a kompakt masinák objektívjei jóval nagyobb mélységélességgel bírnak a cserélhető objektívekkel szemben. Extrém nagyításoknál a kompakt gépekkel is előfordulhat azonban, hogy lerekeszeléssel elérhető plusz mélységélességre lesz szükségünk. Ráadásul az minden objektívre igaz, hogy közepes rekesznél rajzolják a legrészletesebb képet, így, ha tehetjük, érdemes közepes rekeszértéket használni a makrofotózásnál is.</p>
        <TwoEnlargeableFigures thumbnailFileName1="0504_makro5_200.jpg" fileName1="0504_makro5.jpg" altText1="Makró 5" caption1="Kompakt géppel készült felvétel" thumbnailFileName2="0504_makro6_200.jpg" fileName2="0504_makro6.jpg" altText2="Makró 6" caption2="Kompakt géppel készült felvétel"/>
        <p>A kompakt gépek makroképességét előtétlencsékkel komolyan megnövelhetjük. Ez azonban - mint minden más - kompromisszumokkal jár: az előtétlencsék sajnos rontják a képminőséget. Az olcsóbb márkák jelentősen, a márkásabbak kevésbé, de mindenképpen rontanak kicsit, ráadásul kis mértékben még az objektívünk fényerejét is csökkentik. Segítségükkel azonban igazán látványos makrofotókat készíthetünk, főleg akkor, ha gépünk alaphelyzetben remek makroképességekkel rendelkezik.</p>
        <p>Fontos megjegyeznem még, hogy minden, a képminőségre valamit is adó fotós (még ha kezdő is) jobban jár, ha állványt vásárol a makrofényképezéshez. Vannak direkt ilyen célra készített apró makroállványok is, melyekkel a földközeli témák megörökítése lehetséges, de egy hétköznapi fotóállvánnyal is dolgozhatunk. Az eredmény meghálálja a befektetett pénzt és fáradtságot. Aki komolyabban szeretne a makrofényképezésben elmerülni, de nem tud vagy nem akar DSLR gépet vásárolni, annak ajánlom a kihajtható, forgatható LCD kijelzővel felszerelt kompakt gépeket, hiszen ezek jelentősen megkönnyítik a makrofényképezést.</p>
    </>;
}
