// frontend/src/materials/third-party-content/hu/sg-makrofotozas-2.tsx
import React from 'react';
import TwoEnlargeableFigures from '../../components/TwoEnlargeableFigures';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'sg-makrofotozas-2',
        title: 'Makrofotózás II.',
        author: 'Gábor Zoltán',
        publishDate: new Date('2006-05-15'),
        publisherName: 'Sg.hu',
        originalUrl: 'https://sg.hu/cikkek/44443/hogyan_fotozzunk_makrofotozas_ii',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <p>Makrofotózási ismertetőnk második részében a DSLR gépeknél ajánlott beállításokat vesszük sorra és néhány tanáccsal is szolgálunk.</p>
        <h2>Makrózás DSLR géppel</h2>
        <p>Digitális tükörreflexes gépünkkel kissé költséges dolog lesz a közelfényképezés, hiszen a makrózni képes objektívek elég drágák. Léteznek makrózni is képes általános célú zoomobjektívek, illetve direkt erre a célra készített fix objektívek (de természetesen másra is használhatjuk őket). DSLR géppel és makroobjektívvel jóval szabadabban mozoghatunk. Az ISO érzékenységet akár ISO400-on vagy efelett is használhatjuk. Az autofókusz nyilván sokkal gyorsabb és pontosabb a kompakt gépeknél, így tehetünk pár próbát vele, de biztosra manuális fókuszálással megyünk. A legcélszerűbb manuális módban beállítani a rekeszt a legalkalmasabb értékre, és a fénymérést segítségül véve a záridőt állítsuk hozzá. Ha a záridő túl hosszúnak tűnik, emeljünk az érzékenységen. Állvány és derítőlap használata itt is ajánlott.</p>
        <TwoEnlargeableFigures thumbnailFileName1="0504_makro7_200.jpg" fileName1="0504_makro7.jpg" altText1="Makró 7" caption1="Digitális tükörreflexes géppel és fordított objektívvel készült felvétel" thumbnailFileName2="0504_makro8_200.jpg" fileName2="0504_makro8.jpg" altText2="Makró 8" caption2="Digitális tükörreflexes géppel és fordított objektívvel készült felvétel"/>
        <p>A makroobjektíveknél az objektív makroképességét az úgynevezett leképezési aránnyal adják meg, például így: 1:1. Ez azt jelenti, hogy egy 36 x 24 mm-es képérzékelőt (vagy filmkockát) teljes egészében egy 36 x 24 mm-es téglalap fog kitölteni. Tehát az adott makroobjektívvel (1:1-es leképezésnél) egy 36 x 24 mm-es területet leszünk képesek élesen befogni. Az olyan objektívek, amik csak 1:2-es leképezésre képesek, nyilván kétszer nagyobb tárgyra képesek csak élesíteni és így tovább (1:4, 1:5 stb.).</p>
        <p>Elég sok objektívet választhatunk céljaink megvalósításához. Találunk makroképességgel felruházott alap zoomobjektívet, de használhatunk makrózáshoz egy 300 mm-es teleobjektívet is, ami képes rövid távolságra fókuszálni. De a legjobb megoldás a fix makroobjektív lesz. Választhatunk 50, 100, 150 és akár 180 mm-es gyújtótávolságú objektívet, a nagyítás-képminőség páros ezekkel a szerkezetekkel lesz a legjobb.</p>
        <TwoEnlargeableFigures thumbnailFileName1="0504_makro9_200.jpg" fileName1="0504_makro9.jpg" altText1="Makró 9" caption1="Digitális tükörreflexes géppel és fordított objektívvel készült felvétel" thumbnailFileName2="0504_makro10_200.jpg" fileName2="0504_makro10.jpg" altText2="Makró 10" caption2="Digitális tükörreflexes géppel és fordított objektívvel készült felvétel"/>
        <p>Haladó fotósok egy fordítógyűrű segítségével akár fordítva is felcsavarhatják általános célú objektívjüket, ezzel pedig igazán extrém mértékű nagyításokat érhetnek el, manuális fókusz és nem működő fénymérés mellett (de ezek működtetéséhez is vannak barkács megoldások). Akinek nincs pénze drága makroobjektívre, de van egy jó minőségű általános célú fix objektívje (vagy akár makroobjektívje), az egy úgynevezett közgyűrűsorral makroképességekkel ruházhatja fel objektívjét. Akiknek fontos az AF és a fénymérés használata, azok ilyet válasszanak gépük és az objektív közé.</p>
        <h2>Általános tanácsok</h2>
        <p>Tanuljuk meg, hogy makrofotózásnál a mélységélesség nagyon lerövidül. Kompaktosok előnyben vannak a DSLR vázakkal szemben, hiszen a kompaktoknál azonos rekeszértéknél jóval nagyobb a mélységélesség, de még így is elég kicsi lesz. Komolyabb makroobjektíveknél a mélységélesség csupán pár centiméterre csökken. Ha fordítva helyezzük fel az objektívet a vázra, a mélységélesség csak pár milliméteres lesz, így ilyen esetekben van a legnehezebb dolgunk. Ha komoly nagyítású felvételt készítünk a természetben, akkor megyünk biztosra, ha sorozatfelvételi módban fényképezünk. Ilyenkor a témák és a saját mozgásunk miatt elcsúszhat, rossz helyre kerülhet a fókusz, tehát jobb, ha egyből több képet készítünk, hátha az egyiken helyes lesz a fókuszpont. Állvány használata erősen javallott!</p>
        <TwoEnlargeableFigures thumbnailFileName1="0504_makro11_200.jpg" fileName1="0504_makro11.jpg" altText1="Makró 11" caption1="Digitális tükörreflexes géppel készült felvétel" thumbnailFileName2="0504_makro12_200.jpg" fileName2="0504_makro12.jpg" altText2="Makró 12" caption2="Digitális tükörreflexes géppel készült felvétel"/>
        <p>Próbáljuk meg témáinkat nem mindig középre komponálni. Előfordulhat, hogy jobb kompozíció születik, ha többet mutatunk az elmosódott háttérből (figyeljünk az aranymetszésre). Rovarok fotózásánál próbáljunk tele állásban fotózni, hiszen a legtöbb rovar nem engedi túl közel magához a gépünket. A virágok, növények fényképezésénél is ügyeljünk az érdekesebb beállításra. Ne csupán egy fotót készítsünk az adott növényről, keressünk több, eredetibb nézőpontot.</p>
        <p>Rengeteg vágatlan, felesleges információt tartalmazó kép özönli el a világhálót, amiknek csupán egy kis százalékát foglalja el a fotótéma csupán azért, mert lusták vagyunk megvágni fotóinkat. Igyekezzünk gépünk teljes felbontását kihasználni. Ne legyünk restek kisebbre szabni a képeket, hiszen a ma divatos 5-8 megapixeles képekből bőven van lehetőségünk vágni, ha esetleg a fotóalanyunkról nem tudtunk elég nagy fotót készíteni. Érdemes odafigyelni gépünk árnyékára is, ha lehet, ne takarjuk el a fényt a témáról az objektívünkkel.</p>
    </>;
}

// frontend/src/materials/third-party-content/hu/sg-makrofotozas-2.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'sg-makrofotozas-2',
            title: 'Makrofotózás II.',
            author: 'Gábor Zoltán',
            publishDate: new Date('2006-05-15'),
            publisherName: 'Sg.hu',
            originalUrl: 'https://sg.hu/cikkek/44443/hogyan_fotozzunk_makrofotozas_ii',
            isOriginalUrlBroken: false,
        };
    }
</script>

<script lang="ts">
    import TwoEnlargeableFigures from '../../components/TwoEnlargeableFigures.svelte';
</script>

<p>Makrofotózási ismertetőnk második részében a DSLR gépeknél ajánlott beállításokat vesszük sorra és néhány tanáccsal is szolgálunk.</p>
<h2>Makrózás DSLR géppel</h2>
<p>Digitális tükörreflexes gépünkkel kissé költséges dolog lesz a közelfényképezés, hiszen a makrózni képes objektívek elég drágák. Léteznek makrózni is képes általános célú zoomobjektívek, illetve direkt erre a célra készített fix objektívek (de természetesen másra is használhatjuk őket). DSLR géppel és makroobjektívvel jóval szabadabban mozoghatunk. Az ISO érzékenységet akár ISO400-on vagy efelett is használhatjuk. Az autofókusz nyilván sokkal gyorsabb és pontosabb a kompakt gépeknél, így tehetünk pár próbát vele, de biztosra manuális fókuszálással megyünk. A legcélszerűbb manuális módban beállítani a rekeszt a legalkalmasabb értékre, és a fénymérést segítségül véve a záridőt állítsuk hozzá. Ha a záridő túl hosszúnak tűnik, emeljünk az érzékenységen. Állvány és derítőlap használata itt is ajánlott.</p>
<TwoEnlargeableFigures thumbnailFileName1="0504_makro7_200.jpg" fileName1="0504_makro7.jpg" altText1="Makró 7" caption1="Digitális tükörreflexes géppel és fordított objektívvel készült felvétel" thumbnailFileName2="0504_makro8_200.jpg" fileName2="0504_makro8.jpg" altText2="Makró 8" caption2="Digitális tükörreflexes géppel és fordított objektívvel készült felvétel"/>
<p>A makroobjektíveknél az objektív makroképességét az úgynevezett leképezési aránnyal adják meg, például így: 1:1. Ez azt jelenti, hogy egy 36 x 24 mm-es képérzékelőt (vagy filmkockát) teljes egészében egy 36 x 24 mm-es téglalap fog kitölteni. Tehát az adott makroobjektívvel (1:1-es leképezésnél) egy 36 x 24 mm-es területet leszünk képesek élesen befogni. Az olyan objektívek, amik csak 1:2-es leképezésre képesek, nyilván kétszer nagyobb tárgyra képesek csak élesíteni és így tovább (1:4, 1:5 stb.).</p>
<p>Elég sok objektívet választhatunk céljaink megvalósításához. Találunk makroképességgel felruházott alap zoomobjektívet, de használhatunk makrózáshoz egy 300 mm-es teleobjektívet is, ami képes rövid távolságra fókuszálni. De a legjobb megoldás a fix makroobjektív lesz. Választhatunk 50, 100, 150 és akár 180 mm-es gyújtótávolságú objektívet, a nagyítás-képminőség páros ezekkel a szerkezetekkel lesz a legjobb.</p>
<TwoEnlargeableFigures thumbnailFileName1="0504_makro9_200.jpg" fileName1="0504_makro9.jpg" altText1="Makró 9" caption1="Digitális tükörreflexes géppel és fordított objektívvel készült felvétel" thumbnailFileName2="0504_makro10_200.jpg" fileName2="0504_makro10.jpg" altText2="Makró 10" caption2="Digitális tükörreflexes géppel és fordított objektívvel készült felvétel"/>
<p>Haladó fotósok egy fordítógyűrű segítségével akár fordítva is felcsavarhatják általános célú objektívjüket, ezzel pedig igazán extrém mértékű nagyításokat érhetnek el, manuális fókusz és nem működő fénymérés mellett (de ezek működtetéséhez is vannak barkács megoldások). Akinek nincs pénze drága makroobjektívre, de van egy jó minőségű általános célú fix objektívje (vagy akár makroobjektívje), az egy úgynevezett közgyűrűsorral makroképességekkel ruházhatja fel objektívjét. Akiknek fontos az AF és a fénymérés használata, azok ilyet válasszanak gépük és az objektív közé.</p>
<h2>Általános tanácsok</h2>
<p>Tanuljuk meg, hogy makrofotózásnál a mélységélesség nagyon lerövidül. Kompaktosok előnyben vannak a DSLR vázakkal szemben, hiszen a kompaktoknál azonos rekeszértéknél jóval nagyobb a mélységélesség, de még így is elég kicsi lesz. Komolyabb makroobjektíveknél a mélységélesség csupán pár centiméterre csökken. Ha fordítva helyezzük fel az objektívet a vázra, a mélységélesség csak pár milliméteres lesz, így ilyen esetekben van a legnehezebb dolgunk. Ha komoly nagyítású felvételt készítünk a természetben, akkor megyünk biztosra, ha sorozatfelvételi módban fényképezünk. Ilyenkor a témák és a saját mozgásunk miatt elcsúszhat, rossz helyre kerülhet a fókusz, tehát jobb, ha egyből több képet készítünk, hátha az egyiken helyes lesz a fókuszpont. Állvány használata erősen javallott!</p>
<TwoEnlargeableFigures thumbnailFileName1="0504_makro11_200.jpg" fileName1="0504_makro11.jpg" altText1="Makró 11" caption1="Digitális tükörreflexes géppel készült felvétel" thumbnailFileName2="0504_makro12_200.jpg" fileName2="0504_makro12.jpg" altText2="Makró 12" caption2="Digitális tükörreflexes géppel készült felvétel"/>
<p>Próbáljuk meg témáinkat nem mindig középre komponálni. Előfordulhat, hogy jobb kompozíció születik, ha többet mutatunk az elmosódott háttérből (figyeljünk az aranymetszésre). Rovarok fotózásánál próbáljunk tele állásban fotózni, hiszen a legtöbb rovar nem engedi túl közel magához a gépünket. A virágok, növények fényképezésénél is ügyeljünk az érdekesebb beállításra. Ne csupán egy fotót készítsünk az adott növényről, keressünk több, eredetibb nézőpontot.</p>
<p>Rengeteg vágatlan, felesleges információt tartalmazó kép özönli el a világhálót, amiknek csupán egy kis százalékát foglalja el a fotótéma csupán azért, mert lusták vagyunk megvágni fotóinkat. Igyekezzünk gépünk teljes felbontását kihasználni. Ne legyünk restek kisebbre szabni a képeket, hiszen a ma divatos 5-8 megapixeles képekből bőven van lehetőségünk vágni, ha esetleg a fotóalanyunkról nem tudtunk elég nagy fotót készíteni. Érdemes odafigyelni gépünk árnyékára is, ha lehet, ne takarjuk el a fényt a témáról az objektívünkkel.</p>
