// frontend/src/materials/third-party-content/hu/studioeszkozok-feheregyensuly-es-szinhomerseklet-a-digitalis-fotoknal.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'studioeszkozok-feheregyensuly-es-szinhomerseklet-a-digitalis-fotoknal',
            title: 'Fotózás alapok',
            author: 'Studioeszkozok.hu',
            publishDate: new Date('2018-03-15'),
            publisherName: 'studioeszkozok.hu',
            originalUrl: 'https://studioeszkozok.hu/feheregyensuly-es-szinhomerseklet-a-digitalis-fotoknal',
            isOriginalUrlBroken: false,
        };
    }
</script>

<script lang="ts">
    import FullWidthLocalImage from '../../../challenges/components/FullWidthLocalImage.svelte';
</script>

<FullWidthLocalImage fileName="studioeszkozok-feheregyensuly-es-szinhomerseklet-a-digitalis-fotoknal.png" altText="" />

// frontend/src/materials/third-party-content/hu/studioeszkozok-feheregyensuly-es-szinhomerseklet-a-digitalis-fotoknal.jsx
import React from 'react';
import FullWidthLocalImage from '../../../challenges/components/FullWidthLocalImage.jsx';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'studioeszkozok-feheregyensuly-es-szinhomerseklet-a-digitalis-fotoknal',
        title: 'Fotózás alapok',
        author: 'Studioeszkozok.hu',
        publishDate: new Date('2018-03-15'),
        publisherName: 'studioeszkozok.hu',
        originalUrl: 'https://studioeszkozok.hu/feheregyensuly-es-szinhomerseklet-a-digitalis-fotoknal',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <FullWidthLocalImage fileName="studioeszkozok-feheregyensuly-es-szinhomerseklet-a-digitalis-fotoknal.png" altText="" />
    </>;
}
