// frontend/src/materials/third-party-content/hu/tutsplus-10-tipp-a-csendelet-fotozas-elkezdesehez.tsx
import React from 'react';
import SimpleFigure from '../../components/SimpleFigure';

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {ArticleMetadata}
 */
export function getMetadata() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return {
        slug: 'tutsplus-10-tipp-a-csendelet-fotozas-elkezdesehez',
        title: '10 tipp a csendélet fotózás elkezdéséhez',
        author: 'Simon Bray',
        publishDate: new Date('2017-01-26'),
        publisherName: 'Tutsplus',
        originalUrl: 'https://photography.tutsplus.com/hu/tutorials/10-tips-to-get-started-with-still-life-photography--photo-8278',
        isOriginalUrlBroken: false,
    };
}

// noinspection JSUnusedGlobalSymbols (This file is loaded dynamically.)
/**
 * @returns {React.ReactElement}
 */
export default function Article() {
    // noinspection SpellCheckingInspection (It's in Hungarian.)
    return <>
        <p>Nem sok olyan fotográfiai gyakorlat létezik, amelyik régebbi a csendélet fotózásnál. A fényképészet megszületésekor egészen hosszú expozíciókra volt szükség, így a statikus tárgyak fényképezése volt az ideális téma. Ám a technológia fejlődésével a csendélet megragadása iránti csodálat megmaradt, és napjainkban még mindig az egyik legjárhatóbb fényképészeti szakma.</p>
        <p>A műfaj csúcsán ez egy rendkívül jövedelmező üzlet, hiszen a magazinoknak, katalógusoknak és honlapoknak mind szükségük van termékfotókra. A csendélet fotózásnak sok, gyakran alulértékelt előnye van, így remélhetőleg áttekinthető lesz számodra a kreativitási területe, és te magad is el fogsz kezdeni fotókat készíteni!</p>

        <h2>1. Az első lépések</h2>
        <p>A közvélekedéssel ellentétben, nincs szükséged stúdióra vagy divatos helyszínre ahhoz, hogy elkezdd a csendélet fotózást. Kezdheted egyszerűen egy otthoni tér kihasználásával, mint például egy ablak elé helyezett asztal, egy egyszerű háttérrel és néhány lámpa felhasználásával.</p>
        <p>Ez jelentősen eltér a tájkép vagy portré fotózástól, ahol rendelkezésedre áll a téma, például egy csodálatos hegyi táj vagy egy modell, amelyeknek rengeteg változójuk van, de a kreatív tartalom ott van előtted. A csendélet fotózás során sokkal kevesebb változó van, a szituáció teljes mértékben a te, vagyis a fotós ellenőrzése alatt áll, ide értve a témát is, de rendkívül kreatívan kell gondolkoznod ahhoz, hogy érdekes és vonzó módon ragadd meg mindezt.</p>
        <SimpleFigure fileName="1.jpg" altText="Illusztráció" caption="Fotó: apwizard"/>

        <h2>2. A témaválasztás</h2>
        <p>Teljes mértékben rajtad múlik az, hogy mit fotózol. Keresgélj a ház körül, keress valami egyszerű, de érdekes dolgot kezdetnek. Ne gondold, hogy gyümölcsöt és virágokat kell fotóznod csak azért, mert mindenki más ezt csinálja, gondolkodj a megszokottól eltérően, anélkül hogy túl erőltetett lennél.</p>
        <p>Ha kint vagy valahol, és valami megragadja a pillantásodat, vidd haza (ne lopd el!), vagy jegyezd fel, hogy majd ne felejtsd el megpróbálni lefotózni egy csendélet kontextusban. Az elején próbáld elkerülni a fényvisszaverő felületeket mint például az üveg és a fém, mivel ezeket rendkívül nehéz fotózni a világítás szempontjából. Miután elsajátítottad az egy objektumos felvételeket, próbáld keverni ezeket, kombinálni a kontrasztos alakú, színű és textúrájú tárgyakat, és nézd meg az eredményt.</p>
        <SimpleFigure fileName="2.jpg" altText="Illusztráció" caption="Fotó: whereisyourmind"/>

        <h2>3. A világítás</h2>
        <p>A világítás nem kell költséges legyen, a magam részéről biztosan tudom, hogy egy stúdiófény készlet nem igazán tartozik a költségvetésembe, így a csendélet fotózáshoz minden lehetséges fényt fel kell használnom. Tartsd eszedben, hogy a fotózás teljesen a te ellenőrzésed alatt áll, így ha akarod, akkor keress egy szobát, amelyben redőnyökkel és függönyökkel kizárhatod az összes természetes fényt, és így teljes mértékben te kontrollálod a témádra vetülő fényt.</p>
        <p>A hagyományos lámpák használata rendkívül jól működik, ha ezeket hatékonyan használják. Próbálj ki többféle helybeállítást, nem minden fénynek kell a tárgy elülső része felől érkeznie, az oldalsó és hátsó megvilágítás érdekességet, árnyékokat és mélységet ad a felvételnek. Egy másik alternatíva az, hogy válassz egy ablak révén jól megvilágított szobát, és használd ezt az előnyödre. Az egyik oldalról a természetes fény átfogóan megvilágítja a témádat, és te ezt kiegészítheted egy lámpával vagy egy reflektorral.</p>
        <SimpleFigure fileName="3.jpg" altText="Illusztráció" caption="Fotó: brtsergio"/>

        <h2>4. Állványok és kameraállás</h2>
        <p>A megvilágítási helyzettől függően előfordulhat, hogy nem kell állványt és exponálót használnod. Én javasolom neked ezek használatát, mivel lehetővé teszik, hogy megfigyeld és dolgozz a témáddal. Ez a beállítás lehetővé teszi, hogy a szokásosnál valamivel hosszabb záridőt használj a kis rekesznyílás biztosítása érdekében, ami lehetővé teszi a nagy mélységélességet, ha ezt szeretnéd.</p>
        <p>Azért ne engedd, hogy a statikus kamera elfojtsa a kreativitásodat, gyorsan el lehet felejteni, hogy a kamera ugyanabban a pozícióban volt az egész fotózás alatt. Ügyelj arra, hogy változtasd a fotózási szögeket és magasságokat. Ellenkező esetben, mielőtt észrevennéd, egy egész felvétel gyűjteményed lesz, amelyek mind ugyanabból a pontból készültek kevés variációval. Keverd meg egy kicsit a dolgokat. Próbálj a tárgy szintjéről fotózni, vagy próbáld ki a felülnézetet, lenézve a témádra, de vigyázz, hogyha körüljárod, hogy ne vonj árnyékot a tárgyra!</p>
        <SimpleFigure fileName="4.jpg" altText="Illusztráció" caption="Fotó: yjhsu"/>

        <h2>5. Válaszd meg jól a hátteret</h2>
        <p>A témádnak megfelelő háttér kulcsfontosságú szerepet fog játszani a felvételeid általános sikerében. A legjobb, ha szép és egyszerű, így nem fogja zavarni a témádat. Egy sima festett fal vagy egy nagy nagy fehér vagy sima színes papír ideális lenne.</p>
        <p>Gondold végig, hogy a háttér kiválasztása hogyan nyújt kontrasztot a témának, hogy egy semleges hátteret akarsz, vagy vannak-e olyan tónusok, amelyek a tárgyad árnyalatainak kiegészítéseként működhetnének. Kisebb tárgyak esetén előfordulhat, hogy nincs szükséged háttérre mint olyanra, hanem egy olyan felületre, amelyre ráhelyezheted az elemeket, amihez például a fekete bársony ideális, mert elnyeli a fényt és úgy néz ki, mint egy szilárd fekete felület.</p>
        <SimpleFigure fileName="5.jpg" altText="Illusztráció" caption="Fotó: darktechsystem"/>

        <h2>6. A kép megkomponálása</h2>
        <p>A csendélet kompozíciója kulcsfontosságú annak biztosításában, hogy a fotód vonzó és egyedi legyen. Vedd figyelembe a harmadolás szabályát, hogy hogyan használhatod ezt a fotóidnál egy erős kompozíciót létrehozása érdekében. Ügyelj arra, hogy ne legyenek zavaró hatások a kép keretén belül, csak a téma legyen és a háttér.</p>
        <p>Változtasd a témád kompozícióját a fotózás során, és gondolkodj a megszokottól eltérően. Hova vezeted a szemet a képen belül? Használsz negatív teret, vagy működhetne ez a keret kitöltésében? A témával kapcsolatban, milyen meghatározó jellemzői vannak ennek? Mire használható? Összefüggésbe hozhatod-e valamivel, vagy önálló témaként működik?</p>
        <SimpleFigure fileName="6.jpg" altText="Illusztráció" caption="Fotó: lindenbaum"/>

        <h2>7. Az egész nap a tiéd</h2>
        <p>Gyakran tapasztalom, hogy a fotózást övező gondolkodásmódom a fotózás okától függ. Így ha egyszerűen a fotózás öröméért vagy magamnak készítek fotókat (ellentétben egy megbízásra készülő munkával), akkor kevésbé leszek szigorú annak biztosításában, hogy a fotózás minden aspektusa a lehető legjobban legyen kivitelezve. Ez nyilvánvalóan egy rossz szokás, amelytől igyekszem megszabadulni, de ha csendélet fotózásról van szó, akkor nincs ok arra, hogy ne csináld jól. Annyi időd van, amennyire szükséged van egy jó munka elvégzéséhez!</p>
        <p>A tájkép fotózástól eltérően a fény nem változik gyorsan, a portrétól eltérően a témád nem fogja elunni magát a hosszú ideig tartó mozdulatlanságtól. Használd ki ezt a lehetőséget, állítsd be a témádat, a világítást, a hátteret és a kamerát, készíts néhány felvételt, majd mozdítsd el egy kicsit a dolgokat, és készíts újakat. Ha eljutsz egy olyan pontig, hogy úgy érzed, a dolgok nem mennek rendesen, akkor hagyj mindent beállítva, készíts magadnak egy csésze teát, és térj vissza hozzá később felfrissülve.</p>
        <p>Egy másik előny az, hogy nincs mentség arra, hogy nem tiszták és élesek a képek, szánj időt a világítás és a fókusz helyes megválasztására. Ha szert tudsz tenni rá, akkor egy makró objektív ideális lenne egy ilyen típusú munkához, de ha nem, akkor válaszd ki a makró módot a fényképezőgépeden, hogy a legjobb esélyed legyen a témád közeli részletének megragadására.</p>
        <SimpleFigure fileName="7.jpg" altText="Illusztráció" caption="Fotó: vamedia"/>

        <h2>8. A nagy mesterek ihletése</h2>
        <p>Ha küszködsz a világítással, a kompozícióval vagy a képeid felépítésével, akkor ihletet kell keresned, és hol máshol keress, mint az élmúlt évek eredeti csendélet remekeiben. Keress rá az interneten a reneszánsz csendélet művészeire, és figyeld meg a munkáik elemeit.</p>
        <p>Ezeknek a festményeknek a tanulmányozása segíteni fog neked a formák, az árnyékok megfigyelésében és a színek együttes működésének megértésében, és remélhetőleg adni fog néhány ötletet arra, hogy hogyan építsd fel a fotográfiai munkáidat úgy, hogy erős és érdekes képeket készíthess.</p>
        <SimpleFigure fileName="8.jpg" altText="Illusztráció" caption="Fotó: layos"/>

        <h2>9. Most rajtad a sor!</h2>
        <p>Eljött az ideje, hogy elkezdd. Keress a naptáradban egy csendes napot, és szánj időt a gyakorlásra. Próbáld beállítani a fényképezőgépedet és a hátteret egy megfelelő fényforráshoz közel egy ablak mellett, és kezdj el kattintgatni!</p>
        <p>Miután elsajátítottad az alapokat, próbálj kreatívabb lenni, kísérletezz a kameraállásokkal, a világítási szögekkel és alternatív fényforrásokkal, mint a gyertyák és lámpák. Megpróbálhatsz kreatívabb lenni a rekesznyílással is, és használj egy f/1.8-as elsődleges lencsét egy művészi sekély fókusz elérése érdekében. Ám ha egyetlen dolgot választasz ki ebből az oktatóleckéből, akkor az legyen ez: a csendélet fotózása nem a gyümölcsöket és a virágokat jelenti! Találj tehát egyedi és inspiráló témákat, amelyek lelkesedéssel töltenek el, és kezdj el kattintani!</p>
        <SimpleFigure fileName="9.jpg" altText="Illusztráció" caption="Fotó: apwizard"/>

        <h2>10. Megélhetés?</h2>
        <p>Nagyon sok igény van a csendélet fotózásra, különösen most, hogy a fotósok számára ennyire egyszerű képeket készíteni a stock fotó oldalak számára, amelyek elérhetőek a magazinok, üzleti kiadványok és online tartalmak számára. Miután elkészítetted a felvételeket, ne félj megosztani őket online, megpróbálhatod akár az Envato PhotoDune stock fotó oldalát. Így minden egyes alkalommal, amikor elkészítesz egy beállítást a fotózáshoz, dolgozz úgy mintha ez egy megbízás lenne, soha nem tudhatod, a csendéleted még pénzt is hozhat neked közben!</p>
        <SimpleFigure fileName="10.jpg" altText="Illusztráció" caption="Fotó: gfpeck"/>
    </>;
}

// frontend/src/materials/third-party-content/hu/tutsplus-10-tipp-a-csendelet-fotozas-elkezdesehez.svelte
<script module lang="ts">
    export function getMetadata() {
        // noinspection SpellCheckingInspection (It's in Hungarian.)
        return {
            slug: 'tutsplus-10-tipp-a-csendelet-fotozas-elkezdesehez',
            title: '10 tipp a csendélet fotózás elkezdéséhez',
            author: 'Simon Bray',
            publishDate: new Date('2017-01-26'),
            publisherName: 'Tutsplus',
            originalUrl: 'https://photography.tutsplus.com/hu/tutorials/10-tips-to-get-started-with-still-life-photography--photo-8278',
            isOriginalUrlBroken: false,
        };
    }
</script>

<script lang="ts">
    import SimpleFigure from '../../components/SimpleFigure.svelte';
</script>

<p>Nem sok olyan fotográfiai gyakorlat létezik, amelyik régebbi a csendélet fotózásnál. A fényképészet megszületésekor egészen hosszú expozíciókra volt szükség, így a statikus tárgyak fényképezése volt az ideális téma. Ám a technológia fejlődésével a csendélet megragadása iránti csodálat megmaradt, és napjainkban még mindig az egyik legjárhatóbb fényképészeti szakma.</p>
<p>A műfaj csúcsán ez egy rendkívül jövedelmező üzlet, hiszen a magazinoknak, katalógusoknak és honlapoknak mind szükségük van termékfotókra. A csendélet fotózásnak sok, gyakran alulértékelt előnye van, így remélhetőleg áttekinthető lesz számodra a kreativitási területe, és te magad is el fogsz kezdeni fotókat készíteni!</p>

<h2>1. Az első lépések</h2>
<p>A közvélekedéssel ellentétben, nincs szükséged stúdióra vagy divatos helyszínre ahhoz, hogy elkezdd a csendélet fotózást. Kezdheted egyszerűen egy otthoni tér kihasználásával, mint például egy ablak elé helyezett asztal, egy egyszerű háttérrel és néhány lámpa felhasználásával.</p>
<p>Ez jelentősen eltér a tájkép vagy portré fotózástól, ahol rendelkezésedre áll a téma, például egy csodálatos hegyi táj vagy egy modell, amelyeknek rengeteg változójuk van, de a kreatív tartalom ott van előtted. A csendélet fotózás során sokkal kevesebb változó van, a szituáció teljes mértékben a te, vagyis a fotós ellenőrzése alatt áll, ide értve a témát is, de rendkívül kreatívan kell gondolkoznod ahhoz, hogy érdekes és vonzó módon ragadd meg mindezt.</p>
<SimpleFigure fileName="1.jpg" altText="Illusztráció" caption="Fotó: apwizard"/>

<h2>2. A témaválasztás</h2>
<p>Teljes mértékben rajtad múlik az, hogy mit fotózol. Keresgélj a ház körül, keress valami egyszerű, de érdekes dolgot kezdetnek. Ne gondold, hogy gyümölcsöt és virágokat kell fotóznod csak azért, mert mindenki más ezt csinálja, gondolkodj a megszokottól eltérően, anélkül hogy túl erőltetett lennél.</p>
<p>Ha kint vagy valahol, és valami megragadja a pillantásodat, vidd haza (ne lopd el!), vagy jegyezd fel, hogy majd ne felejtsd el megpróbálni lefotózni egy csendélet kontextusban. Az elején próbáld elkerülni a fényvisszaverő felületeket mint például az üveg és a fém, mivel ezeket rendkívül nehéz fotózni a világítás szempontjából. Miután elsajátítottad az egy objektumos felvételeket, próbáld keverni ezeket, kombinálni a kontrasztos alakú, színű és textúrájú tárgyakat, és nézd meg az eredményt.</p>
<SimpleFigure fileName="2.jpg" altText="Illusztráció" caption="Fotó: whereisyourmind"/>

<h2>3. A világítás</h2>
<p>A világítás nem kell költséges legyen, a magam részéről biztosan tudom, hogy egy stúdiófény készlet nem igazán tartozik a költségvetésembe, így a csendélet fotózáshoz minden lehetséges fényt fel kell használnom. Tartsd eszedben, hogy a fotózás teljesen a te ellenőrzésed alatt áll, így ha akarod, akkor keress egy szobát, amelyben redőnyökkel és függönyökkel kizárhatod az összes természetes fényt, és így teljes mértékben te kontrollálod a témádra vetülő fényt.</p>
<p>A hagyományos lámpák használata rendkívül jól működik, ha ezeket hatékonyan használják. Próbálj ki többféle helybeállítást, nem minden fénynek kell a tárgy elülső része felől érkeznie, az oldalsó és hátsó megvilágítás érdekességet, árnyékokat és mélységet ad a felvételnek. Egy másik alternatíva az, hogy válassz egy ablak révén jól megvilágított szobát, és használd ezt az előnyödre. Az egyik oldalról a természetes fény átfogóan megvilágítja a témádat, és te ezt kiegészítheted egy lámpával vagy egy reflektorral.</p>
<SimpleFigure fileName="3.jpg" altText="Illusztráció" caption="Fotó: brtsergio"/>

<h2>4. Állványok és kameraállás</h2>
<p>A megvilágítási helyzettől függően előfordulhat, hogy nem kell állványt és exponálót használnod. Én javasolom neked ezek használatát, mivel lehetővé teszik, hogy megfigyeld és dolgozz a témáddal. Ez a beállítás lehetővé teszi, hogy a szokásosnál valamivel hosszabb záridőt használj a kis rekesznyílás biztosítása érdekében, ami lehetővé teszi a nagy mélységélességet, ha ezt szeretnéd.</p>
<p>Azért ne engedd, hogy a statikus kamera elfojtsa a kreativitásodat, gyorsan el lehet felejteni, hogy a kamera ugyanabban a pozícióban volt az egész fotózás alatt. Ügyelj arra, hogy változtasd a fotózási szögeket és magasságokat. Ellenkező esetben, mielőtt észrevennéd, egy egész felvétel gyűjteményed lesz, amelyek mind ugyanabból a pontból készültek kevés variációval. Keverd meg egy kicsit a dolgokat. Próbálj a tárgy szintjéről fotózni, vagy próbáld ki a felülnézetet, lenézve a témádra, de vigyázz, hogyha körüljárod, hogy ne vonj árnyékot a tárgyra!</p>
<SimpleFigure fileName="4.jpg" altText="Illusztráció" caption="Fotó: yjhsu"/>

<h2>5. Válaszd meg jól a hátteret</h2>
<p>A témádnak megfelelő háttér kulcsfontosságú szerepet fog játszani a felvételeid általános sikerében. A legjobb, ha szép és egyszerű, így nem fogja zavarni a témádat. Egy sima festett fal vagy egy nagy nagy fehér vagy sima színes papír ideális lenne.</p>
<p>Gondold végig, hogy a háttér kiválasztása hogyan nyújt kontrasztot a témának, hogy egy semleges hátteret akarsz, vagy vannak-e olyan tónusok, amelyek a tárgyad árnyalatainak kiegészítéseként működhetnének. Kisebb tárgyak esetén előfordulhat, hogy nincs szükséged háttérre mint olyanra, hanem egy olyan felületre, amelyre ráhelyezheted az elemeket, amihez például a fekete bársony ideális, mert elnyeli a fényt és úgy néz ki, mint egy szilárd fekete felület.</p>
<SimpleFigure fileName="5.jpg" altText="Illusztráció" caption="Fotó: darktechsystem"/>

<h2>6. A kép megkomponálása</h2>
<p>A csendélet kompozíciója kulcsfontosságú annak biztosításában, hogy a fotód vonzó és egyedi legyen. Vedd figyelembe a harmadolás szabályát, hogy hogyan használhatod ezt a fotóidnál egy erős kompozíciót létrehozása érdekében. Ügyelj arra, hogy ne legyenek zavaró hatások a kép keretén belül, csak a téma legyen és a háttér.</p>
<p>Változtasd a témád kompozícióját a fotózás során, és gondolkodj a megszokottól eltérően. Hova vezeted a szemet a képen belül? Használsz negatív teret, vagy működhetne ez a keret kitöltésében? A témával kapcsolatban, milyen meghatározó jellemzői vannak ennek? Mire használható? Összefüggésbe hozhatod-e valamivel, vagy önálló témaként működik?</p>
<SimpleFigure fileName="6.jpg" altText="Illusztráció" caption="Fotó: lindenbaum"/>

<h2>7. Az egész nap a tiéd</h2>
<p>Gyakran tapasztalom, hogy a fotózást övező gondolkodásmódom a fotózás okától függ. Így ha egyszerűen a fotózás öröméért vagy magamnak készítek fotókat (ellentétben egy megbízásra készülő munkával), akkor kevésbé leszek szigorú annak biztosításában, hogy a fotózás minden aspektusa a lehető legjobban legyen kivitelezve. Ez nyilvánvalóan egy rossz szokás, amelytől igyekszem megszabadulni, de ha csendélet fotózásról van szó, akkor nincs ok arra, hogy ne csináld jól. Annyi időd van, amennyire szükséged van egy jó munka elvégzéséhez!</p>
<p>A tájkép fotózástól eltérően a fény nem változik gyorsan, a portrétól eltérően a témád nem fogja elunni magát a hosszú ideig tartó mozdulatlanságtól. Használd ki ezt a lehetőséget, állítsd be a témádat, a világítást, a hátteret és a kamerát, készíts néhány felvételt, majd mozdítsd el egy kicsit a dolgokat, és készíts újakat. Ha eljutsz egy olyan pontig, hogy úgy érzed, a dolgok nem mennek rendesen, akkor hagyj mindent beállítva, készíts magadnak egy csésze teát, és térj vissza hozzá később felfrissülve.</p>
<p>Egy másik előny az, hogy nincs mentség arra, hogy nem tiszták és élesek a képek, szánj időt a világítás és a fókusz helyes megválasztására. Ha szert tudsz tenni rá, akkor egy makró objektív ideális lenne egy ilyen típusú munkához, de ha nem, akkor válaszd ki a makró módot a fényképezőgépeden, hogy a legjobb esélyed legyen a témád közeli részletének megragadására.</p>
<SimpleFigure fileName="7.jpg" altText="Illusztráció" caption="Fotó: vamedia"/>

<h2>8. A nagy mesterek ihletése</h2>
<p>Ha küszködsz a világítással, a kompozícióval vagy a képeid felépítésével, akkor ihletet kell keresned, és hol máshol keress, mint az élmúlt évek eredeti csendélet remekeiben. Keress rá az interneten a reneszánsz csendélet művészeire, és figyeld meg a munkáik elemeit.</p>
<p>Ezeknek a festményeknek a tanulmányozása segíteni fog neked a formák, az árnyékok megfigyelésében és a színek együttes működésének megértésében, és remélhetőleg adni fog néhány ötletet arra, hogy hogyan építsd fel a fotográfiai munkáidat úgy, hogy erős és érdekes képeket készíthess.</p>
<SimpleFigure fileName="8.jpg" altText="Illusztráció" caption="Fotó: layos"/>

<h2>9. Most rajtad a sor!</h2>
<p>Eljött az ideje, hogy elkezdd. Keress a naptáradban egy csendes napot, és szánj időt a gyakorlásra. Próbáld beállítani a fényképezőgépedet és a hátteret egy megfelelő fényforráshoz közel egy ablak mellett, és kezdj el kattintgatni!</p>
<p>Miután elsajátítottad az alapokat, próbálj kreatívabb lenni, kísérletezz a kameraállásokkal, a világítási szögekkel és alternatív fényforrásokkal, mint a gyertyák és lámpák. Megpróbálhatsz kreatívabb lenni a rekesznyílással is, és használj egy f/1.8-as elsődleges lencsét egy művészi sekély fókusz elérése érdekében. Ám ha egyetlen dolgot választasz ki ebből az oktatóleckéből, akkor az legyen ez: a csendélet fotózása nem a gyümölcsöket és a virágokat jelenti! Találj tehát egyedi és inspiráló témákat, amelyek lelkesedéssel töltenek el, és kezdj el kattintani!</p>
<SimpleFigure fileName="9.jpg" altText="Illusztráció" caption="Fotó: apwizard"/>

<h2>10. Megélhetés?</h2>
<p>Nagyon sok igény van a csendélet fotózásra, különösen most, hogy a fotósok számára ennyire egyszerű képeket készíteni a stock fotó oldalak számára, amelyek elérhetőek a magazinok, üzleti kiadványok és online tartalmak számára. Miután elkészítetted a felvételeket, ne félj megosztani őket online, megpróbálhatod akár az Envato PhotoDune stock fotó oldalát. Így minden egyes alkalommal, amikor elkészítesz egy beállítást a fotózáshoz, dolgozz úgy mintha ez egy megbízás lenne, soha nem tudhatod, a csendéleted még pénzt is hozhat neked közben!</p>
<SimpleFigure fileName="10.jpg" altText="Illusztráció" caption="Fotó: gfpeck"/>
