// frontend/src/website/components/App.tsx
import React, {useEffect, useState} from 'react';
import {BrowserRouter, Switch, Route, useHistory, Redirect} from 'react-router-dom';
import {useAuth0} from '../../auth/components/Auth0Provider';
import {useI18n} from '../../i18n/components/I18nProvider';
import ReactGA from 'react-ga';
// import LogRocket from 'logrocket';
//import {config} from '../../config';

import PhotoUploader from '../../upload/PhotoUploader';

import ScrollToTop from './ScrollToTop';
import FullPageLoadingIndicator from './FullPageLoadingIndicator';
import NavigationBar from './NavigationBar';
import BugReportButton from '../../bug-report/components/BugReportButton';

import Error404Page from './Error404Page';
import FrontPage from '../../front-page/components/FrontPage';
import AboutPage from '../../about/components/AboutPage';
import FaqPage from '../../faq/components/FaqPage';
import ContactPage from '../../contact/components/ContactPage';
import UploadPage from '../../upload/components/UploadPage';
import CoursePage from '../../challenges/components/CoursePage';
import ChallengePage from '../../challenges/components/ChallengePage';
import MaterialsPage from '../../materials/components/MaterialsPage';
import BugReportPage from '../../bug-report/components/BugReportPage';
import MaterialPage from '../../materials/components/MaterialPage';
import Footer from './Footer';
import PhotatoMessagesPage from '../../admin/messages/components/PhotatoMessagesPage';
import PhotatoMessagePage from '../../admin/messages/components/PhotatoMessagePage';
import SitemapGeneratorPage from '../../admin/sitemap-generator/components/SitemapGeneratorPage';
import AdminPage from '../../admin/components/AdminPage';
import PermissionHelper from '../../auth/PermissionHelper';
import ReactPixel from '../reactPixel';
import Error403Page from './Error403Page';
import {getAndRemoveRedirectPath} from '../../auth/auth0LoginHandler';
import AdminPhotosPage from '../../admin/photos/components/AdminPhotosPage';

const photoUploader = new PhotoUploader();
const permissionHelper = new PermissionHelper();

export default function App() {
    const {areTranslationsLoaded} = useI18n();
    const history = useHistory();
    /* User type: https://auth0.com/docs/api/authentication#user-profile or check “auth0UserInfoSchema” in back end */
    const {loading: isAuthLoading, isAuthenticated, user} = useAuth0();
    const [isTrackingInitialized, setIsTrackingInitialized] = useState(false);
    const [areFontsReady, setFontsReady] = useState(false);

    useEffect(() => {
        async function checkFontsLoaded() {
            // noinspection JSUnresolvedVariable (It actually exists.)
            await document.fonts.ready;
            setFontsReady(true);
        }

        // noinspection JSIgnoredPromiseFromCall
        checkFontsLoaded();
    }, []);

    /* Initialize Google Analytics page view tracking */
    useEffect(() => {
        if (history && !isTrackingInitialized) {
            history.listen(location => {
                ReactGA.set({page: location.pathname}); /* Update the user’s current page */
                ReactGA.pageview(location.pathname); /* Record a page view for the given page */
                ReactPixel.pageView();
            });
            setIsTrackingInitialized(true);
        }
    }, [history]);

    /* Set Google Analytics user sub if we have any */
    useEffect(() => {
        if (isAuthenticated && user) {
            ReactGA.set({
                userSub: isAuthenticated ? user.sub : undefined,
                /* Can add any data that is relevant to the session and would like to track with Google Analytics */
            });

            // if (config.environment === 'production') {
            //     LogRocket.identify(user.sub, { /* More info and options: https://app.logrocket.com/veujlu/photato-website/settings/setup */
            //         name: user.name,
            //         email: user.email,
            //     });
            // }
        }
    }, [isAuthenticated, user]);

    const publicRoutes = _getPublicRoutes();
    const memberRoutes = _getMemberRoutes(isAuthenticated);
    const adminRoutes = _getAdminRoutes(isAuthenticated && user && permissionHelper.isAdmin(user.email));

    return areTranslationsLoaded && areFontsReady && !isAuthLoading
        ?
        <BrowserRouter basename='/'>
            <ScrollToTop/>
            <NavigationBar/>
            <BugReportButton/>
            <main>
                <Switch>
                    {publicRoutes}
                    {memberRoutes}
                    {adminRoutes}
                    <Route path='/' key='Error404Page'>
                        <Error404Page/>
                    </Route>
                </Switch>
            </main>
            <Footer/>
        </BrowserRouter>
        :
        <FullPageLoadingIndicator/>;
}

function _getPublicRoutes() {
    return [
        <Route path='/' exact={true} key='FrontPage'>
            <FrontPage/>
        </Route>,
        <Route path='/about' key='AboutPage'>
            <AboutPage/>
        </Route>,
        <Route path='/faq' key='FaqPage'>
            <FaqPage/>
        </Route>,
        <Route path='/contact' key='ContactPage'>
            <ContactPage/>
        </Route>,
        <Route path='/materials' key='MaterialsPage'>
            <MaterialsPage/>
        </Route>,
        <Route path='/bug-report' key='BugReportPage'>
            <BugReportPage/>
        </Route>,
        <Route path='/:languageCode/article/:slug' key='MaterialPage'>
            <MaterialPage/>
        </Route>,
        <Route path='/:languageCode/external-article/:slug' key='MaterialPage'>
            <MaterialPage/>
        </Route>,
        <Route path='/login-callback' key='LoginCallbackRedirect'>
            <Redirect to={getAndRemoveRedirectPath() || '/'}/>
        </Route>,
    ];
}

function _getMemberRoutes(isAuthenticated: boolean | undefined) {
    return [
        <Route path='/upload' key='UploadPage'>
            {isAuthenticated ?
                <UploadPage photoUploader={photoUploader}/> :
                <Error403Page/>}
        </Route>,
        <Route path='/course' exact={true} key='CoursePage'>
            {isAuthenticated ?
                <CoursePage/> :
                <Error403Page/>}
        </Route>,
        <Route path='/challenges/:weekIndex' key='ChallengePage'>
            {isAuthenticated ?
                <ChallengePage/> :
                <Error403Page/>}
        </Route>,
    ];
}

function _getAdminRoutes(isAdmin: boolean | undefined) {
    return [
        <Route path='/admin' exact={true} key='AdminPage'>
            {isAdmin ?
                <AdminPage/> :
                <Error403Page/>}
        </Route>,
        <Route path='/admin/messages' key='AdminPhotatoMessagesPage'>
            {isAdmin ?
                <PhotatoMessagesPage/> :
                <Error403Page/>}
        </Route>,
        <Route path='/admin/message/:slug' key='AdminPhotatoMessagePage'>
            {isAdmin ?
                <PhotatoMessagePage/> :
                <Error403Page/>}
        </Route>,
        <Route path='/admin/photos' key='AdminPhotosPage'>
            {isAdmin ?
                <AdminPhotosPage/> :
                <Error403Page/>}
        </Route>,
        <Route path='/admin/sitemap-generator' key='SitemapGeneratorPage'>
            {isAdmin ?
                <SitemapGeneratorPage/> :
                <Error403Page/>}
        </Route>,
    ];
}

// frontend/src/website/components/App.svelte
<script lang="ts">
    import type {Component} from 'svelte';
    import {location, matchPath} from '../router.svelte';
    import {twemoji} from '../twemoji';
    import {areTranslationsLoaded} from '../../i18n/i18n.svelte';
    import {auth} from '../../auth/auth.svelte';

    import FullPageLoadingIndicator from './FullPageLoadingIndicator.svelte';
    import NavigationBar from './NavigationBar.svelte';
    import BugReportButton from '../../bug-report/components/BugReportButton.svelte';
    import Footer from './Footer.svelte';
    import Error404Page from './Error404Page.svelte';
    import Error403Page from './Error403Page.svelte';

    import FrontPage from '../../front-page/components/FrontPage.svelte';
    import AboutPage from '../../about/components/AboutPage.svelte';
    import FaqPage from '../../faq/components/FaqPage.svelte';
    import ContactPage from '../../contact/components/ContactPage.svelte';
    import MaterialsPage from '../../materials/components/MaterialsPage.svelte';
    import MaterialPage from '../../materials/components/MaterialPage.svelte';
    import BugReportPage from '../../bug-report/components/BugReportPage.svelte';
    import LoginPage from '../../auth/components/LoginPage.svelte';
    import LoginVerifyPage from '../../auth/components/LoginVerifyPage.svelte';
    import UploadPage from '../../upload/components/UploadPage.svelte';
    import CoursePage from '../../challenges/components/CoursePage.svelte';
    import ChallengePage from '../../challenges/components/ChallengePage.svelte';
    import AdminPage from '../../admin/components/AdminPage.svelte';
    import PhotatoMessagesPage from '../../admin/messages/components/PhotatoMessagesPage.svelte';
    import PhotatoMessagePage from '../../admin/messages/components/PhotatoMessagePage.svelte';
    import AdminPhotosPage from '../../admin/photos/components/AdminPhotosPage.svelte';
    import SitemapGeneratorPage from '../../admin/sitemap-generator/components/SitemapGeneratorPage.svelte';

    type Gate = 'public' | 'member' | 'admin';
    interface RouteDef {
        pattern: string;
        exact?: boolean;
        component: Component<any>;
        gate: Gate;
        extraProps?: Record<string, unknown>;
        /** Parse emoji into images across the whole page (the pages the old app wrapped in <Twemoji>). */
        parseEmoji?: boolean;
    }

    /* First match wins (like the old react-router <Switch>). Param routes are exact so they never
     * swallow a longer or shorter path. Member/admin gating is client-side convenience; the backend
     * enforces it regardless (401/403). */
    const routes: RouteDef[] = [
        {pattern: '/', exact: true, component: FrontPage, gate: 'public'},
        {pattern: '/about', exact: true, component: AboutPage, gate: 'public', parseEmoji: true},
        {pattern: '/faq', exact: true, component: FaqPage, gate: 'public', parseEmoji: true},
        {pattern: '/contact', exact: true, component: ContactPage, gate: 'public', parseEmoji: true},
        {pattern: '/materials', exact: true, component: MaterialsPage, gate: 'public'},
        {pattern: '/bug-report', exact: true, component: BugReportPage, gate: 'public'},
        {pattern: '/login', exact: true, component: LoginPage, gate: 'public'},
        {pattern: '/login/verify', exact: true, component: LoginVerifyPage, gate: 'public'},
        {pattern: '/:languageCode/article/:slug', exact: true, component: MaterialPage, gate: 'public', extraProps: {isExternalArticle: false}},
        {pattern: '/:languageCode/external-article/:slug', exact: true, component: MaterialPage, gate: 'public', extraProps: {isExternalArticle: true}},
        {pattern: '/upload', exact: true, component: UploadPage, gate: 'member'},
        {pattern: '/course', exact: true, component: CoursePage, gate: 'member'},
        {pattern: '/challenges/:weekIndex', exact: true, component: ChallengePage, gate: 'member'},
        {pattern: '/admin', exact: true, component: AdminPage, gate: 'admin'},
        {pattern: '/admin/messages', exact: true, component: PhotatoMessagesPage, gate: 'admin'},
        {pattern: '/admin/message/:slug', exact: true, component: PhotatoMessagePage, gate: 'admin'},
        {pattern: '/admin/photos', exact: true, component: AdminPhotosPage, gate: 'admin'},
        {pattern: '/admin/sitemap-generator', exact: true, component: SitemapGeneratorPage, gate: 'admin'},
    ];

    let fontsReady = $state(false);
    $effect(() => {
        void document.fonts.ready.then(() => {fontsReady = true;});
    });

    const ready = $derived(areTranslationsLoaded() && fontsReady && !auth.isLoading);

    const matched = $derived.by(() => {
        for (const route of routes) {
            const params = matchPath(route.pattern, location.pathname, {exact: route.exact});
            if (params) {
                return {route, params};
            }
        }
        return null;
    });

    /* Which component to render, applying the member/admin gate. */
    const view = $derived.by(() => {
        if (!matched) {
            return {component: Error404Page as Component<any>, props: {} as Record<string, unknown>, parseEmoji: false};
        }
        const {route, params} = matched;
        const allowed = route.gate === 'public'
            || (route.gate === 'member' && auth.isAuthenticated)
            || (route.gate === 'admin' && auth.isAdmin);
        if (!allowed) {
            return {component: Error403Page as Component<any>, props: {}, parseEmoji: false};
        }
        return {component: route.component, props: {...params, ...(route.extraProps ?? {})}, parseEmoji: route.parseEmoji === true};
    });
</script>

{#if ready}
    {@const View = view.component}
    <NavigationBar/>
    <BugReportButton/>
    <main use:twemoji={view.parseEmoji}>
        <View {...view.props}/>
    </main>
    <Footer/>
{:else}
    <FullPageLoadingIndicator/>
{/if}
