// frontend/src/website/components/Error404Page.svelte
<script lang="ts">
    import {__} from '../../i18n/i18n.svelte';
    import NavLinkButton from './NavLinkButton.svelte';

    $effect(() => {document.title = __('404 error') + ' - Photato';});
</script>

<h1>{__('404 error')}</h1>
<p>{__('This page does not exist.')}</p>
<p><NavLinkButton to="/">{__('Return to the Photato main page.')}</NavLinkButton></p>

// frontend/src/website/components/Error404Page.jsx
import React, {useEffect} from 'react';
import {useI18n} from '../../i18n/components/I18nProvider.jsx';
import NavLinkButton from './NavLinkButton.jsx';

export default function Error404Page() {
    const {__} = useI18n();

    useEffect(() => {document.title = __('404 error') + ' - Photato'}, []);

    return <>
        <h1>{__('404 error')}</h1>
        <p>{__('This page does not exist.')}</p>
        <p><NavLinkButton to='/'>{__('Return to the Photato main page.')}</NavLinkButton></p>
    </>;
}
