// frontend/src/website/components/Footer.svelte
<script lang="ts">
    import { __ } from '../../i18n/i18n.svelte'
    import { twemoji } from '../twemoji'
    import ExternalLink from '../../materials/components/ExternalLink.svelte'
</script>

<footer>
    <div class="copyright" use:twemoji>{__('Made with ❤️ by the Photato team')}</div>
    <div class="social">
        <ExternalLink
            href="https://www.facebook.com/photato12/"
            class="facebook icon"
            title={__('Photato’s Facebook page')}
        />
        <ExternalLink
            href="https://www.instagram.com/photatocourse/"
            class="instagram icon"
            title={__('Photato’s Instagram')}
        />
    </div>
</footer>

// frontend/src/website/components/Footer.jsx
import React from 'react';
import {useI18n} from '../../i18n/components/I18nProvider.jsx';
import ExternalLink from '../../materials/components/ExternalLink.jsx';
import Twemoji from './Twemoji.jsx';

export default function Footer() {
    const {__} = useI18n();

    return <footer>
        <Twemoji><div className='copyright'>{__('Made with ❤️ by the Photato team')}</div></Twemoji>
        <div className='social'>
            <ExternalLink href='https://www.facebook.com/photato12/'
                          className='facebook icon'
                          title={__('Photato’s Facebook page')}/>
            <ExternalLink href='https://www.instagram.com/photatocourse/'
                          className='instagram icon'
                          title={__('Photato’s Instagram')}/>
        </div>
    </footer>;
}
