// frontend/src/website/components/FullPageLoadingIndicator.svelte
<script lang="ts">
    import {__, areTranslationsLoaded} from '../../i18n/i18n.svelte';

    let isTakingLong = $state(false);
    $effect(() => {
        const timeout = setTimeout(() => {isTakingLong = true;}, 4000);
        return () => clearTimeout(timeout);
    });
</script>

<div id="fullPageLoadingIndicator">
    <div>
        <div class="spinner"></div>
        <div class="logo">
            <img src="/website/aperture-logo.svg" alt="logo" class="logo"/>
            <img src="/website/photato-logo-text.svg" alt="Photato" class="siteTitle"/>
        </div>
    </div>
    {#if isTakingLong && areTranslationsLoaded()}
        <div class="loadingTakingLong">{@html __('Loading seems to take longer than usual. If you think this is a problem, please report it here.')}</div>
    {/if}
</div>

// frontend/src/website/components/FullPageLoadingIndicator.tsx
import React, {useEffect, useState} from 'react';
import {useI18n} from '../../i18n/components/I18nProvider';

export default function FullPageLoadingIndicator() {
    const {__, areTranslationsLoaded} = useI18n();
    const [isTakingLong, setTakingLong] = useState(false);

    useEffect(() => {
        const timeout = setTimeout(() => {
            setTakingLong(true);
        }, 4000);

        return () => {
            clearTimeout(timeout);
        }
    });

    return <div id='fullPageLoadingIndicator'>
        <div>
            <div className='spinner'/>
            <div className='logo'>
                <img src='/website/aperture-logo.svg' alt="logo" className="logo" />
                <img src="/website/photato-logo-text.svg" alt="Photato" className="siteTitle" />
            </div>
        </div>
        {isTakingLong && areTranslationsLoaded ? <div className="loadingTakingLong">{__('Loading seems to take longer than usual. If you think this is a problem, please report it here.')}</div> : null}
    </div>;
}
