// frontend/src/website/components/NavigationBar.tsx
import React, {useEffect, useRef, useState} from 'react';
import {NavLink, useLocation} from 'react-router-dom';
import {config} from '../../config';
import {useAuth0} from '../../auth/components/Auth0Provider';
import {useI18n} from '../../i18n/components/I18nProvider';
import NavLinkMenuItemWithIcon from './NavLinkMenuItemWithIcon';
import PermissionHelper from '../../auth/PermissionHelper';
import {saveUrlAndLoginWithRedirect} from '../../auth/auth0LoginHandler';

const permissionHelper = new PermissionHelper();

export default function NavigationBar() {
    const {isAuthenticated, loginWithRedirect, user, logout} = useAuth0();
    const [isMenuVisible, setIsMenuVisible] = useState(false);
    const menuRef = useRef<HTMLElement>(null);
    const authenticationMenuRef = useRef<HTMLElement>(null);
    const {__} = useI18n();
    const location = useLocation();

    useEffect(() => {
        function hideMenusIfClickedOutside(event: MouseEvent) {
            if (menuRef.current && authenticationMenuRef.current
                && !menuRef.current.contains(event.target as Node) && !authenticationMenuRef.current.contains(event.target as Node)) {
                setIsMenuVisible(false);
            }
        }

        document.addEventListener("mousedown", hideMenusIfClickedOutside); /* Bind the event listener */
        return () => { document.removeEventListener("mousedown", hideMenusIfClickedOutside); }; /* Unbind the event listener on clean up */

    }, [menuRef, authenticationMenuRef]);

    // noinspection HtmlUnknownTarget
    return <header role='navigation'>
        <NavLink to='/' exact={true} className='logoContainer' title='Photato'>
            <img src='/website/aperture-logo.svg' alt="logo" className="logo" />
            <img src="/website/photato-logo-text.svg" alt="Photato" className="siteTitle" />
        </NavLink>{createMainMenu()}
        <div className='spacer'/>
        {!isAuthenticated && <a href='#' className='signInLink' onClick={() => saveUrlAndLoginWithRedirect(loginWithRedirect, location.pathname)}>{__('Sign in')}</a>}
        <div className='material-icons hamburgerMenu' onClick={toggleMenuVisibility}>menu
        </div>
        {isAuthenticated &&
        <img src={user?.picture} alt={__('Profile picture')} onClick={toggleMenuVisibility} className='profilePicture'/>}{isAuthenticated && createAuthenticationMenu()}
    </header>;


    function handleSignOut() {
        logout({returnTo: window.location.origin});
    }

    function createMainMenu() {
        /* List of icons: https://material.io/resources/icons/?style=baseline */
        return <nav ref={menuRef} className={isMenuVisible ? ' visible' : ''} onClick={() => {
            setIsMenuVisible(false);
        }}>
            <NavLinkMenuItemWithIcon to='/' exact={true} activeClassName='active' iconName='home'>{__('Home')}</NavLinkMenuItemWithIcon>
            <NavLinkMenuItemWithIcon to='/about' activeClassName='active' iconName='face'>{__('About')}</NavLinkMenuItemWithIcon>
            <NavLinkMenuItemWithIcon to='/faq' activeClassName='active' iconName='help'>{__('FAQ')}</NavLinkMenuItemWithIcon>
            <NavLinkMenuItemWithIcon to='/contact' activeClassName='active' iconName='alternate_email'>{__('Contact')}</NavLinkMenuItemWithIcon>
            {isAuthenticated ?
                <NavLinkMenuItemWithIcon to='/course' activeClassName='active' iconName='casino'>{config.course.titleWithoutPhotato}</NavLinkMenuItemWithIcon> : null}
            <NavLinkMenuItemWithIcon to='/materials' activeClassName='active' iconName='book'>{__('Materials')}</NavLinkMenuItemWithIcon>
            {isAuthenticated && permissionHelper.isAdmin(user?.email) ? <NavLinkMenuItemWithIcon to='/admin' activeClassName='active' iconName='lock'>{__('Admin')}</NavLinkMenuItemWithIcon> : null}
            {isAuthenticated ?
                <div className='menuItem separator'>
                    <span className='material-icons'/>
                    <hr/>
                </div> : null}
            {isAuthenticated ?
                <a href='#' className='menuItem signOut' onClick={handleSignOut}><span className='profile icon'><img src={user?.picture} alt={__('Profile picture')} className='profilePicture'/></span><span className='title'>{__('Sign out')}</span></a> : null}
        </nav>;
    }

    function createAuthenticationMenu() {
        const className = 'authenticationMenu' + (isMenuVisible ? ' visible' : '');

        function hideMenu() {
            setIsMenuVisible(false);
        }

        return <nav ref={authenticationMenuRef} className={className} onClick={hideMenu}>
            <a href='#' className='menuItem signOut' onClick={handleSignOut}><span className='icon material-icons'>exit_to_app</span><span className='title'>{__('Sign out')}</span></a>
        </nav>;
    }

    function toggleMenuVisibility() {
        setIsMenuVisible(!isMenuVisible);
    }
}

// frontend/src/website/components/NavigationBar.svelte
<script lang="ts">
    import {config} from '../../config';
    import {__} from '../../i18n/i18n.svelte';
    import {auth, logout} from '../../auth/auth.svelte';
    import {navigate} from '../router.svelte';
    import Link from './Link.svelte';
    import NavLinkMenuItemWithIcon from './NavLinkMenuItemWithIcon.svelte';

    let isMenuVisible = $state(false);
    let menuRef = $state<HTMLElement | null>(null);

    /* Hide the popup menu when clicking anywhere outside it (mobile only; on desktop the menu is a fixed
     * bar and this is a no-op). */
    $effect(() => {
        function hideMenuIfClickedOutside(event: MouseEvent) {
            if (menuRef && !menuRef.contains(event.target as Node)) {
                isMenuVisible = false;
            }
        }
        document.addEventListener('mousedown', hideMenuIfClickedOutside);
        return () => document.removeEventListener('mousedown', hideMenuIfClickedOutside);
    });

    function toggleMenuVisibility() {
        isMenuVisible = !isMenuVisible;
    }

    async function handleSignOut() {
        await logout();
        navigate('/');
    }
</script>

<header role="navigation">
    <Link to="/" exact={true} class="logoContainer" title="Photato">
        <img src="/website/aperture-logo.svg" alt="logo" class="logo"/>
        <img src="/website/photato-logo-text.svg" alt="Photato" class="siteTitle"/>
    </Link>
    <nav bind:this={menuRef} class={isMenuVisible ? 'visible' : ''} onclick={() => (isMenuVisible = false)}>
        <NavLinkMenuItemWithIcon to="/" exact={true} iconName="home">{__('Home')}</NavLinkMenuItemWithIcon>
        <NavLinkMenuItemWithIcon to="/about" iconName="face">{__('About')}</NavLinkMenuItemWithIcon>
        <NavLinkMenuItemWithIcon to="/faq" iconName="help">{__('FAQ')}</NavLinkMenuItemWithIcon>
        <NavLinkMenuItemWithIcon to="/contact" iconName="alternate_email">{__('Contact')}</NavLinkMenuItemWithIcon>
        {#if auth.isAuthenticated}
            <NavLinkMenuItemWithIcon to="/course" iconName="casino">{config.course.titleWithoutPhotato}</NavLinkMenuItemWithIcon>
        {/if}
        <NavLinkMenuItemWithIcon to="/materials" iconName="book">{__('Materials')}</NavLinkMenuItemWithIcon>
        {#if auth.isAdmin}
            <NavLinkMenuItemWithIcon to="/admin" iconName="lock">{__('Admin')}</NavLinkMenuItemWithIcon>
        {/if}
        {#if auth.isAuthenticated}
            <a href="#logout" class="menuItem" onclick={(event) => {event.preventDefault(); void handleSignOut();}}><span class="icon material-icons">exit_to_app</span><span class="title">{__('Sign out')}</span></a>
        {/if}
    </nav>
    <div class="spacer"></div>
    {#if !auth.isAuthenticated}
        <a href="/login" class="signInLink" onclick={(event) => {event.preventDefault(); navigate('/login');}}>{__('Sign in')}</a>
    {/if}
    <div class="material-icons hamburgerMenu" onclick={toggleMenuVisibility}>menu</div>
</header>
