// frontend/src/challenges/components/ChallengeList.jsx
import React from 'react';
import {NavLink} from 'react-router-dom';
import {config} from '../../config.jsx';
import {useI18n} from '../../i18n/components/I18nProvider.jsx';
import {weeklyChallengeTitles} from '../challengeRepository.jsx';
import {useCourseData} from './CourseDataProvider.jsx';

export default function ChallengeList() {
    const {__} = useI18n();
    const {currentWeekIndex} = useCourseData();
    const weekCount = config.course.weekCount;
    const weekIndexes = Array.from(Array(Math.min(currentWeekIndex, weekCount)), (value, key) => key + 1);
    const challengeLinks = weekIndexes.map(weekIndex =>
        <p>
            <NavLink to={'/challenges/' + weekIndex}>
                {__('Week {weekIndex}:', {weekIndex}) + ' ' + __(weeklyChallengeTitles[weekIndex - 1])}
            </NavLink>
        </p>);
    return <div className='challengeList'>{challengeLinks}</div>;
}

// frontend/src/challenges/components/ChallengeList.svelte
<script lang="ts">
    import {config} from '../../config';
    import {__} from '../../i18n/i18n.svelte';
    import {weeklyChallengeTitles} from '../challengeRepository';
    import {courseData} from '../courseData';
    import Link from '../../website/components/Link.svelte';

    const weekCount = config.course.weekCount;
    const weekIndexes = Array.from(Array(Math.min(courseData.currentWeekIndex, weekCount)), (value, key) => key + 1);
</script>

<div class="challengeList">
    {#each weekIndexes as weekIndex (weekIndex)}
        <p>
            <Link to={'/challenges/' + weekIndex}>
                {__('Week {weekIndex}:', {weekIndex}) + ' ' + __(weeklyChallengeTitles[weekIndex - 1])}
            </Link>
        </p>
    {/each}
</div>
