// frontend/src/materials/components/MaterialsPage.jsx
import React, {useState, useEffect} from 'react';
import {config} from '../../config.jsx';
import {useI18n} from '../../i18n/components/I18nProvider.jsx';
import {useCourseData} from '../../challenges/components/CourseDataProvider.jsx';
import {NavLink} from 'react-router-dom';
import {weeklyChallengeTitles} from '../../challenges/challengeRepository.jsx';
import {ownArticleSlugsByLanguageAndByWeek, thirdPartyArticleSlugsByLanguageAndByWeek} from '../articles-repository.jsx';
import ExternalLink from './ExternalLink.jsx';

/**
 * @typedef {Object} ArticleMetadata
 * @property {string} slug
 * @property {string} title
 * @property {string|null} author
 * @property {Date} publishDate
 * @property {string} publisherName
 * @property {string} [originalUrl] Only applicable for external articles.
 * @property {boolean} [isOriginalUrlBroken] Only applicable for external articles.
 */
/**
 * @typedef {Object} LoadedArticle
 * @property {function(): ArticleMetadata} getMetadata
 * @property {function(): string} getContent
 */

export default function MaterialsPage() {
    const {getActiveLocaleCode, __} = useI18n();
    const {currentDayIndex} = useCourseData();

    const languageCode = getActiveLocaleCode().substring(0, 2);
    const ownSlugsByLanguageAndByWeek = ownArticleSlugsByLanguageAndByWeek[languageCode];
    const thirdPartySlugsByLanguageAndByWeek = thirdPartyArticleSlugsByLanguageAndByWeek[languageCode];

    /* Load articles */

    const [/** @type {Object<int, LoadedArticle[]>} */ ownArticlesByWeek, setOwnArticlesByWeek] = useState({});
    const [/** @type {Object<int, LoadedArticle[]>} */ thirdPartyArticlesByWeek, setThirdPartyArticlesByWeek] = useState({});
    useEffect(() => {
        /**
         * @param {string[]} slugs
         * @param {"own"|"third-party"} ownership
         * @returns {Promise<LoadedArticle[]>}
         */
        function loadArticlesForOneWeek(slugs, ownership) {
            return Promise.all(slugs.map(slug => import((`../${ownership}-content/${languageCode}/${slug}.jsx`))));
        }

        async function loadArticlesForAllWeeks() {
            /** @type {{weekIndex: string, articles: LoadedArticle[]}[]} */
            const ownArticlePromisesForEachWeek = Object.entries(ownSlugsByLanguageAndByWeek)
                .map(async ([weekIndex, slugs]) => ({weekIndex, articles: await loadArticlesForOneWeek(slugs, 'own')}));
            /** @type {{weekIndex: string, articles: LoadedArticle[]}[]} */
            const thirdPartyArticlePromisesForEachWeek = Object.entries(thirdPartySlugsByLanguageAndByWeek)
                .map(async ([weekIndex, slugs]) => ({weekIndex, articles: await loadArticlesForOneWeek(slugs, 'third-party')}));
            /** @type {Object<int, LoadedArticle[]>} */
            const ownArticlesForEachWeek = (await Promise.all(ownArticlePromisesForEachWeek))
                .reduce((object, {weekIndex, articles}) => ({...object, [parseInt(weekIndex)]: articles}), {});
            const thirdPartyArticlesForEachWeek = (await Promise.all(thirdPartyArticlePromisesForEachWeek))
                .reduce((object, {weekIndex, articles}) => ({...object, [parseInt(weekIndex)]: articles}), {});
            setOwnArticlesByWeek(ownArticlesForEachWeek);
            setThirdPartyArticlesByWeek(thirdPartyArticlesForEachWeek);
        }

        loadArticlesForAllWeeks().then(() => {});
        document.title = __('Articles about photography') + ' - Photato';
    }, []);

    return <>
        <h1>{__('Articles about photography')}</h1>
        <p>{__('Some of these articles are not our own. [...]')}</p>
        {renderList()}
    </>;

    function renderList() {
        if (Object.keys(ownArticlesByWeek).length && Object.keys(thirdPartyArticlesByWeek).length) {
            const currentWeekIndexWithBoundariesAndSunday = Math.min(Math.floor(currentDayIndex / 7) + 1, config.course.weekCount);
            if (currentWeekIndexWithBoundariesAndSunday >= 1) {
                const weekIndexes = [...Array(currentWeekIndexWithBoundariesAndSunday + 1).keys()].slice(1);
                return weekIndexes.map(weekIndex => renderOneWeek(weekIndex, [...ownArticlesByWeek[weekIndex], ...thirdPartyArticlesByWeek[weekIndex]]))
            } else {
                return <>
                    <h2>{__('Week #{weekIndex}', {weekIndex: 1})} – ???</h2>
                    <p>{__('The course hasn’t started. Helpful articles will be added here as the course progresses. Check back later!')}</p>
                </>;
            }
        } else {
            return <p>{__('Loading articles...')}</p>;
        }
    }

    /**
     * @param {int} weekIndex One-based
     * @param {LoadedArticle[]} articles
     * @returns {React.ReactElement[]|null}
     */
    function renderOneWeek(weekIndex, articles) {
        return articles.length ? <div key={weekIndex}>
            <h2>{__('Week #{weekIndex}', {weekIndex})} – {__(weeklyChallengeTitles[weekIndex - 1])}</h2>
            <ul>{articles.map(renderArticleToListElement)}</ul>
        </div> : null;
    }

    /**
     * @param {LoadedArticle} article
     */
    function renderArticleToListElement(article) {
        const metadata = article.getMetadata();
        if (article.getMetadata().publisherName === 'Photato') {
            return <li className="own" key={metadata.slug}>
                <NavLink to={'/' + languageCode + '/article/' + metadata.slug}>{metadata.title}</NavLink> ({__('Photato article')})
            </li>;
        } else {
            return <li className={metadata.isOriginalUrlBroken ? 'thirdParty broken' : 'thirdParty'} key={metadata.slug}>
                [<NavLink to={'/' + languageCode + '/external-article/' + metadata.slug}>{__('Photato cached version')}</NavLink>]&nbsp;
                {!metadata.isOriginalUrlBroken
                    ? <ExternalLink href={metadata.originalUrl}>{metadata.publisherName + ': ' + metadata.title}</ExternalLink>
                    : metadata.publisherName + ': ' + metadata.title}
                {metadata.isOriginalUrlBroken && ' – ' + __('the original article is not available anymore 😞')}
            </li>;
        }
    }
}

// frontend/src/materials/components/MaterialsPage.svelte
<script lang="ts">
    import {onMount} from 'svelte';
    import {config} from '../../config';
    import {__, getActiveLocaleCode} from '../../i18n/i18n.svelte';
    import {courseData} from '../../challenges/courseData';
    import Link from '../../website/components/Link.svelte';
    import {weeklyChallengeTitles} from '../../challenges/challengeRepository';
    import {ownArticleSlugsByLanguageAndByWeek, thirdPartyArticleSlugsByLanguageAndByWeek} from '../articles-repository';
    import ExternalLink from './ExternalLink.svelte';
    import type {LoadedArticle} from '../types';

    type ArticlesByWeek = Record<number, LoadedArticle[]>;

    const languageCode = getActiveLocaleCode().substring(0, 2);
    const ownSlugsByWeek = (ownArticleSlugsByLanguageAndByWeek as Record<string, Record<number, string[]>>)[languageCode];
    const thirdPartySlugsByWeek = (thirdPartyArticleSlugsByLanguageAndByWeek as Record<string, Record<number, string[]>>)[languageCode];

    let ownArticlesByWeek = $state<ArticlesByWeek>({});
    let thirdPartyArticlesByWeek = $state<ArticlesByWeek>({});

    function loadArticlesForOneWeek(slugs: string[], ownership: 'own' | 'third-party'): Promise<LoadedArticle[]> {
        return Promise.all(slugs.map(slug =>
            (ownership === 'own'
                ? import(`../own-content/${languageCode}/${slug}.svelte`)
                : import(`../third-party-content/${languageCode}/${slug}.svelte`)) as Promise<LoadedArticle>));
    }

    onMount(async () => {
        const ownPromises = Object.entries(ownSlugsByWeek)
            .map(async ([weekIndex, slugs]) => ({weekIndex, articles: await loadArticlesForOneWeek(slugs, 'own')}));
        const thirdPartyPromises = Object.entries(thirdPartySlugsByWeek)
            .map(async ([weekIndex, slugs]) => ({weekIndex, articles: await loadArticlesForOneWeek(slugs, 'third-party')}));
        ownArticlesByWeek = (await Promise.all(ownPromises))
            .reduce<ArticlesByWeek>((object, {weekIndex, articles}) => ({...object, [parseInt(weekIndex)]: articles}), {});
        thirdPartyArticlesByWeek = (await Promise.all(thirdPartyPromises))
            .reduce<ArticlesByWeek>((object, {weekIndex, articles}) => ({...object, [parseInt(weekIndex)]: articles}), {});
    });

    $effect(() => {document.title = __('Articles about photography') + ' - Photato';});

    let isLoaded = $derived(Object.keys(ownArticlesByWeek).length > 0 && Object.keys(thirdPartyArticlesByWeek).length > 0);
    let currentWeek = $derived(Math.min(Math.floor(courseData.currentDayIndex / 7) + 1, config.course.weekCount));
    let weekIndexes = $derived(currentWeek >= 1 ? [...Array(currentWeek + 1).keys()].slice(1) : []);

    function articlesForWeek(weekIndex: number): LoadedArticle[] {
        return [...(ownArticlesByWeek[weekIndex] ?? []), ...(thirdPartyArticlesByWeek[weekIndex] ?? [])];
    }
</script>

<h1>{__('Articles about photography')}</h1>
<p>{@html __('Some of these articles are not our own. [...]')}</p>

{#if !isLoaded}
    <p>{__('Loading articles...')}</p>
{:else if currentWeek >= 1}
    {#each weekIndexes as weekIndex (weekIndex)}
        {@const articles = articlesForWeek(weekIndex)}
        {#if articles.length}
            <div>
                <h2>{__('Week #{weekIndex}', {weekIndex})} – {__(weeklyChallengeTitles[weekIndex - 1])}</h2>
                <ul>
                    {#each articles as article (article.getMetadata().slug)}
                        {@const metadata = article.getMetadata()}
                        {#if metadata.publisherName === 'Photato'}
                            <li class="own">
                                <Link to={'/' + languageCode + '/article/' + metadata.slug}>{metadata.title}</Link> ({__('Photato article')})
                            </li>
                        {:else}
                            <li class={metadata.isOriginalUrlBroken ? 'thirdParty broken' : 'thirdParty'}>
                                [<Link to={'/' + languageCode + '/external-article/' + metadata.slug}>{@html __('Photato cached version')}</Link>]&nbsp;{#if !metadata.isOriginalUrlBroken}<ExternalLink href={metadata.originalUrl}>{metadata.publisherName + ': ' + metadata.title}</ExternalLink>{:else}{metadata.publisherName + ': ' + metadata.title}{/if}{#if metadata.isOriginalUrlBroken}{' – ' + __('the original article is not available anymore 😞')}{/if}
                            </li>
                        {/if}
                    {/each}
                </ul>
            </div>
        {/if}
    {/each}
{:else}
    <h2>{__('Week #{weekIndex}', {weekIndex: 1})} – ???</h2>
    <p>{__('The course hasn’t started. Helpful articles will be added here as the course progresses. Check back later!')}</p>
{/if}
